import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

export interface CppCuteBrowserHeaderDistributionReproducibilityOutputV2 extends JsonObject {
  readonly outputPath: string;
  readonly sha256: string;
  readonly byteLength: string;
}

/** Generated by cpp_cute_browser_header_distribution_reproducibility_authoring.mjs. */
const CPP_CUTE_BROWSER_HEADER_DISTRIBUTION_REPRODUCIBILITY_V2_VALUE = {
  "schema": "browsergrad.compiler.cpp-cute.browser-header-distribution-reproducibility",
  "version": 2,
  "authority": "two-root-exact-header-distribution-reproducibility-observation-only",
  "scope": "five-header-packs-license-inventory-and-notice-outputs-only",
  "verifierSourceRevision": "8f69487e1256dcd700339a72c01c77c587b3ca87",
  "buildInputLockId": "bg.cpp.browser-build-input-lock.sha256.08ddf15cbd0e5600fd1ae9f935cc7e3552e0140b665138ccdcf6d0f837bcdc34",
  "buildInputLockResourceSha256": "b0021295d4b9295abc3d8ef90a84883f3deae430d97446e5166444d0d82f025d",
  "headerInputProjectionId": "bg.cpp.browser-header-input-projection.sha256.48490ddb7b2fe655ec36824e276b90122e2f548a77b768f5978029a31129c5b7",
  "pipelineId": "bg.cpp.browser-header-pack-pipeline.sha256.4145f20e8bf8d617bc19cd3cdb6a44e0224a001581290fd95281b7b2eaaec3fa",
  "outputVerificationId": "bg.cpp.distribution-output-file-verification.sha256.a7e52dd81789859e6c3f718f210793d5dd4a891a4b26a07a41a94683df2c49f7",
  "reproducibilityId": "bg.cpp.browser-header-distribution-reproducibility.sha256.786197fcadb7421405943fa87c3c647b06b98aeb116554aeb7cdb058a46b0252",
  "outputs": [
    {
      "outputPath": "assets/browsergrad-cpp-cute/THIRD_PARTY_NOTICES.txt",
      "sha256": "5086675598ef771d8909ddb599786b4307534152af379463777b538546440472",
      "byteLength": "115330"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/clang-resource.headers.bgvfs",
      "sha256": "037acb8aaae9a437ed8275ca608dd92c31a142aa8c882b7ac238e80b3343805e",
      "byteLength": "7704705"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/cuda-12.6.3.headers.bgvfs",
      "sha256": "1917ba19e65d1e3be9dfe23b80c693ba8de5ce8e44538a7d16715cd61ece2cbd",
      "byteLength": "18954596"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/cutlass-3.7.0.headers.bgvfs",
      "sha256": "4f1c39b73f2fa7252628a253f7bb5b1411bdfdada872c5ff733b1b9008d89555",
      "byteLength": "21403975"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/libcxx-22.1.8.headers.bgvfs",
      "sha256": "1f2c5a1e86b04c29b6af33cc3fba0487b9bdcb87affaa44fceb32bec424e7dba",
      "byteLength": "12689654"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/license-inventory.json",
      "sha256": "7a49e4b82bdc0cf38e0d27079650d112cae4df085b02fd4d416c907ff0308085",
      "byteLength": "1208403"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/linux-sysroot.headers.bgvfs",
      "sha256": "d04a460dc605703b8e8a104cc5c043e6a7020ca7201991470c615273d43e7ae4",
      "byteLength": "8927070"
    },
    {
      "outputPath": "licenses/browsergrad-compiler.LICENSE",
      "sha256": "84996b33d49ed1a25655a12449c504089e2ac164f3f27a2c893711010bef1620",
      "byteLength": "1070"
    },
    {
      "outputPath": "licenses/clang.LICENSE.txt",
      "sha256": "ebcd9bbf783a73d05c53ba4d586b8d5813dcdf3bbec50265860ccc885e606f47",
      "byteLength": "15140"
    },
    {
      "outputPath": "licenses/compiler-rt.LICENSE.txt",
      "sha256": "1a8f1058753f1ba890de984e48f0242a3a5c29a6a8f2ed9fd813f36985387e8d",
      "byteLength": "16708"
    },
    {
      "outputPath": "licenses/cutlass.LICENSE.txt",
      "sha256": "42fec630f410aa308f70a51a89fadcd19586fa620f9831a32bee528a9a10000e",
      "byteLength": "1547"
    },
    {
      "outputPath": "licenses/emscripten-musl.COPYRIGHT",
      "sha256": "b870108ec5e7790e9f9919064f1b9421d62d5f9b0e6c230c6adf7ea2da62e97b",
      "byteLength": "6196"
    },
    {
      "outputPath": "licenses/emscripten.LICENSE",
      "sha256": "620a78084fc7ca97c0b5dea9abf891f3ffcadfdbf305276f099c9c4e12fc1d86",
      "byteLength": "5093"
    },
    {
      "outputPath": "licenses/libcxx.LICENSE.txt",
      "sha256": "539dd7aed86e8a4f12cbdd0e6c50c189c7d74847e4fecc64ce2c6ee3a01da38b",
      "byteLength": "16703"
    },
    {
      "outputPath": "licenses/libcxxabi.LICENSE.txt",
      "sha256": "e2b35be49f7284a45b7baca8fc7b3ab7440e7902392b2528a457816b5bb2a15c",
      "byteLength": "16706"
    },
    {
      "outputPath": "licenses/libunwind.LICENSE.txt",
      "sha256": "b5efebcaca80879234098e52d1725e6d9eb8fb96a19fce625d39184b705f7b6d",
      "byteLength": "16706"
    },
    {
      "outputPath": "licenses/llvm.LICENSE.txt",
      "sha256": "8d85c1057d742e597985c7d4e6320b015a9139385cff4cbae06ffc0ebe89afee",
      "byteLength": "15141"
    }
  ],
  "totals": {
    "outputCount": 17,
    "byteLength": "71114743"
  },
  "claims": {
    "twoDistinctPrivateOutputRootsVerified": true,
    "exactOutputsRehashedInBothRoots": true,
    "exactHeaderDistributionOutputSetReproducible": true,
    "fullDistributedOutputSetReproducible": false,
    "externalDistributedFileLicenseMapReviewed": false,
    "licenseReviewComplete": false,
    "distributionAuthorized": false,
    "signedProvenanceVerified": false,
    "workerExecutionObserved": false,
    "releaseReady": false
  }
} as const satisfies JsonObject;

export type CppCuteBrowserHeaderDistributionReproducibilityResourceV2 =
  typeof CPP_CUTE_BROWSER_HEADER_DISTRIBUTION_REPRODUCIBILITY_V2_VALUE;

export const CPP_CUTE_BROWSER_HEADER_DISTRIBUTION_REPRODUCIBILITY_V2_RESOURCE =
  deepFreezeJson(
    CPP_CUTE_BROWSER_HEADER_DISTRIBUTION_REPRODUCIBILITY_V2_VALUE,
  ) as unknown as CppCuteBrowserHeaderDistributionReproducibilityResourceV2;
