import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

export interface CppCuteBrowserFullDistributionReproducibilityOutputV1 extends JsonObject {
  readonly outputPath: string;
  readonly role: string;
  readonly mediaType: string;
  readonly sha256: string;
  readonly byteLength: string;
}

/** Generated by cpp_cute_browser_full_distribution_reproducibility_authoring.mjs. */
const CPP_CUTE_BROWSER_FULL_DISTRIBUTION_REPRODUCIBILITY_V1_VALUE = {
  "schema": "browsergrad.compiler.cpp-cute.browser-full-distribution-reproducibility-observation",
  "version": 1,
  "authority": "two-root-exact-full-distribution-reproducibility-observation-only",
  "verifierSourceRevision": "c039842b6155fd62ac662e7f5205bb9ba2a4ae86",
  "materializerSourceRevision": "c039842b6155fd62ac662e7f5205bb9ba2a4ae86",
  "producerPolicyScope": "local-engineering-reproducibility-only",
  "buildInputLockId": "bg.cpp.browser-build-input-lock.sha256.08ddf15cbd0e5600fd1ae9f935cc7e3552e0140b665138ccdcf6d0f837bcdc34",
  "buildInputLockResourceSha256": "b0021295d4b9295abc3d8ef90a84883f3deae430d97446e5166444d0d82f025d",
  "reproducibilityId": "bg.cpp.browser-full-distribution-reproducibility.sha256.5543bed26d97d5b10498794ca2e1c1f47c17ebb0b7ac28d2a5814538031b80b3",
  "deterministicMetadata": {
    "metadataId": "bg.cpp.browser-distribution-metadata.sha256.05641c9bb57a1f2bd9def6af22eb8b9da6d5b5c4bacbfdfb48dc53a45a2e3bda",
    "profileId": "browsergrad.compiler.cpp-cute.browser-clang@1",
    "profileHash": "bef58d9cf127e542d473039269d83cb54269ed710bf144b053ea5da9a9fda2a3",
    "compilationContractHash": "bc909fc7331ccac6c781ed6c11363ce58b68b1d5cf1bc04f9f7275bdd68cc965",
    "profileSha256": "79ea59b9a1fcfce14df17ebf22bd70691c195a15136adffd1a27d228a3f80958",
    "profileByteLength": "7148",
    "assetManifestId": "bg.cpp.browser-assets.sha256.97ffd5434c8b8b88b1e461aab5285bd63ab512b339619568e0379184dff6e13b",
    "assetManifestSha256": "307a17722eb9892b29e63fd68f02368ef706f85271f29cdcd2d57c5634afe855",
    "assetManifestByteLength": "11501",
    "assetSetSha256": "e8df813538e9f867ecc6085cc2cfb07142a9af70b0ad3c6777d618aad90f04ef",
    "buildSubjectId": "bg.cpp.browser-build-subject.sha256.d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42",
    "buildSubjectSha256": "d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42",
    "wasmSha256": "937ffe559aa5bd57db7eeecd26a590d90344457e6a6e0b06151afb6cfcc3fb6d",
    "wasmByteLength": "31841971",
    "workerBundleSha256": "33db9ab814e6ac9204a147006cbca845b7917b635d3f59efb9d9ac8a796c7626",
    "headerDistributionReproducibilityId": "bg.cpp.browser-header-distribution-reproducibility.sha256.786197fcadb7421405943fa87c3c647b06b98aeb116554aeb7cdb058a46b0252",
    "headerDistributionOutputVerificationId": "bg.cpp.distribution-output-file-verification.sha256.a7e52dd81789859e6c3f718f210793d5dd4a891a4b26a07a41a94683df2c49f7"
  },
  "deterministicOutputs": [
    {
      "outputPath": "assets/browsergrad-cpp-cute/asset-manifest.json",
      "role": "asset-manifest",
      "mediaType": "application/json",
      "sha256": "307a17722eb9892b29e63fd68f02368ef706f85271f29cdcd2d57c5634afe855",
      "byteLength": "11501"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/build-input-lock.json",
      "role": "build-input-lock",
      "mediaType": "application/json",
      "sha256": "b0021295d4b9295abc3d8ef90a84883f3deae430d97446e5166444d0d82f025d",
      "byteLength": "26662"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/clang-extractor.wasm",
      "role": "clang-extractor",
      "mediaType": "application/wasm",
      "sha256": "937ffe559aa5bd57db7eeecd26a590d90344457e6a6e0b06151afb6cfcc3fb6d",
      "byteLength": "31841971"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/clang-resource.headers.bgvfs",
      "role": "clang-resource-header-vfs",
      "mediaType": "application/octet-stream",
      "sha256": "037acb8aaae9a437ed8275ca608dd92c31a142aa8c882b7ac238e80b3343805e",
      "byteLength": "7704705"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/cpp-cute-browser-worker.mjs",
      "role": "browser-worker-module",
      "mediaType": "text/javascript",
      "sha256": "33db9ab814e6ac9204a147006cbca845b7917b635d3f59efb9d9ac8a796c7626",
      "byteLength": "584969"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/cuda-12.6.3.headers.bgvfs",
      "role": "cuda-header-vfs",
      "mediaType": "application/octet-stream",
      "sha256": "1917ba19e65d1e3be9dfe23b80c693ba8de5ce8e44538a7d16715cd61ece2cbd",
      "byteLength": "18954596"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/cutlass-3.7.0.headers.bgvfs",
      "role": "cutlass-header-vfs",
      "mediaType": "application/octet-stream",
      "sha256": "4f1c39b73f2fa7252628a253f7bb5b1411bdfdada872c5ff733b1b9008d89555",
      "byteLength": "21403975"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/diagnostic-normalization.json",
      "role": "diagnostic-normalization-manifest",
      "mediaType": "application/vnd.browsergrad.cpp-cute.diagnostic-normalization.v1+json",
      "sha256": "6de153792fb09711a9f71ee470433f58ce4183a09fe4e8eb987c9d9bf6a46997",
      "byteLength": "8799"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/libcxx-22.1.8.headers.bgvfs",
      "role": "libcxx-header-vfs",
      "mediaType": "application/octet-stream",
      "sha256": "1f2c5a1e86b04c29b6af33cc3fba0487b9bdcb87affaa44fceb32bec424e7dba",
      "byteLength": "12689654"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/license-inventory.json",
      "role": "license-inventory",
      "mediaType": "application/json",
      "sha256": "7a49e4b82bdc0cf38e0d27079650d112cae4df085b02fd4d416c907ff0308085",
      "byteLength": "1208403"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/linux-sysroot.headers.bgvfs",
      "role": "linux-sysroot-header-vfs",
      "mediaType": "application/octet-stream",
      "sha256": "d04a460dc605703b8e8a104cc5c043e6a7020ca7201991470c615273d43e7ae4",
      "byteLength": "8927070"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/runtime-abi-manifest.json",
      "role": "runtime-abi-manifest",
      "mediaType": "application/vnd.browsergrad.cpp-cute.runtime-abi-manifest.v1+json",
      "sha256": "551a4c727fcaa616780f50f20bf17cd96b4e49749da80a56be1768ac180a0160",
      "byteLength": "44507"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/semantic-adapter-manifest.json",
      "role": "semantic-adapter-manifest",
      "mediaType": "application/vnd.browsergrad.cpp-cute.semantic-adapter.v1+json",
      "sha256": "e5aa795c4feebd523ed72b95be03b102d497f2e0313ee9c99fadf1309cde6150",
      "byteLength": "2575"
    },
    {
      "outputPath": "assets/browsergrad-cpp-cute/THIRD_PARTY_NOTICES.txt",
      "role": "third-party-notices",
      "mediaType": "text/plain",
      "sha256": "5086675598ef771d8909ddb599786b4307534152af379463777b538546440472",
      "byteLength": "115330"
    },
    {
      "outputPath": "licenses/browsergrad-compiler.LICENSE",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "84996b33d49ed1a25655a12449c504089e2ac164f3f27a2c893711010bef1620",
      "byteLength": "1070"
    },
    {
      "outputPath": "licenses/clang.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "ebcd9bbf783a73d05c53ba4d586b8d5813dcdf3bbec50265860ccc885e606f47",
      "byteLength": "15140"
    },
    {
      "outputPath": "licenses/compiler-rt.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "1a8f1058753f1ba890de984e48f0242a3a5c29a6a8f2ed9fd813f36985387e8d",
      "byteLength": "16708"
    },
    {
      "outputPath": "licenses/cutlass.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "42fec630f410aa308f70a51a89fadcd19586fa620f9831a32bee528a9a10000e",
      "byteLength": "1547"
    },
    {
      "outputPath": "licenses/emscripten.LICENSE",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "620a78084fc7ca97c0b5dea9abf891f3ffcadfdbf305276f099c9c4e12fc1d86",
      "byteLength": "5093"
    },
    {
      "outputPath": "licenses/emscripten-musl.COPYRIGHT",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "b870108ec5e7790e9f9919064f1b9421d62d5f9b0e6c230c6adf7ea2da62e97b",
      "byteLength": "6196"
    },
    {
      "outputPath": "licenses/libcxx.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "539dd7aed86e8a4f12cbdd0e6c50c189c7d74847e4fecc64ce2c6ee3a01da38b",
      "byteLength": "16703"
    },
    {
      "outputPath": "licenses/libcxxabi.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "e2b35be49f7284a45b7baca8fc7b3ab7440e7902392b2528a457816b5bb2a15c",
      "byteLength": "16706"
    },
    {
      "outputPath": "licenses/libunwind.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "b5efebcaca80879234098e52d1725e6d9eb8fb96a19fce625d39184b705f7b6d",
      "byteLength": "16706"
    },
    {
      "outputPath": "licenses/llvm.LICENSE.txt",
      "role": "component-license",
      "mediaType": "text/plain",
      "sha256": "8d85c1057d742e597985c7d4e6320b015a9139385cff4cbae06ffc0ebe89afee",
      "byteLength": "15141"
    }
  ],
  "detachedEvidence": {
    "outputPath": "assets/browsergrad-cpp-cute/build-provenance.dsse.json",
    "role": "detached-build-provenance",
    "mediaType": "application/vnd.dsse.envelope.v1+json",
    "firstSha256": "aaf8d8a60f6a823baaba9693a244aad1071f3d2d20f26f0a5763bec7440f5041",
    "firstByteLength": "3035",
    "secondSha256": "aaf8d8a60f6a823baaba9693a244aad1071f3d2d20f26f0a5763bec7440f5041",
    "secondByteLength": "3035",
    "buildSubjectId": "bg.cpp.browser-build-subject.sha256.d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42",
    "buildSubjectSha256": "d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42"
  },
  "totals": {
    "outputCount": 25,
    "deterministicSubjectCount": 24,
    "detachedEvidenceCount": 1,
    "firstByteLength": "103638762",
    "secondByteLength": "103638762"
  },
  "claims": {
    "twoDistinctPrivateOutputRootsVerified": true,
    "exactBuildLockOutputPlanMatched": true,
    "exactOutputsRehashedInBothRoots": true,
    "deterministicSubjectsByteIdentical": true,
    "detachedEvidenceBuildSubjectMatched": true,
    "fullDistributedOutputSetReproducible": true,
    "detachedSignatureVerified": false,
    "externallyRootedProducerTrusted": false,
    "licenseReviewComplete": false,
    "distributionAuthorized": false,
    "workerExecutionObserved": false,
    "loweringAuthorityMinted": false,
    "backendExecutionObserved": false,
    "releaseReady": false
  }
} as const satisfies JsonObject;

export type CppCuteBrowserFullDistributionReproducibilityResourceV1 =
  typeof CPP_CUTE_BROWSER_FULL_DISTRIBUTION_REPRODUCIBILITY_V1_VALUE;

export const CPP_CUTE_BROWSER_FULL_DISTRIBUTION_REPRODUCIBILITY_V1_RESOURCE =
  deepFreezeJson(
    CPP_CUTE_BROWSER_FULL_DISTRIBUTION_REPRODUCIBILITY_V1_VALUE,
  ) as unknown as CppCuteBrowserFullDistributionReproducibilityResourceV1;
