import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

/**
 * Selected Gate-3 browser compiler build inputs.
 *
 * This resource is intentionally blocked for release. It fixes reviewed
 * upstream inputs and the build recipe without claiming that BrowserGrad
 * distributed header licenses, output bytes, or two clean builds exist. Those
 * facts require detached evidence produced by later authorities.
 */
const CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_VALUE = {
  schema: "browsergrad.compiler.cpp-cute.browser-build-input-lock",
  version: { major: 1, minor: 0 },
  lockId: "bg.cpp.browser-build-input-lock.sha256.c0c7ee66b05951ee3b977ccac0de68e5e417106d6c8894e1152771a4a775dbf3",
  body: {
    scope: {
      productPath: "browser-local-clang-wasm",
      authority: "build-input-selection-only",
      outputIdentity: "not-authorized",
      reproducibility: "detached-evidence-required",
      producerTrust: "detached-signed-attestation-required",
      dockerUse: "pinned-build-time-only",
      runtimeDocker: "forbidden",
      networkDuringBuild: "forbidden",
    },
    runtimeAbiResource: {
      outputPath: "assets/browsergrad-cpp-cute/runtime-abi-manifest.json",
      mediaType: "application/vnd.browsergrad.cpp-cute.runtime-abi-manifest.v1+json",
      runtimeAbiId: "browsergrad.compiler.cpp-cute.clang-wasm-runtime@1",
      manifestId: "bg.cpp.browser-runtime-abi.sha256.4e870314f139bd8af2f0e45a7410d8d3c6eaa2a8d358064bffd534ae7a91cb18",
      resourceSha256: "7b6c8891081d7a46c3064069aaf56b5e85635d72e17fe4d19bef021a922f68bc",
      resourceByteLength: "40578",
      byteIdentity: "must-equal-package-canonical-resource",
      authority: "design-reference-only-no-wasm-conformance-worker-or-release-authority",
    },
    sources: [
      {
        sourceId: "cutlass",
        repository: "https://github.com/NVIDIA/cutlass",
        acquisitionUrl: "https://github.com/NVIDIA/cutlass/archive/refs/tags/v3.7.0.tar.gz",
        tag: "v3.7.0",
        commit: "b78588d1630aa6643bf021613717bafb705df4ef",
        treeSha1: "4f4ae808cf284b8b0599d520a46e9fe364b87fa6",
        archiveSha256: "dfcafb7435a1b114ce32faee4f3257e276caf08f55fea04fa8bf3efa3a83c814",
        archiveByteLength: "29728321",
      },
      {
        sourceId: "llvm-project",
        repository: "https://github.com/llvm/llvm-project",
        acquisitionUrl:
          "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/llvm-project-22.1.8.src.tar.xz",
        tag: "llvmorg-22.1.8",
        commit: "ca7933e47d3a3451d81e72ac174dcb5aa28b59d1",
        treeSha1: "1e4fdb95266974a0cbca9ec4c6f740488322f238",
        archiveSha256: "922f1817a0df7b1489272d18134ee0087a8b068828f87ac63b9861b1a9965888",
        archiveByteLength: "167061596",
        attestationUrl:
          "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/llvm-project-22.1.8.src.tar.xz.jsonl",
        attestationSha256: "dd4aa06bd73706743090631300c02a6d8a3df43d41d85c627ec438d5a13b3739",
        attestationByteLength: "11234",
      },
    ],
    builder: {
      kind: "oci-image",
      repository: "docker.io/emscripten/emsdk",
      tag: "6.0.3",
      platform: "linux/amd64",
      imageIndexDigest: "sha256:bb0910e6a18bb9bd7cb31ae4ed40f9073148b78cb2cdb8ea8676454e0d85425c",
      platformManifestDigest: "sha256:2a7a41cd7e2065b30ba389c8db0fbeaebd7ec06bb4e20f23cab8ba92180f25c7",
      imageConfigDigest: "sha256:1998ba0793f0e61685f08c62a3e78bbcd1ef84895fefe994bf48d8d66dc1e495",
      emsdk: {
        repository: "https://github.com/emscripten-core/emsdk",
        tag: "6.0.3",
        commit: "db04e88298d9916fc51fcd3743045ca3eb695127",
        treeSha1: "dcd5379b6ad5fae277df240385eef415663556e5",
        releaseBundleCommit: "9074aa513b501925adb1361e208932ad32a29a5f",
        releaseBundleUrl:
          "https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/9074aa513b501925adb1361e208932ad32a29a5f/wasm-binaries.tar.xz",
        releaseBundleSha256: "3f32b91a3f8d405846ccacee911f9364da75f413fbd11ea1f3f7f23bf9d07cf3",
        releaseBundleByteLength: "292035244",
        emscriptenCommit: "283e2d130132859fde6a4e4c87fd254b38127651",
        llvmToolchainCommit: "592953beff733a1e28f6c6e5e39f948fb035a329",
        binaryenCommit: "1517ea948c09455502ba45ee3f26ea06fb2b7542",
      },
    },
    recipe: {
      recipeId: "browsergrad.compiler.cpp-cute.clang-wasm-build@1",
      sourceDateEpoch: "1781562833",
      environment: [
        { name: "LANG", value: "C" },
        { name: "LC_ALL", value: "C" },
        { name: "SOURCE_DATE_EPOCH", value: "1781562833" },
        { name: "TZ", value: "UTC" },
        { name: "ZERO_AR_DATE", value: "1" },
      ],
      parallelJobs: 4,
      prefixMapKinds: ["debug", "file", "macro"],
      stages: [
        {
          ordinal: 0,
          stageId: "native-tablegen",
          executionPlatform: "linux/amd64",
          cmakeGenerator: "Unix Makefiles",
          sourceSubdirectory: "llvm",
          buildDirectoryRole: "native-tablegen",
          definitions: [
            { name: "CLANG_ENABLE_STATIC_ANALYZER", value: "OFF" },
            { name: "CLANG_INCLUDE_DOCS", value: "OFF" },
            { name: "CLANG_INCLUDE_TESTS", value: "OFF" },
            { name: "CMAKE_BUILD_TYPE", value: "Release" },
            { name: "CMAKE_C_COMPILER", value: "@EMSDK@/upstream/bin/clang" },
            { name: "CMAKE_CXX_COMPILER", value: "@EMSDK@/upstream/bin/clang++" },
            { name: "CMAKE_FIND_USE_PACKAGE_REGISTRY", value: "OFF" },
            { name: "CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH", value: "OFF" },
            { name: "CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY", value: "OFF" },
            { name: "CMAKE_MAKE_PROGRAM", value: "/usr/bin/make" },
            { name: "LLVM_APPEND_VC_REV", value: "OFF" },
            { name: "LLVM_ENABLE_BINDINGS", value: "OFF" },
            { name: "LLVM_ENABLE_CURL", value: "OFF" },
            { name: "LLVM_ENABLE_EH", value: "OFF" },
            { name: "LLVM_ENABLE_FFI", value: "OFF" },
            { name: "LLVM_ENABLE_HTTPLIB", value: "OFF" },
            { name: "LLVM_ENABLE_LIBEDIT", value: "OFF" },
            { name: "LLVM_ENABLE_LIBXML2", value: "OFF" },
            { name: "LLVM_ENABLE_PROJECTS", value: "clang" },
            { name: "LLVM_ENABLE_RTTI", value: "OFF" },
            { name: "LLVM_ENABLE_Z3_SOLVER", value: "OFF" },
            { name: "LLVM_ENABLE_ZLIB", value: "OFF" },
            { name: "LLVM_ENABLE_ZSTD", value: "OFF" },
            { name: "LLVM_INCLUDE_BENCHMARKS", value: "OFF" },
            { name: "LLVM_INCLUDE_DOCS", value: "OFF" },
            { name: "LLVM_INCLUDE_EXAMPLES", value: "OFF" },
            { name: "LLVM_INCLUDE_TESTS", value: "OFF" },
            { name: "LLVM_TARGETS_TO_BUILD", value: "WebAssembly" },
            { name: "Python3_EXECUTABLE", value: "/usr/bin/python3" },
          ],
          compilerFlags: [
            "-O2",
            "-DNDEBUG",
            "-Werror=date-time",
            "@PREFIX_MAP_FLAGS@",
          ],
          targets: ["clang-tblgen", "llvm-tblgen"],
        },
        {
          ordinal: 1,
          stageId: "clang-extractor-wasm",
          executionPlatform: "wasm32-unknown-emscripten",
          cmakeGenerator: "Unix Makefiles",
          sourceSubdirectory: "llvm",
          buildDirectoryRole: "clang-extractor-wasm",
          definitions: [
            {
              name: "BROWSERGRAD_EXTRACTOR_FACTORY_OUTPUT_PATH",
              value: "@BUILD_EVIDENCE@/generated/clang-extractor.mjs",
            },
            { name: "BUILD_SHARED_LIBS", value: "OFF" },
            { name: "CLANG_BUILD_TOOLS", value: "OFF" },
            { name: "CLANG_ENABLE_HLSL", value: "OFF" },
            { name: "CLANG_ENABLE_OBJC_REWRITER", value: "OFF" },
            { name: "CLANG_ENABLE_STATIC_ANALYZER", value: "OFF" },
            { name: "CLANG_INCLUDE_DOCS", value: "OFF" },
            { name: "CLANG_INCLUDE_TESTS", value: "OFF" },
            { name: "CLANG_TABLEGEN", value: "@NATIVE_BUILD@/bin/clang-tblgen" },
            { name: "CMAKE_BUILD_TYPE", value: "Release" },
            { name: "CMAKE_FIND_USE_PACKAGE_REGISTRY", value: "OFF" },
            { name: "CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH", value: "OFF" },
            { name: "CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY", value: "OFF" },
            { name: "CMAKE_INSTALL_PREFIX", value: "/opt/browsergrad-clang" },
            { name: "CMAKE_MAKE_PROGRAM", value: "/usr/bin/make" },
            { name: "CMAKE_TRY_COMPILE_TARGET_TYPE", value: "STATIC_LIBRARY" },
            { name: "LLVM_APPEND_VC_REV", value: "OFF" },
            { name: "LLVM_BUILD_LLVM_DYLIB", value: "OFF" },
            { name: "LLVM_BUILD_TOOLS", value: "OFF" },
            { name: "LLVM_ENABLE_BACKTRACES", value: "OFF" },
            { name: "LLVM_ENABLE_BINDINGS", value: "OFF" },
            { name: "LLVM_ENABLE_CRASH_OVERRIDES", value: "OFF" },
            { name: "LLVM_ENABLE_CURL", value: "OFF" },
            { name: "LLVM_ENABLE_EH", value: "OFF" },
            { name: "LLVM_ENABLE_FFI", value: "OFF" },
            { name: "LLVM_ENABLE_HTTPLIB", value: "OFF" },
            { name: "LLVM_ENABLE_LIBEDIT", value: "OFF" },
            { name: "LLVM_ENABLE_LIBXML2", value: "OFF" },
            { name: "LLVM_ENABLE_LTO", value: "OFF" },
            { name: "LLVM_ENABLE_PIC", value: "OFF" },
            { name: "LLVM_ENABLE_PLUGINS", value: "OFF" },
            { name: "LLVM_ENABLE_PROJECTS", value: "clang" },
            { name: "LLVM_ENABLE_RTTI", value: "ON" },
            { name: "LLVM_ENABLE_THREADS", value: "OFF" },
            { name: "LLVM_ENABLE_UNWIND_TABLES", value: "OFF" },
            { name: "LLVM_ENABLE_Z3_SOLVER", value: "OFF" },
            { name: "LLVM_ENABLE_ZLIB", value: "OFF" },
            { name: "LLVM_ENABLE_ZSTD", value: "OFF" },
            { name: "LLVM_EXTERNAL_BROWSERGRAD_EXTRACTOR_SOURCE_DIR", value: "@EXTRACTOR_SOURCE@" },
            { name: "LLVM_EXTERNAL_PROJECTS", value: "browsergrad_extractor" },
            { name: "LLVM_INCLUDE_BENCHMARKS", value: "OFF" },
            { name: "LLVM_INCLUDE_DOCS", value: "OFF" },
            { name: "LLVM_INCLUDE_EXAMPLES", value: "OFF" },
            { name: "LLVM_INCLUDE_TESTS", value: "OFF" },
            { name: "LLVM_LINK_LLVM_DYLIB", value: "OFF" },
            { name: "LLVM_NATIVE_TOOL_DIR", value: "@NATIVE_BUILD@/bin" },
            { name: "LLVM_TABLEGEN", value: "@NATIVE_BUILD@/bin/llvm-tblgen" },
            { name: "LLVM_TARGETS_TO_BUILD", value: "WebAssembly" },
            { name: "Python3_EXECUTABLE", value: "/usr/bin/python3" },
          ],
          compilerFlags: [
            "-O3",
            "-DNDEBUG",
            "-fexceptions",
            "-Werror=date-time",
            "@PREFIX_MAP_FLAGS@",
          ],
          linkerFlags: [
            "-O2",
            "-fexceptions",
            "-mno-simd128",
            "-mno-atomics",
            "-mbulk-memory",
            "-mnontrapping-fptoint",
            "--no-entry",
            "-sSTRICT=1",
            "-sMODULARIZE=1",
            "-sEXPORT_ES6=1",
            "-sEXPORT_NAME=createBrowserGradCppCuteExtractor",
            "-sENVIRONMENT=worker",
            "-sFILESYSTEM=0",
            "-sDYNAMIC_EXECUTION=0",
            "-sINVOKE_RUN=0",
            "-sEXIT_RUNTIME=0",
            "-sASSERTIONS=0",
            "-sSTACK_OVERFLOW_CHECK=2",
            "-sALLOW_MEMORY_GROWTH=1",
            "-sINITIAL_MEMORY=268435456",
            "-sMAXIMUM_MEMORY=1073741824",
            "-sMEMORY_GROWTH_LINEAR_STEP=67108864",
            "-sSTACK_SIZE=16777216",
            "-sABORTING_MALLOC=0",
            "-sMALLOC=dlmalloc",
            "-sERROR_ON_UNDEFINED_SYMBOLS=0",
            "-Wl,--error-limit=0",
            "-sWASM_ASYNC_COMPILATION=1",
            "-sRETAIN_COMPILER_SETTINGS=0",
            "-sEMIT_PRODUCERS_SECTION=0",
            "-sINCOMING_MODULE_JS_API=['instantiateWasm','onAbort','print','printErr']",
            "-sEXPORTED_RUNTIME_METHODS=[]",
            "-sEXPORTED_FUNCTIONS=['_bg_cpp_cute_abi_version','_bg_cpp_cute_alloc','_bg_cpp_cute_allocator_metrics_pointer','_bg_cpp_cute_frontend_work_metrics_pointer','_bg_cpp_cute_compile','_bg_cpp_cute_free','_bg_cpp_cute_reset','_bg_cpp_cute_result_length','_bg_cpp_cute_result_pointer','_bg_cpp_cute_status']",
            "-Wl,--Map=@BUILD_EVIDENCE@/clang-extractor.link.map",
          ],
          targets: ["browsergrad-cpp-cute-extractor"],
        },
      ],
      extractorSource: {
        sourceSetSha256: "20d7b765b5fbd8d0b50897d09f4317502a2db34f99ecb434b409bc9e1cc9b674",
        hashDomain: "browsergrad.compiler.cpp-cute.browser-extractor-source-set.v1",
        files: [
          {
            path: "BrowserGradCppCuteArtifactV3.cpp",
            sha256: "e3635d67f45dfc2003d8a9ad6998b1ef6d3a2f77bf913babc3d9b1e7de167805",
            byteLength: "7164",
          },
          {
            path: "BrowserGradCppCuteArtifactV3.h",
            sha256: "7ea2d62eceb900255c8d26a787ebe2cae19a151c2d12c44f09acaa1f1cfbbb18",
            byteLength: "276",
          },
          {
            path: "BrowserGradCppCuteArtifactWriter.cpp",
            sha256: "40ad8b05eb78744fe2f56198c98447d2deaafce22e1c71ae163a6c4c0ed3b759",
            byteLength: "73255",
          },
          {
            path: "BrowserGradCppCuteArtifactWriter.h",
            sha256: "e627b9c21683918699a073b20100d126a244971331bd7e85693ad45d1712543e",
            byteLength: "918",
          },
          {
            path: "BrowserGradCppCuteBrowserHost.cpp",
            sha256: "05a7b026165501c53814df3bc01c9d59a64a37a7f09f96c6c78334f98428b2bc",
            byteLength: "8817",
          },
          {
            path: "BrowserGradCppCuteBrowserSyscalls.inc",
            sha256: "6c54005d64343bc59e1135d2c608ec36a95f2c3c69f58c0968bc44e020d17389",
            byteLength: "1293",
          },
          {
            path: "BrowserGradCppCuteCanonicalJson.cpp",
            sha256: "c21267a8f1f8ea679f4593107bf5f082173aa3863ee94a9d72a1d0154994599f",
            byteLength: "13509",
          },
          {
            path: "BrowserGradCppCuteCanonicalJson.h",
            sha256: "93319b3733557de68dc2d2d858e52943f45a9da3998540ce5b63542d83810e7a",
            byteLength: "1887",
          },
          {
            path: "BrowserGradCppCuteClangAction.cpp",
            sha256: "3a6a4bfdfbcf869740802285fba022b8d2354540d7ecb5c469830a98a3c0e9eb",
            byteLength: "28880",
          },
          {
            path: "BrowserGradCppCuteClangAction.h",
            sha256: "cfb76724aaede4fa65f01c00ae325f291c41e7fe2aa8561c0b55d17a034b9480",
            byteLength: "2851",
          },
          {
            path: "BrowserGradCppCuteCommandLine.cpp",
            sha256: "9cc43a3a8ff04bc9cc05795e80225a8fc5d53a369531ff2832074c7163898720",
            byteLength: "7909",
          },
          {
            path: "BrowserGradCppCuteCommandLine.h",
            sha256: "3ab99816245e4434db9a19a993f7b3420cd8853d6c31b03e33f43e432533a3e0",
            byteLength: "1937",
          },
          {
            path: "BrowserGradCppCuteCommandLinePolicy.inc",
            sha256: "759f4cfa94f39a3baf316f24b446ec19bb2f89c32b73fa39ea6d780d00dafdda",
            byteLength: "2487",
          },
          {
            path: "BrowserGradCppCuteCompilePlan.cpp",
            sha256: "12ae711ccf4f9c800184f5876374b7369e35dcb09c31e27de54adea99713b317",
            byteLength: "9303",
          },
          {
            path: "BrowserGradCppCuteCompilePlan.h",
            sha256: "a7fc0e50982180c38177f51284462056d98a2932c636d662d876879d323ba97b",
            byteLength: "2636",
          },
          {
            path: "BrowserGradCppCuteCompileSession.cpp",
            sha256: "6fabb8bb810bad7ff42b965d91f7d5bd874ede7a6be214b6c7b3b37d23681cf3",
            byteLength: "95830",
          },
          {
            path: "BrowserGradCppCuteCompileSession.h",
            sha256: "8734b25b9f728d3142765e3aaf1e20c32bb0d655def0bc98e7567b06608b95b8",
            byteLength: "5618",
          },
          {
            path: "BrowserGradCppCuteDiagnostics.cpp",
            sha256: "0939fb48ebabd2a0f92b0f92954d349b028337dbc4562648c0bbfdfe222f7c20",
            byteLength: "29756",
          },
          {
            path: "BrowserGradCppCuteDiagnostics.h",
            sha256: "80c34ee9e730b4903dd11edb381feb2a97d7b5177612427c23e7e0d851ebbb4c",
            byteLength: "5269",
          },
          {
            path: "BrowserGradCppCuteDiagnosticsPolicy.inc",
            sha256: "1b673140d645c39d8af5a6473f16b07eaa044d6926c1f02a54be3fb49219bbce",
            byteLength: "4163",
          },
          {
            path: "BrowserGradCppCuteExtractor.cpp",
            sha256: "e867f2953b1e51b6c4eb1e9e15bf91687350241a30fd82b8c00bb410b9e313d1",
            byteLength: "1841",
          },
          {
            path: "BrowserGradCppCuteImportedVfs.cpp",
            sha256: "f5568cb7f25b19d420fe4dcaf5327c1b58734ba93948ad5b5dd44bbc0a16f15a",
            byteLength: "24208",
          },
          {
            path: "BrowserGradCppCuteImportedVfs.h",
            sha256: "1a35fb3c10674276e13b3c64eba8a4ba503593481659911276db091391bbd3a1",
            byteLength: "11959",
          },
          {
            path: "BrowserGradCppCuteInvocation.cpp",
            sha256: "11eb1e875e3e8fef012f5bc9df7c5b6e4d8edf685f9cfbdc07a330cd01211b92",
            byteLength: "21487",
          },
          {
            path: "BrowserGradCppCuteInvocation.h",
            sha256: "b93d317c27694bc68787a7adfa1c6fe75e679bcc400517b67a7d838e439f7cfc",
            byteLength: "5328",
          },
          {
            path: "BrowserGradCppCuteMetrics.cpp",
            sha256: "55036dce1d11ef8189bcac87a196fbe3d21b6edbe02c9c4df82f15b23b0c80f1",
            byteLength: "32905",
          },
          {
            path: "BrowserGradCppCuteMetrics.h",
            sha256: "474d432b6c3cc5e436506e22efc7daf8a2f7d82f00d6dd663abf1a8b7ef62ee2",
            byteLength: "7036",
          },
          {
            path: "BrowserGradCppCutePreprocessorPolicy.cpp",
            sha256: "4d9bce76cd4f2240068a3fae328ba43a21f9a66a51981073dad813d8e2ae4d74",
            byteLength: "6449",
          },
          {
            path: "BrowserGradCppCutePreprocessorPolicy.h",
            sha256: "c9e3d1c8e0ed963f783e22da0da98a9b6bb812f6c4a97748174089aec9aaa43e",
            byteLength: "4919",
          },
          {
            path: "BrowserGradCppCuteProducer.cpp",
            sha256: "6624a0466c3fca1b03cf3c88db311fdc4163bebfc61106011c6d62e68896a923",
            byteLength: "11370",
          },
          {
            path: "BrowserGradCppCuteProducer.h",
            sha256: "f6b5ffa781357b8263fdbd29427746a50c2e1261b224b7d2fe79f9376bbc6a9b",
            byteLength: "3256",
          },
          {
            path: "BrowserGradCppCuteRuntime.cpp",
            sha256: "44d7d823a205c1497f53a2da4d97e203702e8ffa7ffc856dad6bb714ca5e4ec8",
            byteLength: "26921",
          },
          {
            path: "BrowserGradCppCuteRuntime.h",
            sha256: "09c2c38c2d7021279dd0f872f1b2b17499e87e2dfa8b1f406c772b6f78e077ea",
            byteLength: "6324",
          },
          {
            path: "BrowserGradCppCuteSha256.cpp",
            sha256: "c2cee126cfa5cba1b7c7e9c2f097ff9775320469d3a279da2914b9b84ffe3aa1",
            byteLength: "7243",
          },
          {
            path: "BrowserGradCppCuteSha256.h",
            sha256: "145a43d9fd95ff60920d38c14985fc29a491eb686007642efbc75a97ad834b94",
            byteLength: "1861",
          },
          {
            path: "BrowserGradCppCuteVirtualPath.cpp",
            sha256: "e264f831cae50136646c1c0e9de3823ef2451cabcc9da47dfb810fb739ac197d",
            byteLength: "2925",
          },
          {
            path: "BrowserGradCppCuteVirtualPath.h",
            sha256: "724af0ee95fa2f1f950424f75e184758467b13b2b4a471689b3c61af3ae49442",
            byteLength: "561",
          },
          {
            path: "CMakeLists.txt",
            sha256: "d8d5b783d7532f17d7c7efac00dcba3ebba2d06b6c9e34b8f4893bf0ff22c90b",
            byteLength: "8933",
          },
        ],
      },
      extractorLinkPolicy: {
        selectedClangLibraries: [
          "clangAST",
          "clangBasic",
          "clangDriver",
          "clangFrontend",
          "clangIndex",
          "clangLex",
          "clangParse",
          "clangSema",
          "clangSerialization",
          "clangTooling",
        ],
        clangDriverUse: "in-process-tooling-dependency-only",
        driverSubprocesses: "forbidden",
        transitiveDependencies: "only-cmake-declared-static-dependencies-at-pinned-llvm-source",
        linkMapObjectClosure: "detached-evidence-required",
        allocatorInterceptionPolicy: {
          exactEntrypoints: [
            "aligned_alloc",
            "calloc",
            "free",
            "__libc_calloc",
            "__libc_free",
            "__libc_malloc",
            "__libc_realloc",
            "malloc",
            "memalign",
            "posix_memalign",
            "pvalloc",
            "realloc",
            "reallocarray",
            "valloc",
          ],
          forbiddenEntrypoints: [
            "bulk_free",
            "independent_calloc",
            "independent_comalloc",
            "realloc_in_place",
          ],
          directBypassReferences:
            "forbidden-outside-BrowserGradCppCuteMetrics.cpp",
          observedCallGraph: "detached-evidence-required",
        },
        prohibitedComponents: [
          "clangCodeGen",
          "clangInterpreter",
          "CUDA driver/runtime",
          "LLD",
          "LLVMExecutionEngine",
          "LLVMJITLink",
          "LLVMNVPTXCodeGen",
          "LLVMWebAssemblyCodeGen",
          "PTX assembler",
          "user-produced WASM",
        ],
      },
      distributedOutputPlan: {
        closure: "exact-path-set-no-additional-distributed-files",
        outputs: [
          {
            path: "assets/browsergrad-cpp-cute/asset-manifest.json",
            role: "asset-manifest",
            mediaType: "application/json",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/build-input-lock.json",
            role: "build-input-lock",
            mediaType: "application/json",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/build-provenance.dsse.json",
            role: "detached-build-provenance",
            mediaType: "application/vnd.dsse.envelope.v1+json",
            reproducibilityClass: "detached-evidence",
          },
          {
            path: "assets/browsergrad-cpp-cute/clang-extractor.wasm",
            role: "clang-extractor",
            mediaType: "application/wasm",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/clang-resource.headers.bgvfs",
            role: "clang-resource-header-vfs",
            mediaType: "application/octet-stream",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/cpp-cute-browser-worker.mjs",
            role: "browser-worker-module",
            mediaType: "text/javascript",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/cuda-12.6.3.headers.bgvfs",
            role: "cuda-header-vfs",
            mediaType: "application/octet-stream",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/cutlass-3.7.0.headers.bgvfs",
            role: "cutlass-header-vfs",
            mediaType: "application/octet-stream",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/libcxx-22.1.8.headers.bgvfs",
            role: "libcxx-header-vfs",
            mediaType: "application/octet-stream",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/license-inventory.json",
            role: "license-inventory",
            mediaType: "application/json",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/linux-sysroot.headers.bgvfs",
            role: "linux-sysroot-header-vfs",
            mediaType: "application/octet-stream",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/runtime-abi-manifest.json",
            role: "runtime-abi-manifest",
            mediaType: "application/vnd.browsergrad.cpp-cute.runtime-abi-manifest.v1+json",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/semantic-adapter-manifest.json",
            role: "semantic-adapter-manifest",
            mediaType: "application/json",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "assets/browsergrad-cpp-cute/THIRD_PARTY_NOTICES.txt",
            role: "third-party-notices",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/browsergrad-compiler.LICENSE",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/clang.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/compiler-rt.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/cutlass.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/emscripten.LICENSE",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/emscripten-musl.COPYRIGHT",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/libcxx.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/libcxxabi.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/libunwind.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
          {
            path: "licenses/llvm.LICENSE.txt",
            role: "component-license",
            mediaType: "text/plain",
            reproducibilityClass: "deterministic-subject",
          },
        ],
      },
      reproducibility: {
        cleanBuildCount: 2,
        sourceAndBuildPaths: "distinct",
        comparison: "per-output-reproducibility-class",
        deterministicSubjects: "sha256-byte-for-byte-across-clean-builds",
        detachedEvidence: "envelope-bytes-may-differ-subject-sha256-must-match",
        nativeTablegenIdentity: "record-and-compare-sha256",
        buildLogs: "canonical-command-and-environment-records-required",
        attestation: "externally-signed-detached-required",
      },
    },
    notices: {
      fileInventoryPolicy: "exact-distributed-file-to-notice-map-required",
      approvedComponents: [
        {
          componentId: "browsergrad-compiler",
          licenseExpression: "MIT",
          sourcePath: "packages/browsergrad-compiler/LICENSE",
          noticeOutputPath: "licenses/browsergrad-compiler.LICENSE",
          noticeSha256: "84996b33d49ed1a25655a12449c504089e2ac164f3f27a2c893711010bef1620",
          noticeByteLength: "1070",
          appliesTo: ["clang-extractor-wasm", "semantic-adapter-manifest", "worker-module"],
        },
        {
          componentId: "clang",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "clang/LICENSE.TXT",
          noticeOutputPath: "licenses/clang.LICENSE.txt",
          noticeSha256: "ebcd9bbf783a73d05c53ba4d586b8d5813dcdf3bbec50265860ccc885e606f47",
          noticeByteLength: "15140",
          appliesTo: ["clang-extractor-wasm", "compiler-resource-pack"],
        },
        {
          componentId: "compiler-rt",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "compiler-rt/LICENSE.TXT",
          noticeOutputPath: "licenses/compiler-rt.LICENSE.txt",
          noticeSha256: "1a8f1058753f1ba890de984e48f0242a3a5c29a6a8f2ed9fd813f36985387e8d",
          noticeByteLength: "16708",
          appliesTo: ["clang-extractor-wasm"],
        },
        {
          componentId: "cutlass",
          licenseExpression: "BSD-3-Clause",
          sourcePath: "LICENSE.txt",
          noticeOutputPath: "licenses/cutlass.LICENSE.txt",
          noticeSha256: "42fec630f410aa308f70a51a89fadcd19586fa620f9831a32bee528a9a10000e",
          noticeByteLength: "1547",
          appliesTo: ["dependency-header-pack:cutlass"],
        },
        {
          componentId: "emscripten",
          licenseExpression: "MIT OR NCSA",
          sourcePath: "LICENSE",
          noticeOutputPath: "licenses/emscripten.LICENSE",
          noticeSha256: "620a78084fc7ca97c0b5dea9abf891f3ffcadfdbf305276f099c9c4e12fc1d86",
          noticeByteLength: "5093",
          appliesTo: ["clang-extractor-wasm", "worker-module"],
        },
        {
          componentId: "emscripten-musl",
          licenseExpression: "MIT",
          sourcePath: "system/lib/libc/musl/COPYRIGHT",
          noticeOutputPath: "licenses/emscripten-musl.COPYRIGHT",
          noticeSha256: "b870108ec5e7790e9f9919064f1b9421d62d5f9b0e6c230c6adf7ea2da62e97b",
          noticeByteLength: "6196",
          appliesTo: ["clang-extractor-wasm"],
        },
        {
          componentId: "libcxx",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "libcxx/LICENSE.TXT",
          noticeOutputPath: "licenses/libcxx.LICENSE.txt",
          noticeSha256: "539dd7aed86e8a4f12cbdd0e6c50c189c7d74847e4fecc64ce2c6ee3a01da38b",
          noticeByteLength: "16703",
          appliesTo: ["clang-extractor-wasm", "dependency-header-pack:cxx-stdlib"],
        },
        {
          componentId: "libcxxabi",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "libcxxabi/LICENSE.TXT",
          noticeOutputPath: "licenses/libcxxabi.LICENSE.txt",
          noticeSha256: "e2b35be49f7284a45b7baca8fc7b3ab7440e7902392b2528a457816b5bb2a15c",
          noticeByteLength: "16706",
          appliesTo: ["clang-extractor-wasm"],
        },
        {
          componentId: "libunwind",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "libunwind/LICENSE.TXT",
          noticeOutputPath: "licenses/libunwind.LICENSE.txt",
          noticeSha256: "b5efebcaca80879234098e52d1725e6d9eb8fb96a19fce625d39184b705f7b6d",
          noticeByteLength: "16706",
          appliesTo: ["clang-extractor-wasm"],
        },
        {
          componentId: "llvm",
          licenseExpression: "Apache-2.0 WITH LLVM-exception",
          sourcePath: "LICENSE.TXT",
          noticeOutputPath: "licenses/llvm.LICENSE.txt",
          noticeSha256: "8d85c1057d742e597985c7d4e6320b015a9139385cff4cbae06ffc0ebe89afee",
          noticeByteLength: "15141",
          appliesTo: ["clang-extractor-wasm"],
        },
      ],
      unresolvedComponents: [
        {
          componentId: "cuda-toolkit-12.6.3-headers",
          intendedAsset: "dependency-header-pack:cuda",
          reasonCode: "exact-file-redistribution-review-required",
          disposition: "blocks-release",
        },
        {
          componentId: "linux-sysroot",
          intendedAsset: "dependency-header-pack:linux-sysroot",
          reasonCode: "source-package-license-and-redistribution-closure-required",
          disposition: "blocks-release",
        },
      ],
    },
    unresolvedBuildInputs: [
      {
        blockerId: "browsergrad-extractor-distributed-materialization",
        requirement: "deterministic-hash-verified-copy-of-generated-wasm-sidecar-into-declared-distributed-output",
      },
      {
        blockerId: "browsergrad-extractor-runtime-metrics-export",
        requirement:
          "runtime-abi-1.1-metrics-source-exists-but-pinned-executed-wasm-interception-zero-size-reallocation-and-call-graph-conformance-remain-unproved",
      },
      {
        blockerId: "browsergrad-worker-emscripten-factory-bundle",
        requirement: "deterministic-package-owned-worker-bundle-of-exact-generated-factory-with-host-supplied-wasm-instantiation",
      },
    ],
    releasePolicy: {
      decision: "blocked",
      blockerIds: [
        "browsergrad-extractor-distributed-materialization",
        "browsergrad-extractor-runtime-metrics-export",
        "browsergrad-worker-emscripten-factory-bundle",
        "cuda-header-redistribution",
        "distributed-file-license-manifest",
        "linux-sysroot-redistribution",
        "observed-wasm-interface-evidence",
        "reproducible-build-evidence",
      ],
      requiredExternalAuthorities: [
        "canonical-runtime-abi-manifest",
      ],
      requiredDetachedEvidence: [
        "exact-distributed-file-license-map",
        "externally-signed-build-attestation",
        "observed-wasm-import-export-feature-and-memory-projection",
        "two-clean-distinct-path-builds-with-identical-assets",
      ],
    },
  },
} as const satisfies JsonObject;

export type CppCuteBrowserBuildInputLockV1Resource =
  typeof CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_VALUE;

export const CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_RESOURCE = deepFreezeJson(
  CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_VALUE,
) as unknown as CppCuteBrowserBuildInputLockV1Resource;
