import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

/** Generated by cpp_cute_browser_reproducibility_authoring.mjs. */
const CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_VALUE = {
  "authority": "clang-wasm-extractor-reproducibility-observation-only",
  "builds": [
    {
      "buildExecutionEvidenceByteLength": 33928,
      "buildExecutionEvidenceSha256": "0bb9ea06bdad3e3f5b706b705e437719a885585c2285b6304761ddb50885e2f3",
      "factoryModuleByteLength": 27884,
      "factoryModuleSha256": "2eaa4ce31951cd5eff989679fd8d63c4ae74df0293f8f727209a3ce0f681764d",
      "linkMapByteLength": 24635634,
      "linkMapCanonicalByteLength": 24586698,
      "linkMapCanonicalSha256": "b112d2fab24efe8111431f5c201a42abeab57af9115ab32fbafa713a1038ba8d",
      "linkMapSha256": "25c87db141afced172f1fee7c0b3fa58173b4bd48ca36a39cf68b0d1888783a9",
      "nativeTools": {
        "clangTablegenByteLength": 2571848,
        "clangTablegenSha256": "aeb5987e0f3523b62f423ccc7f2bf281e990a944f21e405b175eca1b05b80a0b",
        "llvmTablegenByteLength": 5057944,
        "llvmTablegenSha256": "b13c84826686062917c3fbb5bb7165c7a5512c7c35eae4128d07b960f8fba163"
      },
      "ordinal": 1,
      "runtimeAbiReviewByteLength": 1681594,
      "runtimeAbiReviewExactInterfaceConformance": true,
      "runtimeAbiReviewSha256": "099616d8d086adb9c998767cbfaff1305f256a9176b3c5a30572d9311888a80e",
      "runtimeClosureObservationByteLength": 16990,
      "runtimeClosureObservationSha256": "9d51a6bde1e1751a2a14829e0ad82b694824b851399d5018f8d743614c874732",
      "runtimeClosureSha256": "5f2d8b17e5db253c27a0b4a15a70553f980a4ddb20df90b225b8df67523d3018",
      "wasmByteLength": 31841971,
      "wasmSha256": "937ffe559aa5bd57db7eeecd26a590d90344457e6a6e0b06151afb6cfcc3fb6d"
    },
    {
      "buildExecutionEvidenceByteLength": 33928,
      "buildExecutionEvidenceSha256": "c59d05e0f4001c5a64ea3555d5e39fa9422da204a2b71906f9fb4cff59c8964e",
      "factoryModuleByteLength": 27884,
      "factoryModuleSha256": "2eaa4ce31951cd5eff989679fd8d63c4ae74df0293f8f727209a3ce0f681764d",
      "linkMapByteLength": 24635634,
      "linkMapCanonicalByteLength": 24586698,
      "linkMapCanonicalSha256": "b112d2fab24efe8111431f5c201a42abeab57af9115ab32fbafa713a1038ba8d",
      "linkMapSha256": "27647d21bcedddbb7c9ee4fae19612808a02cf897dee8a1eef3112be124b7d5c",
      "nativeTools": {
        "clangTablegenByteLength": 2571848,
        "clangTablegenSha256": "aeb5987e0f3523b62f423ccc7f2bf281e990a944f21e405b175eca1b05b80a0b",
        "llvmTablegenByteLength": 5057944,
        "llvmTablegenSha256": "b13c84826686062917c3fbb5bb7165c7a5512c7c35eae4128d07b960f8fba163"
      },
      "ordinal": 2,
      "runtimeAbiReviewByteLength": 1681594,
      "runtimeAbiReviewExactInterfaceConformance": true,
      "runtimeAbiReviewSha256": "099616d8d086adb9c998767cbfaff1305f256a9176b3c5a30572d9311888a80e",
      "runtimeClosureObservationByteLength": 16990,
      "runtimeClosureObservationSha256": "9d51a6bde1e1751a2a14829e0ad82b694824b851399d5018f8d743614c874732",
      "runtimeClosureSha256": "5f2d8b17e5db253c27a0b4a15a70553f980a4ddb20df90b225b8df67523d3018",
      "wasmByteLength": 31841971,
      "wasmSha256": "937ffe559aa5bd57db7eeecd26a590d90344457e6a6e0b06151afb6cfcc3fb6d"
    }
  ],
  "claims": {
    "abiConformanceVerified": false,
    "extractorOutputsReproducible": true,
    "fullDistributedOutputSetReproducible": false,
    "outputIdentityAuthorized": false,
    "producerAttested": false,
    "releaseReady": false
  },
  "cleanBuildCount": 2,
  "comparison": {
    "canonicalCommandsAndEnvironmentMatched": true,
    "factoryModuleBytesMatched": true,
    "linkMapCanonicalProjectionMatched": true,
    "nativeTablegenIdentitiesMatched": true,
    "runtimeAbiReviewBytesMatched": true,
    "runtimeClosureMatched": true,
    "sourceAndBuildPathsDistinct": true,
    "wasmBytesMatched": true
  },
  "lockId": "bg.cpp.browser-build-input-lock.sha256.08ddf15cbd0e5600fd1ae9f935cc7e3552e0140b665138ccdcf6d0f837bcdc34",
  "schema": "browsergrad.compiler.cpp-cute.clang-wasm-reproducibility",
  "sourceSetSha256": "120cf4948cb27938c98836315e01375ba23f5ef7c8c3d037fb47d0d0d0601bee",
  "version": 3
} as const satisfies JsonObject;

export type CppCuteBrowserReproducibilityV3Resource =
  typeof CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_VALUE;

export const CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_RESOURCE = deepFreezeJson(
  CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_VALUE,
) as unknown as CppCuteBrowserReproducibilityV3Resource;
