import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

/**
 * Producer-neutral policy for converting exact Clang 22.1.8 diagnostics into
 * the frontend Artifact V3 vocabulary. Loading this resource does not prove
 * that a native or Wasm producer installed or applied the policy.
 */
const CPP_CUTE_DIAGNOSTIC_NORMALIZATION_V1_VALUE = {
  schema: "browsergrad.compiler.cpp-cute.diagnostic-normalization",
  version: { major: 1, minor: 0 },
  manifestId: "bg.cpp.diagnostic-normalization.sha256.21d60795bc3da39c9003316f0e6c489c98f7db94cf24a0707bc0fae94001a10a",
  body: {
    policyId: "browsergrad.compiler.cpp-cute.clang-diagnostic-normalization@1",
    clang: {
      compilerId: "clang",
      version: "22.1.8",
    },
    artifactBinding: {
      schema: "browsergrad.compiler.cpp-cute.frontend-artifact",
      major: 3,
      diagnosticShape: "browsergrad.compiler.cpp-cute.frontend-diagnostic@3",
      fixItsRepresented: false,
    },
    classification: {
      rawDiagnosticIdRange: { minimum: 0, maximum: 4_294_967_295 },
      rawDiagnosticIdEncoding: "unsigned-decimal-no-leading-zeroes",
      clangDiagnosticCodeFormat: "clang:diag-<raw-diagnostic-id>",
      categorySource: "producer-stage-default-with-closed-custom-overrides",
      producerStageSource: "active-frontend-callback-boundary",
      messageInference: "forbidden",
      diagnosticGroupInference: "forbidden",
    },
    stageMappings: [
      { producerStage: "preprocessor", artifactPhase: "preprocessing" },
      { producerStage: "parser", artifactPhase: "parsing" },
      { producerStage: "sema-name-lookup", artifactPhase: "name-lookup" },
      { producerStage: "sema-overload-resolution", artifactPhase: "overload-resolution" },
      { producerStage: "sema-template-instantiation", artifactPhase: "template-instantiation" },
      { producerStage: "sema-cuda", artifactPhase: "cuda-sema" },
      { producerStage: "artifact-extractor", artifactPhase: "artifact-extraction" },
    ],
    severityMappings: [
      {
        clangLevel: "ignored",
        disposition: "omit-before-normalization",
        artifactSeverity: null,
        blocking: false,
        parentRequired: false,
      },
      {
        clangLevel: "remark",
        disposition: "emit",
        artifactSeverity: "remark",
        blocking: false,
        parentRequired: false,
      },
      {
        clangLevel: "note",
        disposition: "emit",
        artifactSeverity: "note",
        blocking: false,
        parentRequired: true,
      },
      {
        clangLevel: "warning",
        disposition: "emit",
        artifactSeverity: "warning",
        blocking: false,
        parentRequired: false,
      },
      {
        clangLevel: "error",
        disposition: "emit",
        artifactSeverity: "error",
        blocking: true,
        parentRequired: false,
      },
      {
        clangLevel: "fatal",
        disposition: "emit",
        artifactSeverity: "fatal",
        blocking: true,
        parentRequired: false,
      },
    ],
    categoryMappings: [
      {
        category: "preprocessing",
        permittedProducerStages: ["preprocessor"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "parsing",
        permittedProducerStages: ["parser"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "name-lookup",
        permittedProducerStages: ["sema-name-lookup"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "overload-resolution",
        permittedProducerStages: ["sema-overload-resolution"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "template-instantiation",
        permittedProducerStages: ["sema-template-instantiation"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "cuda-sema",
        permittedProducerStages: ["sema-cuda"],
        codeStrategy: "clang-raw-diagnostic-id",
      },
      {
        category: "artifact-extraction",
        permittedProducerStages: ["artifact-extractor"],
        codeStrategy: "closed-browsergrad-custom-code",
      },
      {
        category: "policy",
        permittedProducerStages: ["preprocessor"],
        codeStrategy: "closed-browsergrad-custom-code",
      },
      {
        category: "resource-limit",
        permittedProducerStages: [
          "preprocessor",
          "parser",
          "sema-name-lookup",
          "sema-overload-resolution",
          "sema-template-instantiation",
          "sema-cuda",
          "artifact-extractor",
        ],
        codeStrategy: "closed-browsergrad-custom-code",
      },
    ],
    customMappings: [
      {
        customCode: "browsergrad.cpp-cute:temporal-macro-forbidden",
        producerStage: "preprocessor",
        category: "policy",
        artifactSeverity: "error",
        blocking: true,
      },
      {
        customCode: "browsergrad.cpp-cute:temporal-macro-mutation-forbidden",
        producerStage: "preprocessor",
        category: "policy",
        artifactSeverity: "error",
        blocking: true,
      },
      {
        customCode: "browsergrad.cpp-cute:diagnostic-resource-limit",
        producerStage: "artifact-extractor",
        category: "resource-limit",
        artifactSeverity: "fatal",
        blocking: true,
      },
      {
        customCode: "browsergrad.cpp-cute:diagnostic-normalization-failed",
        producerStage: "artifact-extractor",
        category: "artifact-extraction",
        artifactSeverity: "fatal",
        blocking: true,
      },
      {
        customCode: "browsergrad.cpp-cute:semantic-extraction-failed",
        producerStage: "artifact-extractor",
        category: "artifact-extraction",
        artifactSeverity: "error",
        blocking: true,
      },
      {
        customCode: "browsergrad.cpp-cute:host-device-surface-divergence",
        producerStage: "artifact-extractor",
        category: "artifact-extraction",
        artifactSeverity: "error",
        blocking: true,
      },
    ],
    stableDiagnosticId: {
      algorithm: "sha256-canonical-json",
      domain: "browsergrad.compiler.cpp-cute.frontend-diagnostic-id.v1",
      outputPrefix: "bg.cpp.diagnostic.sha256.",
      projectionSchema: "browsergrad.compiler.cpp-cute.frontend-diagnostic-id-input@1",
      canonicalProjectionKeys: [
        "domain",
        "compilationContractHash",
        "ownerPassId",
        "diagnostic",
      ],
      compilationContractHashSource: "payload.compilationContractHash",
      ownerPassIdSource: "semantic-pass-diagnosticIds-membership.passId",
      serializedDiagnosticFields: [
        "phase",
        "severity",
        "code",
        "renderedMessage",
        "location",
        "subject",
        "parentDiagnosticId",
      ],
      parentDependency: "serialized-parentDiagnosticId-root-first",
      recomputationOrder: "root-diagnostics-then-direct-note-children",
      duplicatePolicy: "collapse-exact-canonical-projection-within-owner-pass",
      duplicateScope: "compilation-contract-and-owner-pass",
      forbiddenInputs: [
        "hostPath",
        "presumedPath",
        "wallClock",
        "pointerAddress",
        "threadId",
        "renderedColor",
        "fixIts",
        "rawClangDiagnosticId",
        "producerStage",
        "category",
        "emissionOrdinal",
        "sourceManagerAddress",
      ],
    },
    sourceLocationPolicy: {
      coordinateUnit: "utf8-byte-offset",
      rangeConvention: "half-open",
      pointConvention: "zero-width-half-open-range",
      pathIdentity: "physical-opened-vfs-file-only",
      presumedLocationUse: "rendering-only-never-identity",
      macroPolicy: "retain-physical-spelling-and-outermost-expansion",
      nonMacroPolicy: "spelling-and-expansion-must-match",
      crossFileRangePolicy: "reject-normalization",
      invalidLocationPolicy: "location-none-only-for-compiler-subject",
      maxRelatedLocations: 32,
      maxRenderedBytesPerRelatedLocation: 2_048,
      maxAggregateRenderedRelatedLocationBytes: 16_384,
    },
    pathNormalizationPolicy: {
      grammar: "canonical-posix-absolute-v1",
      root: "/",
      separator: "/",
      requireOpenedFileMembership: true,
      rejectBackslash: true,
      rejectNulAndControlBytes: true,
      rejectEmptyDotAndDotDotSegments: true,
      rejectTrailingSlashExceptRoot: true,
      rejectUriDriveAndNetworkForms: true,
      resolveSymlinks: false,
      useCurrentWorkingDirectory: false,
      useHostFilesystemFallback: false,
      lineDirectiveFilenameAuthority: false,
    },
    renderedTextPolicy: {
      encoding: "utf-8",
      unicodeNormalization: "preserve",
      lineEndings: "lf",
      allowTab: true,
      allowLineFeed: true,
      rejectNulOtherC0AndDelete: true,
      maxRenderedMessageBytes: 4_096,
      overflowDisposition: "emit-resource-limit-and-stop-pass-without-truncation",
    },
    notePolicy: {
      representation: "child-diagnostic-with-parent-diagnostic-id",
      ordering: "clang-emission-order",
      parentPolicy: "direct-child-of-emitted-root-only",
      normalizationOrder: "root-before-direct-note-children",
      maxNotesPerPrimaryDiagnostic: 16,
      maxRenderedBytesPerNote: 2_048,
      maxAggregateRenderedNoteBytesPerPrimaryDiagnostic: 16_384,
      orphanDisposition: "emit-normalization-failed-and-stop-pass",
      overflowDisposition: "emit-resource-limit-and-stop-pass-without-truncation",
    },
    fixItPolicy: {
      artifactV3Disposition: "bounded-validate-then-omit",
      ordering: "source-range-then-emission-order",
      maxFixItsPerDiagnostic: 16,
      maxReplacementBytesPerFixIt: 4_096,
      maxAggregateReplacementBytesPerDiagnostic: 16_384,
      requireOpenedFileMembership: true,
      requireSingleFileHalfOpenRange: true,
      overlappingRangeDisposition: "emit-normalization-failed-and-stop-pass",
      invalidRangeDisposition: "emit-normalization-failed-and-stop-pass",
      overflowDisposition: "emit-resource-limit-and-stop-pass-without-truncation",
      stableDiagnosticIdContribution: false,
    },
    unknownDiagnosticPolicy: {
      unknownRawId: "emit-versioned-raw-id-code-at-active-stage",
      malformedRawId: "emit-normalization-failed-and-stop-pass",
      unknownCategory: "use-producer-stage-default-category",
      unknownCustomCode: "emit-normalization-failed-and-stop-pass",
      unknownProducerStage: "emit-normalization-failed-and-stop-pass",
      unknownClangLevel: "emit-normalization-failed-and-stop-pass",
      preserveEffectiveSeverity: true,
      preserveBoundedRenderedMessage: true,
      rawIdIdentityContribution: "serialized-code-only",
      silentlyDrop: false,
    },
    diagnosticSetPolicy: {
      maxUniqueDiagnosticsPerSession: 1_000_000,
      maxRetainedNormalizedBytesPerSession: 8_388_608,
      effectiveLimits: "caller-must-narrow-but-never-widen",
      duplicateAccounting: "exact-duplicates-consume-no-additional-count-or-note-budget",
      terminalFailure: "invalid-or-resource-limit-poisons-normalizer",
    },
    authority: {
      designAuthority: true,
      clangInvocationAuthorized: false,
      diagnosticNormalizationPerformed: false,
      artifactProductionAuthorized: false,
    },
  },
} as const satisfies JsonObject;

export type CppCuteDiagnosticNormalizationV1Resource =
  typeof CPP_CUTE_DIAGNOSTIC_NORMALIZATION_V1_VALUE;

export const CPP_CUTE_DIAGNOSTIC_NORMALIZATION_V1_RESOURCE = deepFreezeJson(
  CPP_CUTE_DIAGNOSTIC_NORMALIZATION_V1_VALUE,
) as unknown as CppCuteDiagnosticNormalizationV1Resource;
