import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

/** Generated by cpp_cute_browser_exact_distribution_convergence_authoring.mjs. */
const VALUE = {
  "schema": "browsergrad.compiler.cpp-cute.browser-exact-distribution-convergence-observation",
  "version": 1,
  "authority": "package-pinned-local-engineering-exact-payload-convergence-observation-only",
  "matrixId": "bg.cpp.browser-exact-distribution-convergence.sha256.3e3c66fe9de9f74d8f6d0cc608cc996340a3b2aeaf66a8a580a82fe32f5f8ba3",
  "sourceRevision": "c039842b6155fd62ac662e7f5205bb9ba2a4ae86",
  "caseCount": 9,
  "distribution": {
    "assetManifestId": "bg.cpp.browser-assets.sha256.97ffd5434c8b8b88b1e461aab5285bd63ab512b339619568e0379184dff6e13b",
    "assetManifestSha256": "307a17722eb9892b29e63fd68f02368ef706f85271f29cdcd2d57c5634afe855",
    "assetSetSha256": "e8df813538e9f867ecc6085cc2cfb07142a9af70b0ad3c6777d618aad90f04ef",
    "buildInputLockId": "bg.cpp.browser-build-input-lock.sha256.08ddf15cbd0e5600fd1ae9f935cc7e3552e0140b665138ccdcf6d0f837bcdc34",
    "buildInputLockResourceSha256": "b0021295d4b9295abc3d8ef90a84883f3deae430d97446e5166444d0d82f025d",
    "buildSubjectId": "bg.cpp.browser-build-subject.sha256.d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42",
    "buildSubjectSha256": "d819e4a96135c5fd3b9f60c58018368ef402523a52675f02584b6ae149d79d42",
    "exactOutputByteLength": "103638762",
    "exactOutputCount": 25,
    "exactRootVerificationId": "bg.cpp.distribution-output-file-verification.sha256.60eab7a52938ddcd5d74afbb7df6ec49f35d1622b095bf3694e984c679660a8b",
    "profileByteLength": "7148",
    "profileHash": "bef58d9cf127e542d473039269d83cb54269ed710bf144b053ea5da9a9fda2a3",
    "profileSha256": "79ea59b9a1fcfce14df17ebf22bd70691c195a15136adffd1a27d228a3f80958",
    "reproducibilityId": "bg.cpp.browser-full-distribution-reproducibility.sha256.5543bed26d97d5b10498794ca2e1c1f47c17ebb0b7ac28d2a5814538031b80b3",
    "resourceSha256": "1c65397c68e7aec7129d4961b1891b97825468019bcd43333f49a350db119209",
    "workerBundleSha256": "33db9ab814e6ac9204a147006cbca845b7917b635d3f59efb9d9ac8a796c7626"
  },
  "producer": {
    "builderId": "https://builders.browsergrad.dev/local-engineering-reproducibility",
    "keyId": "sha256:5cacb1fa2e19b2654e59f1c2779f478e936719f1bc99a4b5ed6d924471a92910",
    "policyId": "bg.cpp.browser-producer-trust-policy.sha256.7cbcf35e2edab064eaf18699f2971f748cd66173e21d76459397954bba094cf1",
    "policySha256": "5748c23ab89e265c96e57ed6812ee37d14b2ca3ddf3d55e2381184e51ee38d9c",
    "producerEvidenceId": "bg.cpp.browser-build-producer.sha256.379fdc07578d7e6c0cf9f8274aa5095fda9e03041021e1acd4de7794cc7c24f6",
    "signatureEvidenceSha256": "fffb2103dd8dea486ca3b1cb6eaa8e0b0475548d20669bd5819ab0c318aff451",
    "statementSha256": "493be3f284af0a47dc7f2223d396645a1b541b29e25ed1d01f8bc1eb88ceb362",
    "trustStoreSha256": "2a4811b7012e62aa87d02c9aa05a60faa7f395a5fc85cad6d1bd95ea7b0431d7"
  },
  "webgpu": {
    "required": true,
    "actualExecutionObservedForEveryCase": true,
    "deviceProfileCount": 1,
    "deviceProfileHashes": [
      "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    ]
  },
  "cases": [
    {
      "caseId": "rank2",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.daa46144d092b79c8056d78cbe78fc2dc63297da3c8f1a8f6206ee9a6afb4ee2",
      "sourceSha256": "4134804a9892ed1f0a2778fae305e957b5a981afccf2a096f1585f3b1d4e6f06",
      "dtype": "f32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.73c6fdf4ec77dcc5034c6f87a09363e5aa41a5d1faa1072262119bce347cc5e1",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.b65cf56763747610e1fc2e726b3cdc03af6f04f0b4825bd9336eff355dba6ad5",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.17563621b150691c6cf03f65d78d16c67e6f239fd5c73600d6ba36b0efd322eb",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.51ddd715e71de6c52459079f222b7367b0c75a7472ee581dfa718db03780fdb1",
      "layoutSemanticHash": "5ade6e063773ba40a1046423e76776cf963544a26c7f17b301565d54a86ecdfe",
      "kernelSemanticHash": "64dc9d67e4f0de9c1f7b68fa369957c9521d8bbb9aa9725ac82f0dfaa573f409",
      "cpuDestinationHash": "db0e59ae7b62597986196566d4097087f097224e7ba9ba7bce497839dab6764c",
      "webGpuDestinationHash": "db0e59ae7b62597986196566d4097087f097224e7ba9ba7bce497839dab6764c",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "rank3",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.fb134aca6716b2ba91d9a37ae4d1fb6b4de350018390f02c7a01e845eb391718",
      "sourceSha256": "6a7beae44e88d7fe8749cb5b485dc7d51d30ed285d33314895be461d428550dd",
      "dtype": "f32",
      "coordinateRank": 3,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.7fac8138302f071dc4a4c6029d1cf6f34173245ba8b771b04ceb20acf057eafb",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.e7b688cd0044c6ca9052f5dc555dc0ff8597ee3f5a6597d99a451f7aa00db5b7",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.3c3e4f4cfd0d5a13536ebee50acef6aca19a6a61e75664fe65a9613fac762439",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.d4cb9d724d677ccd0c1216f5c43b6a48fa9a8a2b84efa286ee4bb1e6531db4e6",
      "layoutSemanticHash": "c2b5e8a0489bd2ee5a54d15399af95b91d9fe102aab63e450361500ffa946a6f",
      "kernelSemanticHash": "e335ea9d9e9a38f591c80c737b8a33401578739e02d6892e5f1907e6b76e6ff2",
      "cpuDestinationHash": "1d1c9094fa8fb4c5a2b9f83093cd1ccca1ec8402de26abe1dee6c3843e7d5c2a",
      "webGpuDestinationHash": "1d1c9094fa8fb4c5a2b9f83093cd1ccca1ec8402de26abe1dee6c3843e7d5c2a",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "rank1",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.bfc4c48c191da5252d7f4ccc0c52fe54b5460e5a657443054e274a318ba00598",
      "sourceSha256": "7c8fc9f261fab7181e9c25d124f2604d31a48a5c9bc49e043c42f9371a27c1c7",
      "dtype": "f32",
      "coordinateRank": 1,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.e7645839de383625c2922b5138d82174787cf639c35a13306066c731af34bfaf",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.c1d34501b96eab0d2c998dc73938f8753cbc3b28fe63e2d63e587efe73bca4a3",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.b6b5d2e8ba5d5c2c07d53985089eb533941c6320c263d9985c755c05eda792df",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.332fa1876c5266a113f2cd228f0bdc10da2db0f43298213ccdb5cc4d93a9a02e",
      "layoutSemanticHash": "89bf81de47ee52bef3e927ce3ace9fb2d77296eb8214f5a4f0aad184b5816e43",
      "kernelSemanticHash": "02f310f29ae7d8080c5a3f6926ae6ef0c65d32040b7cc8190db56ea40763931c",
      "cpuDestinationHash": "5c6ab95d110f933c4112c8a9b1ea7451afb09a8e018aa1cf115b2da3cc4cd021",
      "webGpuDestinationHash": "5c6ab95d110f933c4112c8a9b1ea7451afb09a8e018aa1cf115b2da3cc4cd021",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "rank4",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.dbe25dbdf365366bd9b7364674b377c1e0b19fb10f0126457c2c5e3ac416ed09",
      "sourceSha256": "28d6094af10254112f25ea717739c836c2c74a4c3f35c7b88dcc45ad60e5a05a",
      "dtype": "f32",
      "coordinateRank": 4,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.e8ebc6159be11fbddf7a128118f316b4c7099255fa9ff15769f0852f46891396",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.9b2dcfe7005005351bd6067d350fb0239e13950c47b72b931d39ff0ab6906212",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.69f906c74799883d9e42b925a210b414f018a11fecb923f86fac0f26ccbba218",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.e8c6212d53dcac55f35089897216a1deef71b3453241fa83a2cb83bb8f1745cb",
      "layoutSemanticHash": "f71fa705c81324cbb001d7bcf06b48228b5eabcbad461ab99c82f138b59c4b41",
      "kernelSemanticHash": "eeafc342c45e9c0046e82b67fb9e5f1ad9b991beae24063e2a88ca732dc2700b",
      "cpuDestinationHash": "05c5aefa8646898996289d943056e68b1844190feaa58bbef23d5690ff72828d",
      "webGpuDestinationHash": "05c5aefa8646898996289d943056e68b1844190feaa58bbef23d5690ff72828d",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "strided-slice",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.79898ec75f2436bb7fb5357b9576d1a3951d93eb4207b247bc4d612d625c666e",
      "sourceSha256": "55f4f5fcf55093a05cb977e3b83479098f6ddc42b830ec63f44b97f27fe3264a",
      "dtype": "f32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.5ee871798eb6a10c4c9de72ff2d8c5ea35c2098f466d421b7c6b41a120b838e0",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.37e15e466ad96cc0dd99fe779101836d5b8072cff94595963880bc48a84bbf94",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.f4ab4e1ebb06d82d5393d4f46069f77796a5987b9c28cb9e21e575c6815cf3b0",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.0f2a9a5709907a91524819856b99801ac1386602e95b652466ba03b25fbae112",
      "layoutSemanticHash": "c43e46d9b4a2fe623b70c5ff67ce5b35e260b5a498a2ede0bf67984d1cc46399",
      "kernelSemanticHash": "939d9e9ec1125485b71ac28aa5bf491928c0721e7642a72d6dc18e6734187d73",
      "cpuDestinationHash": "318df11b8031b82c60a6971b1b1172e68aa23bf1c7edded1135392783c961fd4",
      "webGpuDestinationHash": "318df11b8031b82c60a6971b1b1172e68aa23bf1c7edded1135392783c961fd4",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "broadcast",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.dc570370ad726f16675ce3e3df4070e62f464dc18f0bc40ffbbc0a0435481ad1",
      "sourceSha256": "bfd91bdaac57ef7314570a8de56f26165a7b263593f319d728c53c13ef7c6376",
      "dtype": "f32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.e2a0ea8b63268c0b27af5f00f7bccc76a0a76e435a37c96e5bcf61d2d2dde082",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.5b844fdd341a1b332bedd59396b4870881070a582a8b1d5848806495738cea0a",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.ca6c4f0cc6f044c22ce85b6be1dd3385405c1e4db034a71ee57f80dc243b104b",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.22436ff2198cd4606db3a8b814771b37b83100ef8bdedd280b3d82b9ff5e13aa",
      "layoutSemanticHash": "5e72e11b9dc901e8c9f4cc05221c3f24fced5f2701bd129aa3dd2c183631a718",
      "kernelSemanticHash": "bfa123e13a4d162ee02a736490494d5ee5d3577d875c819283f0f2243c5fea16",
      "cpuDestinationHash": "60d8fbebb1cf3026189c500e30ae88802f7e3d91651d6fb40774aff808ccfb1b",
      "webGpuDestinationHash": "60d8fbebb1cf3026189c500e30ae88802f7e3d91651d6fb40774aff808ccfb1b",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "i32-rank2",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.939428f7704b51045c7a224d153b3e0c19613429ad65d48eed426d71c879c4c5",
      "sourceSha256": "88a083b141a5b7a85a9a1f2420873029f891cc1738e74ababe849a58bb839577",
      "dtype": "i32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.dc24abb0854506ebc6de97e499b3f3bef579da206d317d6629e35aae269bb125",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.95b28c81deffed79cacbb48236a119a2b6eb77e6ccd1e133119063154bcc6e52",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.83f1855481d7473918db4d930ec5913340206f31f0f30384d78247328362f1b6",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.58d9682718a04f388f5ebe88d24d5d901d81b718635274155289bdbecc85f7a6",
      "layoutSemanticHash": "a29489aaa6c39240c1b5082e3b3b4cf89e7ecdf3a645a25380955799fa884210",
      "kernelSemanticHash": "bfb93603b68d0b6f96785f415bb17398767d4b82d3204b25a04d0fbd2500201e",
      "cpuDestinationHash": "e9eb93a4e037911ffa699e1e8fc936d31539ae65fc9a071b36aee9531757655d",
      "webGpuDestinationHash": "e9eb93a4e037911ffa699e1e8fc936d31539ae65fc9a071b36aee9531757655d",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "u32-broadcast",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.767c4465d003c28905ac2f3ccc47552100c51efb5f168c22ba093aadcddedc44",
      "sourceSha256": "c21158f1cb394377b5b8057435bfaad64b515689a8b04391a1bcae643a567536",
      "dtype": "u32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.9e2a00878e2d8dc542a0e2f11d92b321f49b4573bd88725be1f8920780602ffa",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.83a0283b156948f9ce003e46a9212cd5e3011796c28d9e2ea6717cff2d7d6e3d",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.7b76f0d11df6545ca1a0c6d9883da930f12d91711eec3e6a254b4f9dd52f3538",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.0449ed42524398da361837510478282db1981a59d09017d8dacaa3e86267282c",
      "layoutSemanticHash": "063922fecf9239305bf20d810b49e979307994e2695a68ddb2c9913f08fb5f4e",
      "kernelSemanticHash": "72298c98ee1bef581aa04cf43a7ad859be3393396852df52075e1771043d0775",
      "cpuDestinationHash": "11bd283413d5dc57742c673834ce3605098c3ecd042b8782501b43f2a3aad300",
      "webGpuDestinationHash": "11bd283413d5dc57742c673834ce3605098c3ecd042b8782501b43f2a3aad300",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    },
    {
      "caseId": "signed-rank2",
      "evidenceId": "bg.cpp.browser-exact-distribution-case-convergence.sha256.327fffe025448643510925d7a1ad4fc4858022b91b3c5b53ee0c47a803273102",
      "sourceSha256": "1b7d54daae8b5339b8a9412a50355cf9917ebd5b7d568045c9c2260ead801d62",
      "dtype": "f32",
      "coordinateRank": 2,
      "candidateId": "bg.cpp.browser-worker-view-copy-candidate.sha256.f3a4596a0ab1cf70f3844f3fb938db66d2085d4678993b1b83addd08479b2435",
      "artifactId": "bg.artifact.cpp-cute-frontend.sha256.5ffb052d93e3232e334192308d120d187e99229f28139dc7a5c9b6b252d12ee1",
      "authorizationId": "bg.cpp.browser-view-copy-authorization.sha256.e45b8ef9e76701fa6d4f40c044ac738fe03ae37f318865261df644576035583f",
      "executionEvidenceId": "bg.cpp.browser-worker-execution.sha256.792a55b69ea25c580d5f204f2379de28eee51b8df096f9092fafd4bb34ac3897",
      "layoutSemanticHash": "fe9d7da4c98eb7b8740fbb93035922bbbe60a2315a291b058ba3eeae2312ab81",
      "kernelSemanticHash": "5be0fb2cc8848ee6e5101e643b8b2487dccff8e99e7b30c682849097f265fd16",
      "cpuDestinationHash": "71683706f28bab41ea8eb3f155e681995a8bdb0107c10c16654cd4a7453ac363",
      "webGpuDestinationHash": "71683706f28bab41ea8eb3f155e681995a8bdb0107c10c16654cd4a7453ac363",
      "deviceProfileHash": "4a9870f131d8a842743b6f5a22c73db085238186ac620289798536a4a4091c59"
    }
  ],
  "claims": {
    "exactPrivateDistributionTreeVerified": true,
    "packagePinnedFullDistributionReproducibilityMatched": true,
    "exactNineCaseBrowserWorkerCompilationObserved": true,
    "localEngineeringProducerAuthenticated": true,
    "exactCandidatesAuthorizedThroughSharedSeam": true,
    "cpuReferenceConvergenceObservedForEveryCase": true,
    "requiredRealWebGpuConvergenceObservedForEveryCase": true,
    "completeDestinationBitComparisonPassedForEveryCase": true,
    "nonzeroOffsetCanariesPreservedForEveryCase": true,
    "externalProducerTrusted": false,
    "licenseReviewComplete": false,
    "distributionAuthorized": false,
    "backendExecutionAuthorityMinted": false,
    "releaseReady": false
  }
} as const satisfies JsonObject;

export type CppCuteBrowserExactDistributionConvergenceV1Resource =
  typeof VALUE;

export const CPP_CUTE_BROWSER_EXACT_DISTRIBUTION_CONVERGENCE_V1_RESOURCE =
  deepFreezeJson(VALUE) as unknown as
    CppCuteBrowserExactDistributionConvergenceV1Resource;
