import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

/**
 * Canonical design contract for the browser-local Clang-WASM extractor.
 *
 * This resource defines the interface a built module must satisfy. It is not
 * evidence that any Wasm bytes satisfy the interface and grants no build,
 * provenance, Worker-execution, or release authority.
 */
const CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE = {
  schema: "browsergrad.compiler.cpp-cute.browser-runtime-abi-manifest",
  version: { major: 1, minor: 1 },
  manifestId: "bg.cpp.browser-runtime-abi.sha256.df1948909dc26d5339659c380a4a5d1601ccecba43433585a779ebe3e3a16d0e",
  body: {
    runtimeAbiId: "browsergrad.compiler.cpp-cute.clang-wasm-runtime@1",
    authority: {
      kind: "design-contract-only",
      observedWasm: "detached-verification-required",
      workerExecution: "not-authorized",
      releaseReadiness: "not-authorized",
    },
    wasm: {
      moduleRole: "compiler-extractor-only-user-programs-never-linked-or-executed",
      addressBits: 32,
      cAbiVersion: 65_537,
      cAbiVersionEncoding: "major-shift-left-16-bitwise-or-minor",
      requiredFeatures: [
        "bulk-memory",
        "mutable-globals",
        "nontrapping-fptoint",
        "sign-extension",
      ],
      forbiddenFeatures: [
        "atomics",
        "exception-handling",
        "memory64",
        "multi-memory",
        "simd128",
        "threads",
      ],
      featurePolicy: {
        instructionSetBaseline: "webassembly-mvp",
        allowedExtensions: [
          "bulk-memory",
          "mutable-globals",
          "nontrapping-fptoint",
          "sign-extension",
        ],
        unlistedExtensions: "forbidden",
        staticOpcodeAndSectionInspection: "required",
        targetFeaturesCrossCheck: "required-but-not-authoritative",
      },
      startSection: "forbidden",
      unlistedCExports: "forbidden",
      supportExports: {
        status: "unresolved-first-build-review-required",
        exactFunctionAllowlist: [],
        exactGlobalAllowlist: [],
        exactTableAllowlist: [],
        unlistedExports: "forbidden",
        observedModuleCannotExtendAllowlist: true,
        releaseConformance: "forbidden-until-independent-review-and-manifest-repin",
      },
      structuralPolicy: {
        status: "unresolved-first-build-review-required",
        releaseConformance: "forbidden-until-exact-first-build-projection-is-reviewed-and-repinned",
        tables: {
          maximumCount: 1,
          allowedElementTypes: ["funcref"],
          imported: "forbidden",
          declaredMaximumRequired: true,
          maximumElementsCeiling: 65_536,
          exactReviewedProjection: [],
        },
        globals: {
          maximumCount: 4_096,
          allowedValueTypes: ["f32", "f64", "i32", "i64"],
          imported: "forbidden",
          exactReviewedExports: [],
        },
        tags: {
          exactCount: 0,
          imported: "forbidden",
          exported: "forbidden",
        },
        customSections: {
          maximumCount: 4,
          maximumSectionByteLength: 524_288,
          maximumTotalByteLength: 1_048_576,
          duplicateNames: "forbidden",
          exactReviewedNameAllowlist: [],
          unlistedNames: "forbidden",
          explicitlyForbiddenNames: ["dylink.0", "producers", "sourceMappingURL"],
          targetFeatures: {
            sectionName: "target_features",
            status: "unresolved-first-build-review-required",
            requiredDeclarations: [
              "bulk-memory",
              "mutable-globals",
              "nontrapping-fptoint",
              "sign-ext",
            ],
            forbiddenDeclarations: [
              "atomics",
              "exception-handling",
              "memory64",
              "multimemory",
              "simd128",
            ],
            exactRawSectionProjection: [],
          },
        },
      },
      memory: {
        count: 1,
        addressType: "i32",
        imported: false,
        exported: true,
        exportName: "memory",
        sharing: "unshared",
        ownership: "module-instance-owned-by-dedicated-worker",
        pageByteLength: 65_536,
        initialPages: 4_096,
        maximumPages: 16_384,
        growth: "allowed-to-maximum",
        growthLinearStepPages: 1_024,
        stackByteLength: 16_777_216,
        maxCompilerWorkingByteLength: 536_870_912,
        maxInputFrameByteLength: 4_194_304,
        maxResultByteLength: 8_388_608,
      },
    },
    cExports: [
      {
        ordinal: 0,
        cSymbol: "bg_cpp_cute_abi_version",
        wasmExportName: "bg_cpp_cute_abi_version",
        cSignature: "uint32_t bg_cpp_cute_abi_version(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-packed-abi-version",
      },
      {
        ordinal: 1,
        cSymbol: "bg_cpp_cute_alloc",
        wasmExportName: "bg_cpp_cute_alloc",
        cSignature: "uint32_t bg_cpp_cute_alloc(uint32_t byte_length)",
        wasmParameters: ["i32"],
        wasmResults: ["i32"],
        resultSemantics: "u32-input-pointer-zero-on-failure",
      },
      {
        ordinal: 2,
        cSymbol: "bg_cpp_cute_allocator_metrics_pointer",
        wasmExportName: "bg_cpp_cute_allocator_metrics_pointer",
        cSignature: "uint32_t bg_cpp_cute_allocator_metrics_pointer(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-nonzero-stable-read-only-allocator-metrics-record-v1-pointer",
      },
      {
        ordinal: 3,
        cSymbol: "bg_cpp_cute_compile",
        wasmExportName: "bg_cpp_cute_compile",
        cSignature: "int32_t bg_cpp_cute_compile(uint32_t input_pointer, uint32_t input_length)",
        wasmParameters: ["i32", "i32"],
        wasmResults: ["i32"],
        resultSemantics: "typed-compile-status",
      },
      {
        ordinal: 4,
        cSymbol: "bg_cpp_cute_free",
        wasmExportName: "bg_cpp_cute_free",
        cSignature: "void bg_cpp_cute_free(uint32_t pointer, uint32_t byte_length)",
        wasmParameters: ["i32", "i32"],
        wasmResults: [],
        resultSemantics: "void-status-readable-separately",
      },
      {
        ordinal: 5,
        cSymbol: "bg_cpp_cute_reset",
        wasmExportName: "bg_cpp_cute_reset",
        cSignature: "void bg_cpp_cute_reset(void)",
        wasmParameters: [],
        wasmResults: [],
        resultSemantics: "void-infallible-for-live-instance",
      },
      {
        ordinal: 6,
        cSymbol: "bg_cpp_cute_result_length",
        wasmExportName: "bg_cpp_cute_result_length",
        cSignature: "uint32_t bg_cpp_cute_result_length(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-result-length-zero-unless-artifact-ready",
      },
      {
        ordinal: 7,
        cSymbol: "bg_cpp_cute_result_pointer",
        wasmExportName: "bg_cpp_cute_result_pointer",
        cSignature: "uint32_t bg_cpp_cute_result_pointer(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-result-pointer-zero-unless-artifact-ready",
      },
      {
        ordinal: 8,
        cSymbol: "bg_cpp_cute_status",
        wasmExportName: "bg_cpp_cute_status",
        cSignature: "int32_t bg_cpp_cute_status(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "current-typed-status-without-state-mutation",
      },
    ],
    allocatorMetricsRecord: {
      schema: "browsergrad.compiler.cpp-cute.allocator-metrics-record",
      version: { major: 1, minor: 0 },
      magicAscii: "BGRTMET1",
      magicBytes: [66, 71, 82, 84, 77, 69, 84, 49],
      byteLength: 72,
      alignmentByteLength: 8,
      encoding: "little-endian-fixed-width",
      storage: "module-global-linear-memory-record",
      pointerExport: "bg_cpp_cute_allocator_metrics_pointer",
      pointerContract: {
        resultEncoding: "u32-wasm32-linear-memory-offset",
        zero: "forbidden-for-conforming-live-module-instance",
        stability: "constant-for-module-instance-lifetime",
        completeRange: "must-fit-current-exported-memory",
        mutability: "module-writes-host-read-only",
      },
      snapshotContract: {
        allowedPhases: "between-synchronous-runtime-calls-only",
        hostRead: "copy-exact-record-before-decoding",
        memoryGrowthDuringCopy: "forbidden",
        consistency: "module-calls-are-synchronous-and-memory-is-unshared",
      },
      accounting: {
        unit: "requested-bytes",
        scope: "all-instrumented-module-global-allocator-events",
        interception: {
          exactEntrypoints: [
            "aligned_alloc",
            "calloc",
            "free",
            "__libc_calloc",
            "__libc_free",
            "__libc_malloc",
            "__libc_realloc",
            "malloc",
            "memalign",
            "posix_memalign",
            "pvalloc",
            "realloc",
            "reallocarray",
            "valloc",
          ],
          forbiddenEntrypoints: [
            "bulk_free",
            "independent_calloc",
            "independent_comalloc",
            "realloc_in_place",
          ],
          underlyingBypassEntrypoints: [
            "emscripten_builtin_calloc",
            "emscripten_builtin_free",
            "emscripten_builtin_malloc",
            "emscripten_builtin_memalign",
            "emscripten_builtin_realloc",
          ],
          directBypassReferences:
            "forbidden-outside-BrowserGradCppCuteMetrics.cpp",
          linkClosureProof:
            "pinned-object-and-final-wasm-call-graph-evidence-required",
        },
        requestedByteBasis: "caller-requested-byte-length-before-alignment-or-allocator-rounding",
        currentFormula: "cumulative-allocated-minus-cumulative-freed",
        peakFormula: "maximum-current-live-since-module-instantiation",
        resetPolicy: "counters-persist-and-reset-frees-are-accounted-until-worker-termination",
        allocationCountSemantics: "successful-creation-or-resize-of-one-tracked-live-allocation",
        freeCountSemantics: "successful-release-of-one-tracked-live-allocation",
        failedAllocationCountSemantics: "failed-nonzero-request-that-preserves-all-prior-live-allocations",
        failedInvalidRequestSemantics:
          "invalid-or-size-overflowing-nonzero-request-increments-failed-once-zero-request-does-not",
        zeroByteCreationSemantics:
          "nonnull-result-counts-one-tracked-zero-byte-allocation-null-result-is-permitted-no-op-neither-success-nor-failure",
        freeNullSemantics: "no-op-with-no-counter-change",
        reallocNullPointerSemantics: "same-as-creation-at-requested-size",
        reallocNonzeroSuccessSemantics:
          "allocated-adds-new-requested-size-freed-adds-old-requested-size-success-and-free-counts-each-increment-once-even-in-place",
        reallocNonzeroFailureSemantics:
          "failed-count-increments-once-and-all-live-byte-and-success-free-counters-remain-unchanged",
        reallocZeroSizeSemantics:
          "nonnull-old-pointer-is-released-freed-adds-old-requested-size-free-count-increments-once-result-is-null-and-failure-count-does-not-change",
        excludes: [
          "allocator-metadata-alignment-and-size-class-rounding",
          "javascript-heap-and-worker-host-memory",
          "static-data-and-module-globals",
          "vfs-logical-reservations-not-resident-in-wasm-memory",
          "wasm-stack",
        ],
        invariants: [
          "cumulative-freed-is-less-than-or-equal-to-cumulative-allocated",
          "current-equals-cumulative-allocated-minus-cumulative-freed",
          "free-count-is-less-than-or-equal-to-successful-allocation-count",
          "peak-is-between-current-and-cumulative-allocated-inclusive",
          "peak-cumulative-and-count-counters-are-monotonic-for-module-instance-lifetime",
        ],
        overflowPolicy: "counter-overflow-must-fail-closed-before-wrap-and-forbids-artifact-ready",
      },
      fields: [
        {
          ordinal: 0,
          name: "magic",
          offset: 0,
          byteLength: 8,
          encoding: "ascii[8]",
          semantics: "must-equal-BGRTMET1",
        },
        {
          ordinal: 1,
          name: "version",
          offset: 8,
          byteLength: 4,
          encoding: "u32le",
          semantics: "must-equal-1",
        },
        {
          ordinal: 2,
          name: "byteLength",
          offset: 12,
          byteLength: 4,
          encoding: "u32le",
          semantics: "must-equal-72",
        },
        {
          ordinal: 3,
          name: "currentLiveGlobalRequestedByteLength",
          offset: 16,
          byteLength: 8,
          encoding: "u64le",
          semantics: "current-live-requested-bytes",
        },
        {
          ordinal: 4,
          name: "peakLiveGlobalRequestedByteLength",
          offset: 24,
          byteLength: 8,
          encoding: "u64le",
          semantics: "peak-live-requested-bytes",
        },
        {
          ordinal: 5,
          name: "cumulativeGlobalAllocatedRequestedByteLength",
          offset: 32,
          byteLength: 8,
          encoding: "u64le",
          semantics: "cumulative-successfully-allocated-requested-bytes",
        },
        {
          ordinal: 6,
          name: "cumulativeGlobalFreedRequestedByteLength",
          offset: 40,
          byteLength: 8,
          encoding: "u64le",
          semantics: "cumulative-successfully-freed-requested-bytes",
        },
        {
          ordinal: 7,
          name: "successfulAllocationCount",
          offset: 48,
          byteLength: 8,
          encoding: "u64le",
          semantics: "successful-creation-or-resize-event-count",
        },
        {
          ordinal: 8,
          name: "freeCount",
          offset: 56,
          byteLength: 8,
          encoding: "u64le",
          semantics: "successful-tracked-release-event-count",
        },
        {
          ordinal: 9,
          name: "failedAllocationCount",
          offset: 64,
          byteLength: 8,
          encoding: "u64le",
          semantics: "failed-request-event-count",
        },
      ],
      authority: {
        values: "module-self-reported-local-observation-only",
        producerConformance: "detached-observed-wasm-verification-required",
        workerExecution: "not-authorized-by-record-values",
        lowering: "not-authorized-by-record-values",
      },
    },
    hostImports: {
      moduleName: "browsergrad_vfs_v1",
      invocation: "synchronous-non-reentrant",
      pointerLifetime: "only-for-import-call-duration",
      unlistedApplicationImports: "forbidden",
      generatedImportAllowlist: {
        policyId: "browsergrad.compiler.cpp-cute.emscripten-generated-imports@1",
        status: "unresolved-first-build-review-required",
        allowlistSha256: "ee4936a35d73df799e5d6f2c4eaad86d3cb8ba10d1dfd1e53da9f9e7f32e0075",
        exactFunctions: [],
        unlistedGeneratedImports: "forbidden",
        observedModuleCannotExtendAllowlist: true,
        capabilityCeiling: "no-clock-random-network-process-or-ambient-filesystem",
        releaseConformance: "forbidden-until-independent-review-and-manifest-repin",
      },
      memoryAccess: {
        rangeArithmetic: "checked-u32-no-wrap",
        completeRangeValidation: "required-before-first-input-read-or-output-write",
        pathInputSnapshot: "after-complete-range-validation-before-any-output-write",
        inputOutputOverlap: "allowed-only-after-complete-input-snapshot",
        outputOutputOverlap: "forbidden",
        memoryGrowthDuringImport: "forbidden",
        invalidRangeMemoryMutation: "forbidden",
        alignmentByteLength: {
          byteOutput: 1,
          u32Output: 4,
          u64ContainingRecord: 8,
        },
      },
      functions: [
        {
          ordinal: 0,
          fieldName: "bg_vfs_status",
          cSignature: "int32_t bg_vfs_status(uint32_t path_pointer, uint32_t path_length, uint32_t metadata_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-one-32-byte-metadata-record-for-an-existing-file-or-directory",
        },
        {
          ordinal: 1,
          fieldName: "bg_vfs_open",
          cSignature: "int32_t bg_vfs_open(uint32_t path_pointer, uint32_t path_length, uint32_t open_result_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "open-one-existing-file-and-write-one-16-byte-open-result",
        },
        {
          ordinal: 2,
          fieldName: "bg_vfs_read",
          cSignature: "int32_t bg_vfs_read(uint32_t handle, uint32_t offset_low, uint32_t offset_high, uint32_t destination_pointer, uint32_t byte_length)",
          wasmParameters: ["i32", "i32", "i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "copy-the-exact-requested-range-or-copy-nothing",
        },
        {
          ordinal: 3,
          fieldName: "bg_vfs_close",
          cSignature: "int32_t bg_vfs_close(uint32_t handle)",
          wasmParameters: ["i32"],
          wasmResults: ["i32"],
          semantics: "close-one-live-file-handle-exactly-once",
        },
        {
          ordinal: 4,
          fieldName: "bg_vfs_directory_count",
          cSignature: "int32_t bg_vfs_directory_count(uint32_t path_pointer, uint32_t path_length, uint32_t count_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-the-stable-immediate-child-count-for-one-directory",
        },
        {
          ordinal: 5,
          fieldName: "bg_vfs_directory_entry",
          cSignature: "int32_t bg_vfs_directory_entry(uint32_t path_pointer, uint32_t path_length, uint32_t index, uint32_t name_pointer, uint32_t name_capacity, uint32_t metadata_pointer)",
          wasmParameters: ["i32", "i32", "i32", "i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-one-byte-sorted-child-basename-and-one-32-byte-metadata-record",
        },
      ],
    },
    vfs: {
      storage: "host-backed-lazy-verified-pack-files-only",
      physicalFilesystemFallback: "forbidden",
      networkFallback: "forbidden",
      pathEncoding: "utf8",
      pathForm: "canonical-absolute-forward-slash-no-nul-dot-or-parent-segments",
      maxPathByteLength: 4_096,
      maxIndexedNodes: 262_144,
      maxIndexLogicalByteLength: 134_217_728,
      indexLogicalByteAccounting:
        "sum-per-node-metadata-record-plus-canonical-path-utf8-plus-immediate-basename-utf8",
      maxAggregateLiveOpenByteLength: 402_653_184,
      liveOpenByteAccounting:
        "logical-full-file-per-live-handle-reservation-not-wasm-residency",
      maxLiveFileHandles: 65_536,
      maxSessionCalls: 1_000_000,
      directoryOrder: "strict-ascending-utf8-byte-order",
      metadataRecord: {
        byteLength: 32,
        fields: [
          { name: "kind", offset: 0, encoding: "u32le", values: ["file=1", "directory=2"] },
          { name: "nameByteLength", offset: 4, encoding: "u32le", values: ["zero-for-status"] },
          { name: "fileByteLength", offset: 8, encoding: "u64le", values: ["zero-for-directory"] },
          { name: "uniqueIdDevice", offset: 16, encoding: "u64le", values: ["session-stable"] },
          { name: "uniqueIdFile", offset: 24, encoding: "u64le", values: ["session-stable"] },
        ],
      },
      openResultRecord: {
        byteLength: 16,
        fields: [
          { name: "handle", offset: 0, encoding: "u32le" },
          { name: "reserved", offset: 4, encoding: "u32le-zero" },
          { name: "fileByteLength", offset: 8, encoding: "u64le" },
        ],
      },
      statuses: [
        { code: 0, name: "ok" },
        { code: 1, name: "not-found" },
        { code: 2, name: "not-directory" },
        { code: 3, name: "is-directory" },
        { code: 4, name: "invalid-path" },
        { code: 5, name: "buffer-too-small" },
        { code: 6, name: "out-of-range" },
        { code: 7, name: "invalid-handle" },
        { code: 8, name: "resource-limit" },
        { code: 9, name: "session-closed" },
        { code: 10, name: "internal-error" },
      ],
      failureAtomicity: "nonzero-status-writes-no-output-except-required-name-length-in-metadata",
      noAmbientInputs: ["clock", "current-directory", "environment", "locale", "random", "timezone"],
    },
    inputFrame: {
      encoding: "little-endian-binary-header-with-canonical-json-regions",
      magicAscii: "BGCCABI1",
      major: 1,
      minor: 0,
      headerByteLength: 64,
      alignmentByteLength: 8,
      maxFrameByteLength: 4_194_304,
      fields: [
        { name: "magic", offset: 0, encoding: "ascii[8]" },
        { name: "major", offset: 8, encoding: "u16le" },
        { name: "minor", offset: 10, encoding: "u16le" },
        { name: "headerByteLength", offset: 12, encoding: "u32le" },
        { name: "totalByteLength", offset: 16, encoding: "u32le" },
        { name: "flags", offset: 20, encoding: "u32le-zero" },
        { name: "profileOffset", offset: 24, encoding: "u32le-must-equal-64" },
        { name: "profileByteLength", offset: 28, encoding: "u32le" },
        { name: "requestOffset", offset: 32, encoding: "u32le-aligned-8" },
        { name: "requestByteLength", offset: 36, encoding: "u32le" },
        { name: "reserved", offset: 40, encoding: "zero[24]" },
      ],
      profileRegion: "exact-canonical-prepared-frontend-profile-json",
      requestRegion: "exact-canonical-producer-neutral-frontend-request-json",
      regionOrder: "profile-then-zero-padding-then-request-then-zero-padding",
      totalLengthRule: "aligned-request-end-equals-total-byte-length-and-all-regions-are-in-bounds",
      sourceBytes: "out-of-band-through-worker-owned-vfs-session",
      compileReadRule: "synchronous-complete-frame-validation-before-vfs-access",
    },
    compileStatuses: [
      { code: 0, name: "artifact-ready", retry: "reset-then-new-invocation" },
      { code: 1, name: "idle", retry: "allocate-input" },
      { code: 2, name: "input-allocated", retry: "compile-or-free" },
      { code: 100, name: "invalid-state", retry: "reset-required" },
      { code: 101, name: "invalid-argument", retry: "reset-required" },
      { code: 102, name: "invalid-frame", retry: "reset-required" },
      { code: 103, name: "abi-mismatch", retry: "module-must-not-be-reused" },
      { code: 104, name: "vfs-error", retry: "reset-required" },
      { code: 105, name: "resource-limit", retry: "reset-required" },
      { code: 106, name: "internal-error", retry: "module-must-not-be-reused" },
    ],
    lifecycle: {
      initialState: "idle",
      states: ["idle", "input-allocated", "compiling-internal", "artifact-ready", "failed"],
      rules: [
        "alloc-is-valid-only-in-idle-with-byte-length-from-1-through-max-input-frame-byte-length",
        "only-one-live-input-allocation-is-permitted",
        "compile-is-valid-only-for-the-exact-live-input-pointer-and-length",
        "compile-is-synchronous-and-not-reentrant",
        "compile-status-zero-means-one-complete-canonical-artifact-is-ready-even-when-that-artifact-rejects-source",
        "infrastructure-failure-never-masquerades-as-a-rejected-source-artifact",
        "free-is-valid-only-for-the-exact-live-input-pointer-and-length-and-never-for-result-memory",
        "free-after-success-preserves-the-artifact-ready-result",
        "result-getters-return-zero-unless-state-is-artifact-ready",
        "result-bytes-are-immutable-until-reset",
        "reset-releases-input-result-and-module-side-vfs-state-and-returns-to-idle",
        "after-abi-mismatch-or-internal-error-the-worker-discards-the-module-instance-after-reading-status",
        "wasm-trap-abort-or-out-of-memory-is-a-worker-infrastructure-failure-with-no-readable-status-guarantee",
      ],
    },
    result: {
      schema: "browsergrad.compiler.cpp-cute.frontend-artifact",
      version: { major: 3, minor: 0 },
      encoding: "canonical-json-bytes",
      maximumByteLength: 8_388_608,
      ownership: "module-owned-worker-must-copy-before-reset",
      lifetime: "from-artifact-ready-until-reset-or-worker-termination",
      emptyResult: "forbidden-when-status-is-artifact-ready",
    },
    cancellation: {
      mechanism: "terminate-dedicated-worker",
      cooperativeImport: "forbidden",
      reason: "synchronous-unshared-wasm-cannot-service-worker-messages-during-compile",
      effect: "invalidates-module-memory-input-result-vfs-handles-and-session-authority",
      workerReuseAfterCancellation: "forbidden",
    },
  },
} as const satisfies JsonObject;

export type CppCuteBrowserRuntimeAbiManifestV1Resource =
  typeof CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE;

export const CPP_CUTE_BROWSER_RUNTIME_ABI_V1_RESOURCE = deepFreezeJson(
  CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE,
) as unknown as CppCuteBrowserRuntimeAbiManifestV1Resource;
