import {
  deepFreezeJson,
  type JsonObject,
} from "@unlocalhosted/browsergrad-semantic-core/schema";

type WasmValueType = "f32" | "f64" | "i32" | "i64";
type GeneratedImportRuntimeRole =
  | "bounded-memory-growth"
  | "javascript-exception-control-flow"
  | "stack-overflow-trap"
  | "stdout-stderr-only";
type SupportExportRuntimeRole =
  | "allocator-runtime"
  | "javascript-exception-bridge"
  | "module-initialization"
  | "stack-runtime";

function generatedImport(
  moduleName: "env" | "wasi_snapshot_preview1",
  fieldName: string,
  wasmParameters: readonly WasmValueType[],
  wasmResults: readonly WasmValueType[],
  runtimeRole: GeneratedImportRuntimeRole,
) {
  return { moduleName, fieldName, wasmParameters, wasmResults, runtimeRole } as const;
}

function supportExport(
  name: string,
  wasmParameters: readonly WasmValueType[],
  wasmResults: readonly WasmValueType[],
  runtimeRole: SupportExportRuntimeRole,
) {
  return { name, wasmParameters, wasmResults, runtimeRole } as const;
}

/**
 * Canonical design contract for the browser-local Clang-WASM extractor.
 *
 * This resource defines the interface a built module must satisfy. It is not
 * evidence that any Wasm bytes satisfy the interface and grants no build,
 * provenance, Worker-execution, or release authority.
 */
const CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE = {
  schema: "browsergrad.compiler.cpp-cute.browser-runtime-abi-manifest",
  version: { major: 1, minor: 15 },
  manifestId: "bg.cpp.browser-runtime-abi.sha256.ca26cb6a191c943c49b5b3ab4ea8f6587557add274fdeacf1c63e78fedf14b00",
  body: {
    runtimeAbiId: "browsergrad.compiler.cpp-cute.clang-wasm-runtime@1",
    authority: {
      kind: "design-contract-only",
      observedWasm: "detached-verification-required",
      workerExecution: "not-authorized",
      releaseReadiness: "not-authorized",
    },
    wasm: {
      moduleRole: "compiler-extractor-only-user-programs-never-linked-or-executed",
      addressBits: 32,
      cAbiVersion: 65_541,
      cAbiVersionEncoding: "major-shift-left-16-bitwise-or-minor",
      // Browser-visible WebAssembly capabilities required for instantiation.
      requiredFeatures: [
        "bulk-memory",
        "mutable-globals",
        "nontrapping-fptoint",
        "sign-extension",
      ],
      forbiddenFeatures: [
        "atomics",
        "exception-handling",
        "memory64",
        "multi-memory",
        "simd128",
        "threads",
      ],
      featurePolicy: {
        instructionSetBaseline: "webassembly-mvp",
        // Static-inspector vocabulary. `bulk-memory-opt` is an exact opcode
        // subset marker, not a browser feature exposed through the profile.
        allowedExtensions: [
          "bulk-memory",
          "bulk-memory-opt",
          "mutable-globals",
          "nontrapping-fptoint",
          "sign-extension",
        ],
        unlistedExtensions: "forbidden",
        staticOpcodeAndSectionInspection: "required",
        targetFeaturesCrossCheck: "optional-advisory-when-present",
        reviewedSubsets: [
          {
            extension: "bulk-memory-opt",
            exactInstructions: ["memory.copy", "memory.fill"],
            memoryIndices: "zero-only",
            multiMemory: "forbidden",
            ambientCapability: "none",
          },
        ],
      },
      startSection: "forbidden",
      unlistedCExports: "forbidden",
      supportExports: {
        status: "independently-reviewed-hash-pinned",
        functionAllowlistSha256: "54fcf849f006f656162394c9feaeec801af059cbc7b0d61e612bcdebc6abb361",
        functionReview: {
          basis: "pinned-emscripten-runtime-sources-locked-link-flags-and-detached-raw-wasm-inspection",
          emscriptenVersion: "6.0.3",
          emscriptenCommit: "283e2d130132859fde6a4e4c87fd254b38127651",
          visibility: "worker-internal-not-browsergrad-c-api",
          runtimeRoles: [
            { name: "allocator-runtime", exactFunctionCount: 14 },
            { name: "javascript-exception-bridge", exactFunctionCount: 6 },
            { name: "module-initialization", exactFunctionCount: 1 },
            { name: "stack-runtime", exactFunctionCount: 8 },
          ],
        },
        tableReview: {
          basis: "detached-raw-wasm-inspection-and-javascript-exception-dispatch-requirement",
          visibility: "worker-internal-not-browsergrad-c-api",
          exactExportCount: 1,
          runtimeRole: "javascript-exception-dispatch-table",
        },
        exactFunctionAllowlist: [
          supportExport("__wasm_call_ctors", [], [], "module-initialization"),
          supportExport("free", ["i32"], [], "allocator-runtime"),
          supportExport("malloc", ["i32"], ["i32"], "allocator-runtime"),
          supportExport("__libc_malloc", ["i32"], ["i32"], "allocator-runtime"),
          supportExport("calloc", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("__libc_calloc", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("__libc_free", ["i32"], [], "allocator-runtime"),
          supportExport("realloc", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("__libc_realloc", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("reallocarray", ["i32", "i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("aligned_alloc", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("memalign", ["i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("posix_memalign", ["i32", "i32", "i32"], ["i32"], "allocator-runtime"),
          supportExport("valloc", ["i32"], ["i32"], "allocator-runtime"),
          supportExport("pvalloc", ["i32"], ["i32"], "allocator-runtime"),
          supportExport("setThrew", ["i32", "i32"], [], "javascript-exception-bridge"),
          supportExport("_emscripten_tempret_set", ["i32"], [], "javascript-exception-bridge"),
          supportExport("emscripten_stack_init", [], [], "stack-runtime"),
          supportExport("emscripten_stack_get_free", [], ["i32"], "stack-runtime"),
          supportExport("emscripten_stack_get_base", [], ["i32"], "stack-runtime"),
          supportExport("emscripten_stack_get_end", [], ["i32"], "stack-runtime"),
          supportExport("_emscripten_stack_restore", ["i32"], [], "stack-runtime"),
          supportExport("_emscripten_stack_alloc", ["i32"], ["i32"], "stack-runtime"),
          supportExport("emscripten_stack_get_current", [], ["i32"], "stack-runtime"),
          supportExport("__cxa_decrement_exception_refcount", ["i32"], [], "javascript-exception-bridge"),
          supportExport("__cxa_increment_exception_refcount", ["i32"], [], "javascript-exception-bridge"),
          supportExport("__cxa_can_catch", ["i32", "i32", "i32"], ["i32"], "javascript-exception-bridge"),
          supportExport("__cxa_get_exception_ptr", ["i32"], ["i32"], "javascript-exception-bridge"),
          supportExport("__set_stack_limits", ["i32", "i32"], [], "stack-runtime"),
        ],
        exactGlobalAllowlist: [],
        exactTableAllowlist: [
          {
            name: "__indirect_function_table",
            index: 0,
            runtimeRole: "javascript-exception-dispatch-table",
          },
        ],
        unlistedExports: "forbidden",
        observedModuleCannotExtendAllowlist: true,
        releaseConformance: "allowed-only-for-exact-reviewed-support-exports",
      },
      structuralPolicy: {
        status: "independently-reviewed-hash-pinned",
        releaseConformance: "allowed-only-for-exact-reviewed-structural-projection",
        tables: {
          maximumCount: 1,
          allowedElementTypes: ["funcref"],
          imported: "forbidden",
          declaredMaximumRequired: true,
          maximumElementsCeiling: 65_536,
          exactReviewedProjection: [
            { elementType: "funcref", minimum: 15_304, maximum: 15_304 },
          ],
        },
        globals: {
          maximumCount: 4_096,
          allowedValueTypes: ["f32", "f64", "i32", "i64"],
          imported: "forbidden",
          exactReviewedExports: [],
        },
        tags: {
          exactCount: 0,
          imported: "forbidden",
          exported: "forbidden",
        },
        customSections: {
          maximumCount: 4,
          maximumSectionByteLength: 524_288,
          maximumTotalByteLength: 1_048_576,
          duplicateNames: "forbidden",
          exactReviewedNameAllowlist: [],
          unlistedNames: "forbidden",
          explicitlyForbiddenNames: ["dylink.0", "producers", "sourceMappingURL"],
          targetFeatures: {
            sectionName: "target_features",
            status: "independently-reviewed-absent",
            authority: "advisory-only-static-opcode-and-section-inspection-is-authoritative",
            requiredDeclarations: [],
            forbiddenDeclarations: [
              "atomics",
              "exception-handling",
              "memory64",
              "multimemory",
              "simd128",
            ],
            exactRawSectionProjection: [],
          },
        },
      },
      memory: {
        count: 1,
        addressType: "i32",
        imported: false,
        exported: true,
        exportName: "memory",
        sharing: "unshared",
        ownership: "module-instance-owned-by-dedicated-worker",
        pageByteLength: 65_536,
        initialPages: 4_096,
        maximumPages: 16_384,
        growth: "allowed-to-maximum",
        growthLinearStepPages: 1_024,
        stackByteLength: 16_777_216,
        maxCompilerWorkingByteLength: 536_870_912,
        maxInputFrameByteLength: 4_194_304,
        maxResultByteLength: 8_388_608,
      },
    },
    cExports: [
      {
        ordinal: 0,
        cSymbol: "bg_cpp_cute_abi_version",
        wasmExportName: "bg_cpp_cute_abi_version",
        cSignature: "uint32_t bg_cpp_cute_abi_version(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-packed-abi-version",
      },
      {
        ordinal: 1,
        cSymbol: "bg_cpp_cute_alloc",
        wasmExportName: "bg_cpp_cute_alloc",
        cSignature: "uint32_t bg_cpp_cute_alloc(uint32_t byte_length)",
        wasmParameters: ["i32"],
        wasmResults: ["i32"],
        resultSemantics: "u32-input-pointer-zero-on-failure",
      },
      {
        ordinal: 2,
        cSymbol: "bg_cpp_cute_allocator_metrics_pointer",
        wasmExportName: "bg_cpp_cute_allocator_metrics_pointer",
        cSignature: "uint32_t bg_cpp_cute_allocator_metrics_pointer(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-nonzero-stable-read-only-allocator-metrics-record-v1-pointer",
      },
      {
        ordinal: 3,
        cSymbol: "bg_cpp_cute_frontend_work_metrics_pointer",
        wasmExportName: "bg_cpp_cute_frontend_work_metrics_pointer",
        cSignature: "uint32_t bg_cpp_cute_frontend_work_metrics_pointer(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-nonzero-stable-read-only-frontend-work-metrics-record-v1-pointer",
      },
      {
        ordinal: 4,
        cSymbol: "bg_cpp_cute_compile",
        wasmExportName: "bg_cpp_cute_compile",
        cSignature: "int32_t bg_cpp_cute_compile(uint32_t input_pointer, uint32_t input_length)",
        wasmParameters: ["i32", "i32"],
        wasmResults: ["i32"],
        resultSemantics: "typed-compile-status",
      },
      {
        ordinal: 5,
        cSymbol: "bg_cpp_cute_free",
        wasmExportName: "bg_cpp_cute_free",
        cSignature: "void bg_cpp_cute_free(uint32_t pointer, uint32_t byte_length)",
        wasmParameters: ["i32", "i32"],
        wasmResults: [],
        resultSemantics: "void-status-readable-separately",
      },
      {
        ordinal: 6,
        cSymbol: "bg_cpp_cute_reset",
        wasmExportName: "bg_cpp_cute_reset",
        cSignature: "void bg_cpp_cute_reset(void)",
        wasmParameters: [],
        wasmResults: [],
        resultSemantics: "void-infallible-for-live-instance",
      },
      {
        ordinal: 7,
        cSymbol: "bg_cpp_cute_result_length",
        wasmExportName: "bg_cpp_cute_result_length",
        cSignature: "uint32_t bg_cpp_cute_result_length(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-result-length-zero-unless-artifact-ready",
      },
      {
        ordinal: 8,
        cSymbol: "bg_cpp_cute_result_pointer",
        wasmExportName: "bg_cpp_cute_result_pointer",
        cSignature: "uint32_t bg_cpp_cute_result_pointer(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "u32-result-pointer-zero-unless-artifact-ready",
      },
      {
        ordinal: 9,
        cSymbol: "bg_cpp_cute_status",
        wasmExportName: "bg_cpp_cute_status",
        cSignature: "int32_t bg_cpp_cute_status(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics: "current-typed-status-without-state-mutation",
      },
      {
        ordinal: 10,
        cSymbol: "bg_cpp_cute_last_diagnostic_code",
        wasmExportName: "bg_cpp_cute_last_diagnostic_code",
        cSignature: "uint32_t bg_cpp_cute_last_diagnostic_code(void)",
        wasmParameters: [],
        wasmResults: ["i32"],
        resultSemantics:
          "u32-first-source-independent-native-diagnostic-code-zero-when-absent",
      },
    ],
    allocatorMetricsRecord: {
      schema: "browsergrad.compiler.cpp-cute.allocator-metrics-record",
      version: { major: 1, minor: 0 },
      magicAscii: "BGRTMET1",
      magicBytes: [66, 71, 82, 84, 77, 69, 84, 49],
      byteLength: 72,
      alignmentByteLength: 8,
      encoding: "little-endian-fixed-width",
      storage: "module-global-linear-memory-record",
      pointerExport: "bg_cpp_cute_allocator_metrics_pointer",
      pointerContract: {
        resultEncoding: "u32-wasm32-linear-memory-offset",
        zero: "forbidden-for-conforming-live-module-instance",
        stability: "constant-for-module-instance-lifetime",
        completeRange: "must-fit-current-exported-memory",
        mutability: "module-writes-host-read-only",
      },
      snapshotContract: {
        allowedPhases: "between-synchronous-runtime-calls-only",
        hostRead: "copy-exact-record-before-decoding",
        memoryGrowthDuringCopy: "forbidden",
        consistency: "module-calls-are-synchronous-and-memory-is-unshared",
      },
      accounting: {
        unit: "requested-bytes",
        scope: "all-instrumented-module-global-allocator-events",
        interception: {
          exactEntrypoints: [
            "aligned_alloc",
            "calloc",
            "free",
            "__libc_calloc",
            "__libc_free",
            "__libc_malloc",
            "__libc_realloc",
            "malloc",
            "memalign",
            "posix_memalign",
            "pvalloc",
            "realloc",
            "reallocarray",
            "valloc",
          ],
          forbiddenEntrypoints: [
            "bulk_free",
            "independent_calloc",
            "independent_comalloc",
            "realloc_in_place",
          ],
          underlyingBypassEntrypoints: [
            "emscripten_builtin_calloc",
            "emscripten_builtin_free",
            "emscripten_builtin_malloc",
            "emscripten_builtin_memalign",
            "emscripten_builtin_realloc",
          ],
          directBypassReferences:
            "forbidden-outside-BrowserGradCppCuteMetrics.cpp",
          linkClosureProof:
            "pinned-object-and-final-wasm-call-graph-evidence-required",
        },
        requestedByteBasis: "caller-requested-byte-length-before-alignment-or-allocator-rounding",
        currentFormula: "cumulative-allocated-minus-cumulative-freed",
        peakFormula: "maximum-current-live-since-module-instantiation",
        resetPolicy: "counters-persist-and-reset-frees-are-accounted-until-worker-termination",
        allocationCountSemantics: "successful-creation-or-resize-of-one-tracked-live-allocation",
        freeCountSemantics: "successful-release-of-one-tracked-live-allocation",
        failedAllocationCountSemantics: "failed-nonzero-request-that-preserves-all-prior-live-allocations",
        failedInvalidRequestSemantics:
          "invalid-or-size-overflowing-nonzero-request-increments-failed-once-zero-request-does-not",
        zeroByteCreationSemantics:
          "nonnull-result-counts-one-tracked-zero-byte-allocation-null-result-is-permitted-no-op-neither-success-nor-failure",
        freeNullSemantics: "no-op-with-no-counter-change",
        reallocNullPointerSemantics: "same-as-creation-at-requested-size",
        reallocNonzeroSuccessSemantics:
          "allocated-adds-new-requested-size-freed-adds-old-requested-size-success-and-free-counts-each-increment-once-even-in-place",
        reallocNonzeroFailureSemantics:
          "failed-count-increments-once-and-all-live-byte-and-success-free-counters-remain-unchanged",
        reallocZeroSizeSemantics:
          "nonnull-old-pointer-is-released-freed-adds-old-requested-size-free-count-increments-once-result-is-null-and-failure-count-does-not-change",
        excludes: [
          "allocator-metadata-alignment-and-size-class-rounding",
          "javascript-heap-and-worker-host-memory",
          "static-data-and-module-globals",
          "vfs-logical-reservations-not-resident-in-wasm-memory",
          "wasm-stack",
        ],
        invariants: [
          "cumulative-freed-is-less-than-or-equal-to-cumulative-allocated",
          "current-equals-cumulative-allocated-minus-cumulative-freed",
          "free-count-is-less-than-or-equal-to-successful-allocation-count",
          "peak-is-between-current-and-cumulative-allocated-inclusive",
          "peak-cumulative-and-count-counters-are-monotonic-for-module-instance-lifetime",
        ],
        overflowPolicy: "counter-overflow-must-fail-closed-before-wrap-and-forbids-artifact-ready",
      },
      fields: [
        {
          ordinal: 0,
          name: "magic",
          offset: 0,
          byteLength: 8,
          encoding: "ascii[8]",
          semantics: "must-equal-BGRTMET1",
        },
        {
          ordinal: 1,
          name: "version",
          offset: 8,
          byteLength: 4,
          encoding: "u32le",
          semantics: "must-equal-1",
        },
        {
          ordinal: 2,
          name: "byteLength",
          offset: 12,
          byteLength: 4,
          encoding: "u32le",
          semantics: "must-equal-72",
        },
        {
          ordinal: 3,
          name: "currentLiveGlobalRequestedByteLength",
          offset: 16,
          byteLength: 8,
          encoding: "u64le",
          semantics: "current-live-requested-bytes",
        },
        {
          ordinal: 4,
          name: "peakLiveGlobalRequestedByteLength",
          offset: 24,
          byteLength: 8,
          encoding: "u64le",
          semantics: "peak-live-requested-bytes",
        },
        {
          ordinal: 5,
          name: "cumulativeGlobalAllocatedRequestedByteLength",
          offset: 32,
          byteLength: 8,
          encoding: "u64le",
          semantics: "cumulative-successfully-allocated-requested-bytes",
        },
        {
          ordinal: 6,
          name: "cumulativeGlobalFreedRequestedByteLength",
          offset: 40,
          byteLength: 8,
          encoding: "u64le",
          semantics: "cumulative-successfully-freed-requested-bytes",
        },
        {
          ordinal: 7,
          name: "successfulAllocationCount",
          offset: 48,
          byteLength: 8,
          encoding: "u64le",
          semantics: "successful-creation-or-resize-event-count",
        },
        {
          ordinal: 8,
          name: "freeCount",
          offset: 56,
          byteLength: 8,
          encoding: "u64le",
          semantics: "successful-tracked-release-event-count",
        },
        {
          ordinal: 9,
          name: "failedAllocationCount",
          offset: 64,
          byteLength: 8,
          encoding: "u64le",
          semantics: "failed-request-event-count",
        },
      ],
      authority: {
        values: "module-self-reported-local-observation-only",
        producerConformance: "detached-observed-wasm-verification-required",
        workerExecution: "not-authorized-by-record-values",
        lowering: "not-authorized-by-record-values",
      },
    },
    frontendWorkMetricsRecord: {
      schema: "browsergrad.compiler.cpp-cute.frontend-work-metrics-record",
      version: { major: 1, minor: 0 },
      magicAscii: "BGFWK001",
      magicBytes: [66, 71, 70, 87, 75, 48, 48, 49],
      byteLength: 96,
      alignmentByteLength: 8,
      encoding: "little-endian-fixed-width",
      storage: "module-global-linear-memory-record",
      pointerExport: "bg_cpp_cute_frontend_work_metrics_pointer",
      pointerContract: {
        resultEncoding: "u32-wasm32-linear-memory-offset",
        zero: "forbidden-for-conforming-live-module-instance",
        stability: "constant-for-module-instance-lifetime",
        completeRange: "must-fit-current-exported-memory",
        mutability: "module-writes-host-read-only",
      },
      snapshotContract: {
        allowedPhases: "between-synchronous-runtime-calls-only",
        hostRead: "copy-exact-record-before-decoding",
        memoryGrowthDuringCopy: "forbidden",
        consistency: "module-calls-are-synchronous-and-memory-is-unshared",
        readyRead: "after-artifact-ready-compile-before-reset",
        resetRead: "after-reset-to-confirm-idle-generation-preservation",
      },
      lifecycle: {
        idlePhase: 0,
        collectingPhase: 1,
        completePhase: 2,
        failedPhase: 3,
        healthyFlag: 1,
        generationPolicy: "increment-on-admitted-invocation-preserve-across-reset-fail-on-overflow",
        acceptedArtifactPassCount: 2,
        rejectedArtifactPassCount: "one-or-two",
        aggregateScope: "cuda-device-pass-followed-by-cuda-host-pass",
        limitPolicy: "effective-request-profile-ceilings-fail-before-artifact-ready",
        overflowPolicy: "counter-overflow-fails-before-wrap-and-forbids-artifact-ready",
      },
      instrumentation: {
        includeDepth: "maximum-source-manager-include-chain-depth-excluding-main-file",
        macroExpansions: "preprocessor-macro-expands-callback-count",
        preprocessedTokens: "final-expanded-token-watcher-count-excluding-eof",
        astNodes: "recursive-ast-visitor-nonnull-declaration-and-statement-count",
        constexprSteps: "pinned-classic-exprconstant-evalinfo-nextstep-count",
        templateInstantiations: "sema-template-callback-instantiation-record-begin-count",
        templateDepth: "maximum-concurrent-sema-template-instantiation-record-depth",
        constexprInterpreter: "classic-evaluator-required-new-interpreter-disabled",
        patchedSourceIdentity:
          "clang-22.1.8-ExprConstant.cpp-sha256-50c474805f9914a2c54d75f2ddd56d82dc20c128069855155f3c37db26e5bcf9",
      },
      fields: [
        { ordinal: 0, name: "magic", offset: 0, byteLength: 8, encoding: "ascii[8]", semantics: "must-equal-BGFWK001" },
        { ordinal: 1, name: "version", offset: 8, byteLength: 4, encoding: "u32le", semantics: "must-equal-1" },
        { ordinal: 2, name: "byteLength", offset: 12, byteLength: 4, encoding: "u32le", semantics: "must-equal-96" },
        { ordinal: 3, name: "phase", offset: 16, byteLength: 4, encoding: "u32le", semantics: "idle-collecting-complete-or-failed" },
        { ordinal: 4, name: "flags", offset: 20, byteLength: 4, encoding: "u32le", semantics: "one-only-while-record-is-healthy" },
        { ordinal: 5, name: "generation", offset: 24, byteLength: 8, encoding: "u64le", semantics: "monotonic-admitted-invocation-generation" },
        { ordinal: 6, name: "includeDepth", offset: 32, byteLength: 8, encoding: "u64le", semantics: "maximum-include-depth" },
        { ordinal: 7, name: "macroExpansions", offset: 40, byteLength: 8, encoding: "u64le", semantics: "aggregate-macro-expansion-count" },
        { ordinal: 8, name: "preprocessedTokens", offset: 48, byteLength: 8, encoding: "u64le", semantics: "aggregate-final-preprocessed-token-count" },
        { ordinal: 9, name: "astNodes", offset: 56, byteLength: 8, encoding: "u64le", semantics: "aggregate-declaration-and-statement-node-count" },
        { ordinal: 10, name: "constexprSteps", offset: 64, byteLength: 8, encoding: "u64le", semantics: "aggregate-classic-constexpr-evaluator-step-count" },
        { ordinal: 11, name: "templateInstantiations", offset: 72, byteLength: 8, encoding: "u64le", semantics: "aggregate-template-instantiation-record-count" },
        { ordinal: 12, name: "templateDepth", offset: 80, byteLength: 8, encoding: "u64le", semantics: "maximum-template-instantiation-record-depth" },
        { ordinal: 13, name: "completedSemanticPasses", offset: 88, byteLength: 8, encoding: "u64le", semantics: "completed-device-and-host-semantic-pass-count" },
      ],
      authority: {
        values: "module-self-reported-local-observation-only",
        producerConformance: "detached-observed-wasm-verification-required",
        workerExecution: "not-authorized-by-record-values",
        lowering: "not-authorized-by-record-values",
      },
    },
    hostImports: {
      moduleName: "browsergrad_vfs_v1",
      invocation: "synchronous-non-reentrant",
      pointerLifetime: "only-for-import-call-duration",
      unlistedApplicationImports: "forbidden",
      generatedImportAllowlist: {
        policyId: "browsergrad.compiler.cpp-cute.emscripten-generated-imports@1",
        status: "independently-reviewed-hash-pinned",
        allowlistSha256: "20214c6cd9f968c1a298f5f3749a3fc0fcceb7a364d201f96f9d3d546864949d",
        independentReview: {
          basis: "pinned-emscripten-runtime-sources-and-locked-link-flags",
          emscriptenVersion: "6.0.3",
          emscriptenCommit: "283e2d130132859fde6a4e4c87fd254b38127651",
          lockedFlags: [
            "-fexceptions",
            "-sSTACK_OVERFLOW_CHECK=2",
            "-sALLOW_MEMORY_GROWTH=1",
            "-sFILESYSTEM=0",
            "-sINCOMING_MODULE_JS_API=['instantiateWasm','onAbort','print','printErr']",
          ],
          runtimeRoles: [
            { name: "javascript-exception-control-flow", exactFunctionCount: 65, ambientCapability: "none" },
            { name: "bounded-memory-growth", exactFunctionCount: 2, ambientCapability: "none" },
            { name: "stack-overflow-trap", exactFunctionCount: 1, ambientCapability: "none" },
            { name: "stdout-stderr-only", exactFunctionCount: 1, ambientCapability: "caller-provided-output-hooks-only" },
          ],
        },
        exactFunctions: [
          generatedImport("env", "invoke_iii", ["i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_find_matching_catch_2", [], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__resumeException", ["i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_find_matching_catch_6", ["i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiii", ["i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_ii", ["i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vii", ["i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viii", ["i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiii", ["i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_find_matching_catch_3", ["i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_throw", ["i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "llvm_eh_typeid_for", ["i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_begin_catch", ["i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_end_catch", [], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_v", ["i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vijjj", ["i32", "i32", "i64", "i64", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vij", ["i32", "i32", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiii", ["i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vi", ["i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiii", ["i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiii", ["i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiji", ["i32", "i32", "i32", "i64", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_find_matching_catch_4", ["i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_find_matching_catch_5", ["i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiijji", ["i32", "i32", "i32", "i32", "i64", "i64", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vijji", ["i32", "i32", "i64", "i64", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiijiijii", ["i32", "i32", "i32", "i32", "i64", "i32", "i32", "i64", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiijj", ["i32", "i32", "i32", "i32", "i64", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vjj", ["i32", "i64", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiijj", ["i32", "i32", "i32", "i32", "i32", "i64", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiij", ["i32", "i32", "i32", "i32", "i32", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viijj", ["i32", "i32", "i32", "i64", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_i", ["i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("wasi_snapshot_preview1", "fd_write", ["i32", "i32", "i32", "i32"], ["i32"], "stdout-stderr-only"),
          generatedImport("env", "emscripten_get_heap_max", [], ["i32"], "bounded-memory-growth"),
          generatedImport("env", "emscripten_resize_heap", ["i32"], ["i32"], "bounded-memory-growth"),
          generatedImport("env", "_emscripten_throw_longjmp", [], [], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_rethrow", [], [], "javascript-exception-control-flow"),
          generatedImport("env", "__cxa_uncaught_exceptions", [], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiij", ["i32", "i32", "i32", "i32", "i32", "i64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiid", ["i32", "i32", "i32", "i32", "i32", "f64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_jiiii", ["i32", "i32", "i32", "i32", "i32"], ["i64"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_fiii", ["i32", "i32", "i32", "i32"], ["f32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_diii", ["i32", "i32", "i32", "i32"], ["f64"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiiiiiiiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiij", ["i32", "i32", "i32", "i64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiiiiii", ["i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viji", ["i32", "i32", "i64", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iij", ["i32", "i32", "i64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiijiii", ["i32", "i32", "i32", "i64", "i32", "i32", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_jii", ["i32", "i32", "i32"], ["i64"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiiji", ["i32", "i32", "i32", "i32", "i64", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iji", ["i32", "i64", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_vijii", ["i32", "i32", "i64", "i32", "i32"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiji", ["i32", "i32", "i64", "i32"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iid", ["i32", "i32", "f64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_iiiij", ["i32", "i32", "i32", "i32", "i64"], ["i32"], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_viiij", ["i32", "i32", "i32", "i32", "i64"], [], "javascript-exception-control-flow"),
          generatedImport("env", "invoke_jij", ["i32", "i32", "i64"], ["i64"], "javascript-exception-control-flow"),
          generatedImport("env", "__handle_stack_overflow", ["i32"], [], "stack-overflow-trap"),
        ],
        unlistedGeneratedImports: "forbidden",
        observedModuleCannotExtendAllowlist: true,
        capabilityCeiling: "no-clock-random-network-process-or-ambient-filesystem",
        releaseConformance: "allowed-only-for-exact-hash-pinned-signatures",
      },
      memoryAccess: {
        rangeArithmetic: "checked-u32-no-wrap",
        completeRangeValidation: "required-before-first-input-read-or-output-write",
        pathInputSnapshot: "after-complete-range-validation-before-any-output-write",
        inputOutputOverlap: "allowed-only-after-complete-input-snapshot",
        outputOutputOverlap: "forbidden",
        memoryGrowthDuringImport: "forbidden",
        invalidRangeMemoryMutation: "forbidden",
        alignmentByteLength: {
          byteOutput: 1,
          u32Output: 4,
          u64ContainingRecord: 8,
        },
      },
      functions: [
        {
          ordinal: 0,
          fieldName: "bg_vfs_status",
          cSignature: "int32_t bg_vfs_status(uint32_t path_pointer, uint32_t path_length, uint32_t metadata_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-one-32-byte-metadata-record-for-an-existing-file-or-directory",
        },
        {
          ordinal: 1,
          fieldName: "bg_vfs_open",
          cSignature: "int32_t bg_vfs_open(uint32_t path_pointer, uint32_t path_length, uint32_t open_result_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "open-one-existing-file-and-write-one-16-byte-open-result",
        },
        {
          ordinal: 2,
          fieldName: "bg_vfs_read",
          cSignature: "int32_t bg_vfs_read(uint32_t handle, uint32_t offset_low, uint32_t offset_high, uint32_t destination_pointer, uint32_t byte_length)",
          wasmParameters: ["i32", "i32", "i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "copy-the-exact-requested-range-or-copy-nothing",
        },
        {
          ordinal: 3,
          fieldName: "bg_vfs_close",
          cSignature: "int32_t bg_vfs_close(uint32_t handle)",
          wasmParameters: ["i32"],
          wasmResults: ["i32"],
          semantics: "close-one-live-file-handle-exactly-once",
        },
        {
          ordinal: 4,
          fieldName: "bg_vfs_directory_count",
          cSignature: "int32_t bg_vfs_directory_count(uint32_t path_pointer, uint32_t path_length, uint32_t count_pointer)",
          wasmParameters: ["i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-the-stable-immediate-child-count-for-one-directory",
        },
        {
          ordinal: 5,
          fieldName: "bg_vfs_directory_entry",
          cSignature: "int32_t bg_vfs_directory_entry(uint32_t path_pointer, uint32_t path_length, uint32_t index, uint32_t name_pointer, uint32_t name_capacity, uint32_t metadata_pointer)",
          wasmParameters: ["i32", "i32", "i32", "i32", "i32", "i32"],
          wasmResults: ["i32"],
          semantics: "write-one-byte-sorted-child-basename-and-one-32-byte-metadata-record",
        },
      ],
    },
    vfs: {
      storage: "host-backed-lazy-verified-pack-files-only",
      physicalFilesystemFallback: "forbidden",
      networkFallback: "forbidden",
      pathEncoding: "utf8",
      pathForm: "canonical-absolute-forward-slash-no-nul-dot-or-parent-segments",
      maxPathByteLength: 4_096,
      maxIndexedNodes: 262_144,
      maxIndexLogicalByteLength: 134_217_728,
      indexLogicalByteAccounting:
        "sum-per-node-metadata-record-plus-canonical-path-utf8-plus-immediate-basename-utf8",
      maxAggregateLiveOpenByteLength: 402_653_184,
      liveOpenByteAccounting:
        "logical-full-file-per-live-handle-reservation-not-wasm-residency",
      maxLiveFileHandles: 65_536,
      maxSessionCalls: 1_000_000,
      directoryOrder: "strict-ascending-utf8-byte-order",
      metadataRecord: {
        byteLength: 32,
        fields: [
          { name: "kind", offset: 0, encoding: "u32le", values: ["file=1", "directory=2"] },
          { name: "nameByteLength", offset: 4, encoding: "u32le", values: ["zero-for-status"] },
          { name: "fileByteLength", offset: 8, encoding: "u64le", values: ["zero-for-directory"] },
          { name: "uniqueIdDevice", offset: 16, encoding: "u64le", values: ["session-stable"] },
          { name: "uniqueIdFile", offset: 24, encoding: "u64le", values: ["session-stable"] },
        ],
      },
      openResultRecord: {
        byteLength: 16,
        fields: [
          { name: "handle", offset: 0, encoding: "u32le" },
          { name: "reserved", offset: 4, encoding: "u32le-zero" },
          { name: "fileByteLength", offset: 8, encoding: "u64le" },
        ],
      },
      statuses: [
        { code: 0, name: "ok" },
        { code: 1, name: "not-found" },
        { code: 2, name: "not-directory" },
        { code: 3, name: "is-directory" },
        { code: 4, name: "invalid-path" },
        { code: 5, name: "buffer-too-small" },
        { code: 6, name: "out-of-range" },
        { code: 7, name: "invalid-handle" },
        { code: 8, name: "resource-limit" },
        { code: 9, name: "session-closed" },
        { code: 10, name: "internal-error" },
      ],
      failureAtomicity: "nonzero-status-writes-no-output-except-required-name-length-in-metadata",
      noAmbientInputs: ["clock", "current-directory", "environment", "locale", "random", "timezone"],
    },
    inputFrame: {
      encoding: "little-endian-binary-header-with-canonical-json-regions",
      magicAscii: "BGCCABI1",
      major: 1,
      minor: 0,
      headerByteLength: 64,
      alignmentByteLength: 8,
      maxFrameByteLength: 4_194_304,
      fields: [
        { name: "magic", offset: 0, encoding: "ascii[8]" },
        { name: "major", offset: 8, encoding: "u16le" },
        { name: "minor", offset: 10, encoding: "u16le" },
        { name: "headerByteLength", offset: 12, encoding: "u32le" },
        { name: "totalByteLength", offset: 16, encoding: "u32le" },
        { name: "flags", offset: 20, encoding: "u32le-zero" },
        { name: "profileOffset", offset: 24, encoding: "u32le-must-equal-64" },
        { name: "profileByteLength", offset: 28, encoding: "u32le" },
        { name: "requestOffset", offset: 32, encoding: "u32le-aligned-8" },
        { name: "requestByteLength", offset: 36, encoding: "u32le" },
        { name: "reserved", offset: 40, encoding: "zero[24]" },
      ],
      profileRegion: "exact-canonical-prepared-frontend-profile-json",
      requestRegion: "exact-canonical-producer-neutral-frontend-request-json",
      regionOrder: "profile-then-zero-padding-then-request-then-zero-padding",
      totalLengthRule: "aligned-request-end-equals-total-byte-length-and-all-regions-are-in-bounds",
      decodeLimits: {
        maxDocumentByteLength: 4_194_304,
        maxNestingDepth: 128,
        maxNodeCount: 1_000_000,
        maxCumulativeStringByteLength: 4_194_304,
        maxArrayElementCount: 65_536,
        maxObjectPropertyCount: 512,
        maxScratchByteLength: 16_777_216,
        accounting: {
          documentBytes: "per-region-before-utf8-decode",
          nestingNodesAndStrings:
            "per-region-root-depth-one-strings-include-object-keys-and-values",
          containers: "per-array-or-object",
          scratchBytes:
            "peak-live-decoder-owned-bytes-per-compile-session-excluding-input-frame-vfs-and-producer-state",
        },
        numberPolicy:
          "safe-integer-lexemes-only-no-negative-zero-fraction-or-exponent",
        canonicalValidationPolicy:
          "byte-exact-browsergrad-canonical-json-validation-per-region-rejecting-duplicate-keys",
      },
      sourceBytes: "out-of-band-through-worker-owned-vfs-session",
      compileReadRule: "synchronous-complete-frame-validation-before-vfs-access",
    },
    compileStatuses: [
      { code: 0, name: "artifact-ready", retry: "reset-then-new-invocation" },
      { code: 1, name: "idle", retry: "allocate-input" },
      { code: 2, name: "input-allocated", retry: "compile-or-free" },
      { code: 100, name: "invalid-state", retry: "reset-required" },
      { code: 101, name: "invalid-argument", retry: "reset-required" },
      { code: 102, name: "invalid-frame", retry: "reset-required" },
      { code: 103, name: "abi-mismatch", retry: "module-must-not-be-reused" },
      { code: 104, name: "vfs-error", retry: "reset-required" },
      { code: 105, name: "resource-limit", retry: "reset-required" },
      { code: 106, name: "internal-error", retry: "module-must-not-be-reused" },
    ],
    nativeDiagnostics: {
      getterExport: "bg_cpp_cute_last_diagnostic_code",
      firstCause: "first-nonzero-code-per-runtime-generation",
      zero: "no-native-diagnostic-reported",
      reset:
        "reset-clears-unless-sticky-allocator-integrity-failure-reports-again",
      authority: "diagnostic-only-never-artifact-or-lowering-authority",
      codes: [
        { code: 0, name: "none" },
        { code: 1, name: "producer-policy-install-failure" },
        { code: 2, name: "producer-vfs-failure" },
        { code: 3, name: "producer-diagnostic-capture-limit" },
        { code: 4, name: "producer-frontend-work-limit" },
        { code: 5, name: "producer-invocation-failure" },
        { code: 6, name: "producer-exception" },
        { code: 7, name: "artifact-decode-internal" },
        { code: 8, name: "artifact-plan-internal" },
        { code: 9, name: "artifact-sink-bind-internal" },
        { code: 10, name: "artifact-frontend-begin-internal" },
        { code: 11, name: "artifact-frontend-complete-internal" },
        { code: 12, name: "artifact-producer-internal" },
        { code: 13, name: "artifact-writer-internal" },
        { code: 14, name: "runtime-post-compile-phase-invariant" },
        { code: 15, name: "runtime-artifact-ready-invariant" },
        { code: 16, name: "runtime-terminal-status-invalid" },
        { code: 17, name: "allocator-invalid-table-shape" },
        { code: 18, name: "allocator-table-probe-exhausted" },
        { code: 19, name: "allocator-table-rehash-failure" },
        { code: 20, name: "allocator-table-insert-failure" },
        { code: 21, name: "allocator-table-erase-failure" },
        { code: 22, name: "allocator-creation-counter-overflow" },
        { code: 23, name: "allocator-release-invariant-failure" },
        { code: 24, name: "allocator-reallocation-invariant-failure" },
        { code: 25, name: "allocator-failed-counter-overflow" },
        { code: 26, name: "allocator-reentrant-hook" },
        { code: 27, name: "allocator-duplicate-builtin-pointer" },
        { code: 28, name: "allocator-untracked-free" },
        { code: 29, name: "allocator-untracked-reallocation" },
        { code: 30, name: "allocator-replacement-pointer-collision" },
        { code: 31, name: "allocator-invalid-metrics-pointer" },
        { code: 32, name: "allocator-unknown-failure" },
        { code: 33, name: "producer-vfs-invalid-limits" },
        { code: 34, name: "producer-vfs-invalid-successful-read" },
        { code: 35, name: "producer-vfs-inconsistent-successful-read" },
        { code: 36, name: "producer-vfs-opened-file-limit" },
        { code: 37, name: "producer-vfs-invalid-include-edge" },
        { code: 38, name: "producer-vfs-include-edge-limit" },
        { code: 39, name: "producer-vfs-invalid-include-source-range" },
        { code: 40, name: "producer-vfs-invalid-include-resolved-path" },
        { code: 41, name: "producer-vfs-invalid-include-including-path" },
        { code: 42, name: "producer-vfs-invalid-include-spelling" },
        { code: 43, name: "producer-vfs-invalid-include-offsets" },
        { code: 44, name: "producer-vfs-invalid-include-source-ordinal" },
        { code: 45, name: "producer-vfs-invalid-forced-include-shape" },
        { code: 46, name: "producer-vfs-invalid-include-kind" },
        { code: 47, name: "artifact-writer-payload-resource-limit" },
        { code: 48, name: "artifact-writer-serialization-resource-limit" },
        { code: 49, name: "artifact-writer-result-allocation-limit" },
        { code: 50, name: "artifact-writer-allocation-failure" },
      ],
    },
    lifecycle: {
      initialState: "idle",
      states: ["idle", "input-allocated", "compiling-internal", "artifact-ready", "failed"],
      rules: [
        "alloc-is-valid-only-in-idle-with-byte-length-from-1-through-max-input-frame-byte-length",
        "only-one-live-input-allocation-is-permitted",
        "compile-is-valid-only-for-the-exact-live-input-pointer-and-length",
        "compile-is-synchronous-and-not-reentrant",
        "compile-status-zero-means-one-complete-canonical-artifact-is-ready-even-when-that-artifact-rejects-source",
        "infrastructure-failure-never-masquerades-as-a-rejected-source-artifact",
        "free-is-valid-only-for-the-exact-live-input-pointer-and-length-and-never-for-result-memory",
        "free-after-success-preserves-the-artifact-ready-result",
        "result-getters-return-zero-unless-state-is-artifact-ready",
        "result-bytes-are-immutable-until-reset",
        "reset-releases-input-result-and-module-side-vfs-state-and-returns-to-idle",
        "after-abi-mismatch-or-internal-error-the-worker-discards-the-module-instance-after-reading-status-and-first-native-diagnostic-code",
        "wasm-trap-abort-or-out-of-memory-is-a-worker-infrastructure-failure-with-no-readable-status-guarantee",
      ],
    },
    result: {
      schema: "browsergrad.compiler.cpp-cute.frontend-artifact",
      version: { major: 3, minor: 0 },
      encoding: "canonical-json-bytes",
      maximumByteLength: 8_388_608,
      ownership: "module-owned-worker-must-copy-before-reset",
      lifetime: "from-artifact-ready-until-reset-or-worker-termination",
      emptyResult: "forbidden-when-status-is-artifact-ready",
    },
    cancellation: {
      mechanism: "terminate-dedicated-worker",
      cooperativeImport: "forbidden",
      reason: "synchronous-unshared-wasm-cannot-service-worker-messages-during-compile",
      effect: "invalidates-module-memory-input-result-vfs-handles-and-session-authority",
      workerReuseAfterCancellation: "forbidden",
    },
  },
} as const satisfies JsonObject;

export type CppCuteBrowserRuntimeAbiManifestV1Resource =
  typeof CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE;

export const CPP_CUTE_BROWSER_RUNTIME_ABI_V1_RESOURCE = deepFreezeJson(
  CPP_CUTE_BROWSER_RUNTIME_ABI_V1_VALUE,
) as unknown as CppCuteBrowserRuntimeAbiManifestV1Resource;
