export const FRAMEWORK_CUMSUM_CONFORMANCE = Object.freeze({
  schema: "browsergrad.framework.cumsum-conformance.v1",
  valid: {
    inputShape: [2, 3],
    inputValues: [[1, 2, 3], [4, -1, 2]],
    axis: 1,
    values: [[1, 3, 6], [4, 3, 5]],
    alternateAxisValues: [[1, 2, 3], [5, 1, 5]],
    gradient: [[3, 2, 1], [3, 2, 1]],
    cotangent: [[1, 2, 4], [3, 5, 7]],
    cotangentGradient: [[7, 6, 4], [15, 12, 7]],
  },
  dtypeCases: [
    {
      id: "float16-default-preserves",
      sourceDtype: "float16",
      values: [0.5, 1, -0.25],
      dtype: null,
      expectedDtype: "float16",
      expectedValues: [0.5, 1.5, 1.25],
    },
    {
      id: "bool-default-promotes-int64",
      sourceDtype: "bool",
      values: [true, false, true],
      dtype: null,
      expectedDtype: "int64",
      expectedValues: [1, 1, 2],
    },
    {
      id: "int8-default-promotes-int64",
      sourceDtype: "int8",
      values: [120, 120, -1],
      dtype: null,
      expectedDtype: "int64",
      expectedValues: [120, 240, 239],
    },
    {
      id: "int32-default-prevents-overflow",
      sourceDtype: "int32",
      values: [2147483647, 1],
      dtype: null,
      expectedDtype: "int64",
      expectedValues: [2147483647, 2147483648],
    },
    {
      id: "explicit-int32",
      sourceDtype: "int64",
      values: [1, 2, 3],
      dtype: "int32",
      expectedDtype: "int32",
      expectedValues: [1, 3, 6],
    },
    {
      id: "explicit-double-alias",
      sourceDtype: "float32",
      values: [0.5, 0.25, 1],
      dtype: "double",
      expectedDtype: "float64",
      expectedValues: [0.5, 0.75, 1.75],
    },
    {
      id: "explicit-bool",
      sourceDtype: "int32",
      values: [0, 1, 1],
      dtype: "bool",
      expectedDtype: "bool",
      expectedValues: [false, true, true],
    },
  ],
  empty: {
    shape: [2, 0, 3],
    axis: 1,
    values: [[], []],
    dtype: "float32",
  },
  typedGradient: {
    sourceDtype: "float64",
    outputDtype: "float32",
    values: [1, 2, 3],
    cotangent: [1, 2, 4],
    expected: [7, 6, 4],
    expectedDtype: "float64",
  },
  autograd: {
    floatToIntegralRequiresGrad: false,
    integralToFloatRequiresGrad: false,
  },
  invalid: [
    { id: "scalar-input" },
    { id: "bool-axis" },
    { id: "float-axis" },
    { id: "low-axis" },
    { id: "high-axis" },
    { id: "hostile-axis" },
    { id: "list-dtype" },
    { id: "hostile-dtype" },
    { id: "unknown-dtype" },
    { id: "unsupported-source-dtype" },
    { id: "out-mutation" },
  ],
  onnx: {
    axis: 1,
    axisDtype: 7,
    outputDtype: 7,
    castTo: 7,
    exclusive: 0,
    reverse: 0,
  },
} as const);
