export const FRAMEWORK_VAR_CONFORMANCE = Object.freeze({
  schema: "browsergrad.framework-var-conformance@1",
  valid: Object.freeze({
    inputShape: Object.freeze([2, 3]),
    inputValues: Object.freeze([1, 2, 3, 4, 5, 6]),
    axis: 1,
    negativeAxis: -1,
    correction: 1,
    outputShape: Object.freeze([2]),
    outputValues: Object.freeze([1, 1]),
    keepdimsShape: Object.freeze([2, 1]),
    keepdimsValues: Object.freeze([Object.freeze([1]), Object.freeze([1])]),
    fullValue: 3.5,
    sourceGradient: Object.freeze([-1, 0, 1, -1, 0, 1]),
  }),
  dtypeCases: Object.freeze([
    Object.freeze({ dtype: "float16", expectedDtype: "float16" }),
    Object.freeze({ dtype: "float32", expectedDtype: "float32" }),
    Object.freeze({ dtype: "float64", expectedDtype: "float64" }),
  ]),
  invalid: Object.freeze([
    Object.freeze({
      id: "non-integral-axis",
      kind: "axis",
      value: 0.5,
      message: "axis must be None, an integer scalar, or a plain tuple/list",
    }),
    Object.freeze({
      id: "boolean-axis",
      kind: "axis",
      value: true,
      message: "axis must be None, an integer scalar, or a plain tuple/list",
    }),
    Object.freeze({
      id: "empty-axes",
      kind: "axis",
      value: Object.freeze([]),
      message: "axis sequence must be non-empty",
    }),
    Object.freeze({
      id: "duplicate-axes",
      kind: "axis",
      value: Object.freeze([0, -2]),
      message: "axes must be unique after normalization",
    }),
    Object.freeze({
      id: "axis-out-of-range",
      kind: "axis",
      value: 2,
      message: "axis 2 out of range for rank 2",
    }),
    Object.freeze({
      id: "both-axis-aliases",
      kind: "both-axis-aliases",
      value: 0,
      message: "specify only one of axis or dim",
    }),
    Object.freeze({
      id: "non-boolean-keepdims",
      kind: "keepdims",
      value: 1,
      message: "keepdim and keepdims must be booleans",
    }),
    Object.freeze({
      id: "non-integral-correction",
      kind: "correction",
      value: 0.5,
      message: "correction must be a built-in or NumPy integer scalar",
    }),
    Object.freeze({
      id: "boolean-correction",
      kind: "correction",
      value: true,
      message: "correction must be a built-in or NumPy integer scalar",
    }),
    Object.freeze({
      id: "correction-out-of-range",
      kind: "correction",
      value: 2147483648,
      message: "correction must be in [-2147483648, 2147483647]",
    }),
    Object.freeze({
      id: "non-boolean-unbiased",
      kind: "unbiased",
      value: 1,
      message: "unbiased must be a boolean",
    }),
    Object.freeze({
      id: "both-correction-aliases",
      kind: "both-correction-aliases",
      value: 0,
      message: "specify only one of correction or unbiased",
    }),
    Object.freeze({
      id: "integer-input",
      kind: "dtype",
      value: "int32",
      message: "floating dtypes only",
    }),
    Object.freeze({
      id: "boolean-input",
      kind: "dtype",
      value: "bool",
      message: "floating dtypes only",
    }),
    Object.freeze({
      id: "scalar-axis",
      kind: "scalar",
      value: 0,
      message: "axis 0 out of range for rank 0",
    }),
  ]),
});
