export const FRAMEWORK_EINSUM_CONFORMANCE = {
  schema: "browsergrad.framework.einsum-conformance.v1",
  matmul: {
    equation: " ij , jk -> ik ",
    canonicalEquation: "ij,jk->ik",
    implicitEquation: "ij,jk",
    leftShape: [2, 3],
    leftValues: [1, 2, 3, 4, 5, 6],
    rightShape: [3, 2],
    rightValues: [7, 8, 9, 10, 11, 12],
    outputShape: [2, 2],
    outputValues: [58, 64, 139, 154],
    leftGradient: [15, 19, 23, 15, 19, 23],
    rightGradient: [5, 5, 7, 7, 9, 9],
  },
  threeOperand: {
    equation: "ab,bc,cd->ad",
    shapes: [[1, 2], [2, 2], [2, 1]],
    values: [[1, 2], [3, 4, 5, 6], [7, 8]],
    outputShape: [1, 1],
    outputValues: [219],
    gradients: [[53, 83], [7, 8, 14, 16], [13, 16]],
  },
  broadcast: {
    equation: "bi,bi->b",
    shapes: [[1, 3], [2, 3]],
    values: [[1, 2, 3], [4, 5, 6, 7, 8, 9]],
    outputValues: [32, 50],
    gradients: [[11, 13, 15], [1, 2, 3, 1, 2, 3]],
  },
  ellipsis: {
    equation: "...i,...i->...",
    shapes: [[2, 3], [1, 2, 3]],
    values: [[1, 2, 3, 4, 5, 6], [1, 1, 1, 2, 2, 2]],
    outputShape: [1, 2],
    outputValues: [6, 30],
    reductionEquation: "...i->i",
    reductionInputShape: [2, 3],
    reductionInputValues: [1, 2, 3, 4, 5, 6],
    reductionOutputValues: [5, 7, 9],
    reductionGradient: [1, 1, 1, 1, 1, 1],
  },
  diagonal: {
    inputShape: [3, 3],
    inputValues: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    equation: "ii->i",
    outputValues: [1, 5, 9],
    traceEquation: "ii->",
    traceValue: 15,
    gradient: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  scalar: {
    equation: ",->",
    values: [2, 3],
    outputValue: 6,
    gradients: [3, 2],
  },
  uppercaseImplicit: {
    equation: "aA",
    canonicalEquation: "aA->Aa",
    inputShape: [2, 3],
    inputValues: [1, 2, 3, 4, 5, 6],
    outputShape: [3, 2],
    outputValues: [1, 4, 2, 5, 3, 6],
  },
  emptyBroadcast: {
    equation: "i,i->i",
    shapes: [[0], [1]],
    outputShape: [0],
    outputValues: [],
  },
  dtypeCases: [
    { leftDtype: "float16", rightDtype: "float16", expectedDtype: "float16" },
    { leftDtype: "int32", rightDtype: "float32", expectedDtype: "float32" },
    { leftDtype: "bool", rightDtype: "bool", expectedDtype: "bool" },
  ],
  invalid: [
    { id: "term-count", equation: "i,j->i", shapes: [[2]], message: "input terms for 1 operands" },
    { id: "invalid-character", equation: "i$->i", shapes: [[2]], message: "invalid subscript" },
    { id: "malformed-ellipsis", equation: ".i->i", shapes: [[2]], message: "invalid subscript" },
    { id: "repeated-extent", equation: "ii->i", shapes: [[2, 3]], message: "unequal extents" },
    { id: "broadcast", equation: "i,i->i", shapes: [[2], [3]], message: "incompatible broadcast extents" },
    { id: "missing-output", equation: "i->j", shapes: [[2]], message: "does not appear in any operand" },
    { id: "duplicate-output", equation: "i->ii", shapes: [[2]], message: "appears more than once" },
    { id: "rank-mismatch", equation: "ij->i", shapes: [[2]], message: "subscripts for rank 1" },
  ],
} as const;
