export const FRAMEWORK_PAD_CONFORMANCE = Object.freeze({
  schema: "browsergrad.framework.constant-pad-conformance.v1",
  valid: {
    inputValues: [[1, 2], [3, 4]],
    pad: [1, 2, 0, 1],
    value: -1,
    canonicalPadWidth: [[0, 1], [1, 2]],
    expectedShape: [3, 5],
    expectedValues: [
      [-1, 1, 2, -1, -1],
      [-1, 3, 4, -1, -1],
      [-1, -1, -1, -1, -1],
    ],
    cotangent: [
      [1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10],
      [11, 12, 13, 14, 15],
    ],
    expectedGradient: [[2, 3], [7, 8]],
  },
  dtypeCases: [
    { dtype: "float16", value: 1.5, expectedValue: 1.5 },
    { dtype: "int64", value: -2, expectedValue: -2 },
    { dtype: "bool", value: true, expectedValue: true },
    { dtype: "uint8", value: 7, expectedValue: 7 },
  ],
  zeroPad: {
    pad: [],
    expectedShape: [2, 2],
    expectedValues: [[1, 2], [3, 4]],
  },
  empty: {
    inputShape: [0, 2],
    pad: [1, 1, 1, 0],
    value: 5,
    expectedShape: [1, 4],
    expectedValues: [[5, 5, 5, 5]],
  },
  vmap: {
    inputValues: [[1, 2], [3, 4]],
    pad: [1, 1],
    expectedValues: [[0, 1, 2, 0], [0, 3, 4, 0]],
    expectedPadWidth: [[0, 0], [1, 1]],
  },
  onnx: {
    opTypes: ["Pad", "Identity"],
    inputCount: 3,
    pads: [0, 1, 1, 2],
    value: -1,
    outputDtype: 1,
  },
  invalid: [
    { id: "non-tensor" },
    { id: "non-sequence" },
    { id: "odd-length" },
    { id: "too-many-dimensions" },
    { id: "bool-padding" },
    { id: "float-padding" },
    { id: "negative-padding" },
    { id: "hostile-padding" },
    { id: "mode-type" },
    { id: "unsupported-mode" },
    { id: "hostile-mode" },
    { id: "hostile-value" },
    { id: "unsupported-dtype" },
    { id: "fractional-integer-fill" },
    { id: "overflowing-fill" },
    { id: "nonfinite-floating-fill" },
    { id: "zero-size-oversized-axis" },
  ],
} as const);
