export const VARIADIC_TENSOR_DTYPE_CASES = Object.freeze([
  {
    id: "float32-dominates-int64",
    dtypes: ["float32", "int64"],
    values: [[0.5, 1.5], [2, 3]],
    expectedDtype: "float32",
    expectedValues: [0.5, 1.5, 2, 3],
    expectedStackValues: [[0.5, 1.5], [2, 3]],
  },
  {
    id: "float16-dominates-int64",
    dtypes: ["float16", "int64"],
    values: [[0.5], [2]],
    expectedDtype: "float16",
    expectedValues: [0.5, 2],
    expectedStackValues: [[0.5], [2]],
  },
  {
    id: "uint8-and-int8-promote-int16",
    dtypes: ["uint8", "int8"],
    values: [[255], [-1]],
    expectedDtype: "int16",
    expectedValues: [255, -1],
    expectedStackValues: [[255], [-1]],
  },
  {
    id: "bool-and-uint8-promote-uint8",
    dtypes: ["bool", "uint8"],
    values: [[true, false], [2, 3]],
    expectedDtype: "uint8",
    expectedValues: [1, 0, 2, 3],
    expectedStackValues: [[1, 0], [2, 3]],
  },
  {
    id: "float64-dominates-float16",
    dtypes: ["float64", "float16"],
    values: [[0.25], [0.5]],
    expectedDtype: "float64",
    expectedValues: [0.25, 0.5],
    expectedStackValues: [[0.25], [0.5]],
  },
  {
    id: "bool-preserves",
    dtypes: ["bool", "bool"],
    values: [[true, false], [false, true]],
    expectedDtype: "bool",
    expectedValues: [true, false, false, true],
    expectedStackValues: [[true, false], [false, true]],
  },
] as const);

export const FRAMEWORK_CAT_CONFORMANCE = Object.freeze({
  schema: "browsergrad.framework.cat-conformance.v1",
  valid: {
    axis: 1,
    inputShapes: [[2, 2], [2, 1], [2, 0]],
    inputValues: [
      [[1, 2], [3, 4]],
      [[5], [6]],
      [[], []],
    ],
    expectedShape: [2, 3],
    expectedValues: [[1, 2, 5], [3, 4, 6]],
    cotangent: [[1, 2, 4], [8, 16, 32]],
    expectedGradients: [
      [[1, 2], [8, 16]],
      [[4], [32]],
      [[], []],
    ],
  },
  dtypeCases: VARIADIC_TENSOR_DTYPE_CASES,
  legacyEmpty: {
    axis: 1,
    emptyDtype: "float64",
    matrixDtype: "float32",
    matrixValues: [[1, 2], [3, 4]],
    expectedShape: [2, 2],
    expectedDtype: "float64",
    expectedValues: [[1, 2], [3, 4]],
    expectedEmptyGradient: [],
    expectedMatrixGradient: [[1, 1], [1, 1]],
  },
  allEmpty: {
    axis: 0,
    dtypes: ["float32", "int64"],
    expectedShape: [0],
    expectedDtype: "float32",
    expectedValues: [],
  },
  mixedGradient: {
    floatingValues: [1, 2],
    integralValues: [3],
    expectedFloatingGradient: [1, 1],
    expectedIntegralGradientPresent: false,
  },
  vmap: {
    mappedValues: [[1, 2], [3, 4]],
    capturedValues: [9],
    expectedValues: [[1, 2, 9], [3, 4, 9]],
    expectedArg: { axis: 1 },
  },
  onnx: {
    axis: 0,
    outputDtype: 1,
    castTo: 1,
    opTypes: ["Cast", "Concat", "Identity"],
    concatInputCount: 2,
  },
  invalid: [
    { id: "non-sequence" },
    { id: "empty-sequence" },
    { id: "non-tensor" },
    { id: "scalar-input" },
    { id: "bool-axis" },
    { id: "float-axis" },
    { id: "low-axis" },
    { id: "high-axis" },
    { id: "hostile-axis" },
    { id: "hostile-sequence" },
    { id: "shape-mismatch" },
    { id: "rank-mismatch" },
    { id: "unsupported-dtype" },
    { id: "out-mutation" },
  ],
} as const);
