export const FRAMEWORK_SMOOTH_L1_LOSS_CONFORMANCE = {
  schema: "browsergrad.framework.smooth-l1-loss-conformance.v1",
  base: {
    shape: [2, 2],
    beta: 1,
    inputValues: [0, -0.5, 2, 0],
    targetValues: [0, 0, 0, 1],
    upstreamValues: [1, 2, 3, 4],
    noneValues: [0, 0.125, 1.5, 0.5],
    sumValue: 2.125,
    meanValue: 0.53125,
    noneInputGradient: [0, -1, 3, -4],
    noneTargetGradient: [0, 1, -3, 4],
    meanInputGradient: [0, -0.125, 0.25, -0.25],
    meanTargetGradient: [0, 0.125, -0.25, 0.25],
  },
  betaProfiles: [
    { beta: 0.5, sumValue: 2.75 },
    { beta: 0, sumValue: 3.5 },
  ],
  zeroBetaGradients: {
    input: [0, -1, 1, -1],
    target: [0, 1, -1, 1],
  },
  mixedDtypes: [
    { inputDtype: "float16", targetDtype: "float16", outputDtype: "float16" },
    { inputDtype: "float16", targetDtype: "float32", outputDtype: "float32" },
    { inputDtype: "float32", targetDtype: "float64", outputDtype: "float64" },
  ],
  scalar: {
    beta: 2,
    inputValue: -3,
    targetValue: 0,
    outputValue: 2,
    inputGradient: -1,
    targetGradient: 1,
  },
  empty: {
    shape: [0, 3],
    noneShape: [0, 3],
    sumValue: 0,
  },
  invalid: [
    { id: "input-type", message: "input must be" },
    { id: "shape", message: "must equal target shape" },
    { id: "reduction", message: "must be 'none', 'sum', or 'mean'" },
    { id: "reduction-type", message: "reduction must be a string" },
    { id: "input-dtype", message: "input 0 dtype" },
    { id: "target-dtype", message: "input 1 dtype" },
    { id: "target-type", message: "target must be" },
    { id: "beta-negative", message: "beta must be non-negative" },
    { id: "beta-nan", message: "beta must be finite" },
    { id: "beta-infinite", message: "beta must be finite" },
    { id: "beta-type", message: "beta must be an exact real scalar" },
    { id: "beta-bool", message: "beta must be an exact real scalar" },
    { id: "beta-underflow", message: "not representable" },
    { id: "beta-overflow", message: "not representable" },
  ],
  limits: {
    workExtent: 1 << 24,
    workspaceExtent: 1 << 23,
  },
} as const;
