export const FRAMEWORK_SCATTER_CONFORMANCE = Object.freeze({
  schema: "browsergrad.framework-scatter-conformance@1",
  valid: Object.freeze({
    targetShape: Object.freeze([2, 4]),
    targetValues: Object.freeze([10, 20, 30, 40, 50, 60, 70, 80]),
    indexShape: Object.freeze([2, 2]),
    indexValues: Object.freeze([3, 0, 1, 2]),
    sourceValues: Object.freeze([1, 2, 3, 4]),
    axis: 1,
    negativeAxis: -1,
    outputShape: Object.freeze([2, 4]),
    outputValues: Object.freeze([2, 20, 30, 1, 50, 3, 4, 80]),
    scalarSource: -5,
    scalarOutputValues: Object.freeze([-5, 20, 30, -5, 50, -5, -5, 80]),
    targetGradient: Object.freeze([0, 1, 1, 0, 1, 0, 0, 1]),
    sourceGradient: Object.freeze([1, 1, 1, 1]),
  }),
  dtypeCases: Object.freeze([
    Object.freeze({ dtype: "float16", expectedDtype: "float16" }),
    Object.freeze({ dtype: "int32", expectedDtype: "int32" }),
    Object.freeze({ dtype: "bool", expectedDtype: "bool" }),
  ]),
  invalid: Object.freeze([
    Object.freeze({
      id: "non-integral-axis",
      kind: "axis",
      value: 0.5,
      message: "dim must be a built-in or NumPy integer scalar",
    }),
    Object.freeze({
      id: "boolean-axis",
      kind: "axis",
      value: true,
      message: "dim must be a built-in or NumPy integer scalar",
    }),
    Object.freeze({
      id: "axis-out-of-range",
      kind: "axis",
      value: 2,
      message: "dim 2 out of range for rank 2",
    }),
    Object.freeze({
      id: "index-int32",
      kind: "index-dtype",
      value: "int32",
      message: "index dtype must be",
    }),
    Object.freeze({
      id: "index-rank-mismatch",
      kind: "index-shape",
      value: Object.freeze([2]),
      message: "target and index must have the same nonzero rank",
    }),
    Object.freeze({
      id: "oversized-non-scatter-dimension",
      kind: "index-shape",
      value: Object.freeze([3, 1]),
      message: "index extent 3 exceeds target extent 2 at non-scatter dimension 0",
    }),
    Object.freeze({
      id: "oversized-selected-dimension",
      kind: "index-shape",
      value: Object.freeze([2, 5]),
      message: "index extent 5 exceeds target extent 4 at selected dimension 1",
    }),
    Object.freeze({
      id: "non-tensor-index",
      kind: "non-tensor-index",
      value: Object.freeze([[0, 1], [1, 0]]),
      message: "index must be a Tensor",
    }),
    Object.freeze({
      id: "source-shape-mismatch",
      kind: "source-shape",
      value: Object.freeze([2, 1]),
      message: "source must be a canonical scalar or have exactly the index shape",
    }),
    Object.freeze({
      id: "source-dtype-mismatch",
      kind: "source-dtype",
      value: "float64",
      message: "source dtype must equal the target dtype",
    }),
    Object.freeze({
      id: "negative-index",
      kind: "index-values",
      value: Object.freeze([-1, 0, 1, 2]),
      message: "index values must be in [0, 4)",
    }),
    Object.freeze({
      id: "index-out-of-range",
      kind: "index-values",
      value: Object.freeze([4, 0, 1, 2]),
      message: "index values must be in [0, 4)",
    }),
    Object.freeze({
      id: "duplicate-destination",
      kind: "index-values",
      value: Object.freeze([1, 1, 0, 2]),
      message: "duplicate destination indices",
    }),
    Object.freeze({
      id: "deprecated-reduction",
      kind: "reduce",
      value: "add",
      message: "reduce= is outside typed overwrite scatter",
    }),
  ]),
});
