export const FRAMEWORK_NLL_LOSS_CONFORMANCE = {
  schema: "browsergrad.framework.nll-loss-conformance.v1",
  base: {
    inputShape: [2, 3, 2],
    targetShape: [2, 2],
    input: [
      -0.1, -1.0,
      -0.2, -0.3,
      -2.0, -0.4,
      -0.5, -0.6,
      -0.7, -0.8,
      -0.9, -1.1,
    ],
    target: [0, 2, 1, -100],
    weight: [0.5, 2.0, 1.5],
    upstream: [1, 2, 3, 4],
    ignoreIndex: -100,
    weightedNone: [0.05, 0.6, 1.4, 0],
    weightedSum: 2.05,
    weightedMean: 0.5125,
    unweightedMean: 0.4,
    weightedNoneGradient: [
      -0.5, 0,
      0, 0,
      0, -3,
      0, 0,
      -6, 0,
      0, 0,
    ],
    weightedMeanGradient: [
      -0.125, 0,
      0, 0,
      0, -0.375,
      0, 0,
      -0.5, 0,
      0, 0,
    ],
  },
  unbatched: {
    input: [-0.1, -0.2, -0.3],
    target: 2,
    value: 0.3,
    gradient: [0, 0, -1],
  },
  empty: {
    zeroBatchInputShape: [0, 3, 2],
    zeroBatchTargetShape: [0, 2],
    zeroSupportInputShape: [2, 3, 0],
    zeroSupportTargetShape: [2, 0],
  },
  mixedDtypes: [
    { dtype: "float16" },
    { dtype: "float32" },
    { dtype: "float64" },
  ],
  invalid: [
    { id: "input-type", message: "input must be" },
    { id: "target-type", message: "target must be" },
    { id: "target-shape", message: "target shape" },
    { id: "session", message: "same session" },
    { id: "input-rank", message: "no user input dimension" },
    { id: "reduction", message: "reduction must be 'none', 'sum', or 'mean'" },
    { id: "reduction-type", message: "reduction must be a string" },
    { id: "input-dtype", message: "input dtype" },
    { id: "target-dtype", message: "target dtype" },
    { id: "weight-type", message: "weight must be" },
    { id: "weight-shape", message: "weight shape" },
    { id: "weight-dtype", message: "weight dtype" },
    { id: "weight-grad", message: "must not require grad" },
    { id: "weight-session", message: "same session" },
    { id: "ignore-type", message: "ignore_index must be an exact integer" },
    { id: "ignore-range", message: "ignore_index must fit signed int64" },
    { id: "target-range", message: "target values must be in" },
    { id: "size-average-type", message: "size_average must be an exact bool or None" },
    { id: "reduce-type", message: "reduce must be an exact bool or None" },
  ],
  limits: {
    workExtent: 8_400_000,
    workspaceExtent: 8_200_000,
  },
} as const;
