export {
  CudaLiteCompilerError,
  type CompiledCudaLiteKernel,
  type CompiledKernelInput,
  type CompileCudaLiteOptions,
  type CudaLiteAnalysis,
  type CudaLiteAnalyzeOptions,
  type CudaLiteAssignmentExpression,
  type CudaLiteBinaryExpression,
  type CudaLiteCastExpression,
  type CudaLiteCallExpression,
  type CudaLiteConditionalExpression,
  type CudaLiteContinueStatement,
  type CudaLiteCooperativeGroupDecl,
  type CudaLiteCooperativeGroupKind,
  type CudaLiteDeviceFunction,
  type CudaLiteDeviceGlobal,
  type CudaLiteDiagnostic,
  type CudaLiteDim3Decl,
  type CudaLiteExpression,
  type CudaLiteFeatureName,
  type CudaLiteFeatureOptions,
  type CudaLiteForStatement,
  type CudaLiteGlobalConstant,
  type CudaLiteIdentifier,
  type CudaLiteIfStatement,
  type CudaLiteIndexExpression,
  type CudaLiteKernel,
  type CudaLiteKernelLaunchStatement,
  type CudaLiteMemberExpression,
  type CudaLiteModule,
  type CudaLiteNumberLiteral,
  type CudaLiteParam,
  type CudaLiteReturnStatement,
  type CudaLiteScalarType,
  type CudaLiteStatement,
  type CudaLiteStringLiteral,
  type CudaLiteTexture2D,
  type CudaLiteUnaryExpression,
  type CudaLiteUpdateExpression,
  type CudaLiteVarDecl,
  type DiagnosticSeverity,
  type KernelLaunch,
  type KernelMemoryAccess,
  type KernelThreadTrace,
  type ReferenceKernelResult,
  type ReferenceTraceMode,
  type RunCompiledKernelReferenceOptions,
  type SourceSpan,
} from "./types.js";

export { parseCudaLite } from "./parser.js";
export type { ParsedCudaLiteModule } from "./parser.js";
export type { AnalyzedCudaLiteModule } from "./analyzer.js";
export type {
  CompilerPhase,
  Parsed,
  Analyzed,
  TypedSemantic,
  CanonicalIr,
  RuntimeLoweredIr,
} from "./compiler_phases.js";
export type {
  SemanticFunctionId,
  SemanticMemoryId,
  SemanticSymbolId,
} from "./semantic_ids.js";
export {
  createSemanticEnvironment,
  type SemanticEnvironment,
} from "./semantic_environment.js";
export {
  collectSemanticPoolAllocations,
  createCudaLiteSemanticModel,
  lowerSemanticModelToKernelIr,
  type CudaLiteSemanticFunction,
  type CudaLiteSemanticLaunchableEntry,
  type CudaLiteSemanticModel,
  type CudaLiteSemanticSymbol,
  type SemanticAddressSpace,
  type SemanticDeviceLaunch,
  type SemanticExpression,
  type SemanticKernelIrModule,
  type SemanticKernelIrOperation,
  type SemanticMemoryRef,
  type SemanticPoolRef,
} from "./semantic_ir.js";
export {
  validateSemanticKernelIr,
  verifySemanticKernelIr,
  type SemanticIrVerificationIssue,
  type VerifiedSemanticKernelIr,
} from "./semantic_ir_verifier.js";
export {
  typeCheckSemanticKernelIr,
  checkSemanticKernelIrTypes,
  type SemanticTypeIssue,
  type TypeCheckedSemanticKernelIr,
} from "./semantic_type_check.js";
export {
  legalizeSemanticKernelIrForWgsl,
  checkSemanticKernelIrWgslLegalization,
  type WgslLegalizationIssue,
  type WgslLegalizedSemanticKernelIr,
} from "./wgsl_legalization.js";
export {
  createTypedWgslIdentifier,
  createTypedWgslLiteral,
  createTypedWgslZero,
  createTypedWgslCall,
  createTypedWgslMemberAccess,
  createTypedWgslQualifiedAccess,
  createTypedWgslIndexAccess,
  createTypedWgslMemoryRead,
  createTypedWgslScalarMemoryRead,
  createTypedWgslMemoryPathRead,
  createTypedWgslIndexedPlace,
  createTypedWgslLocalPlace,
  createTypedWgslDereferencedIndexedPlace,
  createTypedWgslDereferencedPlace,
  createTypedWgslPointerIndexRead,
  createTypedWgslBindingAddress,
  createTypedWgslAddressOf,
  createTypedWgslPlaceRead,
  createTypedWgslTextureLoad,
  createTypedWgslTextureDescriptorRead,
  createTypedWgslCubemapTextureLoad,
  createTypedWgslAtomicCall,
  createTypedWgslBitcast,
  createTypedWgslConstructor,
  isWgslVectorType,
  convertTypedWgslExpression,
  legalizeTypedWgslBoolToNumeric,
  emitTypedWgslBinary,
  emitTypedWgslSelect,
  emitTypedWgslUnary,
  type TypedWgslExpression,
  type TypedWgslPlace,
  type WgslAtomicBuiltin,
  type WgslPointerType,
  type WgslBinaryOperator,
  type WgslUnaryOperator,
  type WgslExpressionType,
  type WgslVectorType,
} from "./typed_wgsl_expression.js";
export {
  createTypedWgslReturnStatement,
  createTypedWgslLocalAssignmentStatement,
  createTypedWgslPlaceAssignmentStatement,
  createTypedWgslCallStatement,
  createTypedWgslVariableStatement,
  type TypedWgslStatement,
} from "./typed_wgsl_statement.js";
export { lowerSemanticCudaRuntime } from "./semantic_runtime_lowering.js";
export {
  projectSemanticHostRuntimeToGpuIr,
  type ProjectedSemanticGpuIr,
} from "./semantic_gpu_projection.js";
export { analyzeCudaLite } from "./analyzer.js";
export {
  classifyCudaCompatibilityFamily,
  createCudaLoweringPlan,
  describeCudaDiagnostic,
  getCudaFeatureRegistry,
  type CudaCompatibilityFamily,
  type CudaFeatureRecord,
  type CudaLoweringKind,
  type CudaLoweringPlan,
} from "./compatibility.js";
export { formatCudaLiteDiagnostics } from "./diagnostics.js";
export {
  compileCudaLiteOptionsFromKernelFeatures,
  cudaLiteFeatureOptionsFromKernelFeatures,
  type CudaLiteKernelFeatureSource,
} from "./features.js";
export {
  createCudaLaunchValidationDiagnostics,
  validateCudaKernelLaunch,
} from "./launch.js";
export {
  createCudaHostDynamicLaunchPlan,
  type CudaHostDynamicLaunch,
  type CudaHostDynamicLaunchBlocker,
  type CudaHostDynamicLaunchBlockerCode,
  type CudaHostDynamicLaunchPlan,
  type CudaHostDynamicLaunchPlanOptions,
} from "./dynamic_launch.js";
export {
  createCudaPeerCopyPlan,
  createCudaRuntimeCopyPlan,
  type CudaPeerCopyBlocker,
  type CudaPeerCopyBlockerCode,
  type CudaPeerCopyOperation,
  type CudaPeerCopyPlan,
  type CudaRuntimeCopyBlocker,
  type CudaRuntimeCopyBlockerCode,
  type CudaRuntimeCopyOperation,
  type CudaRuntimeCopyPlan,
} from "./peer_copy.js";
export {
  createCudaGridSyncPhasePlan,
  createCudaRuntimePlan,
  type CudaGridSyncPhasePlan,
  type CudaRuntimeOperation,
  type CudaRuntimeOperationKind,
  type CudaRuntimePlan,
} from "./runtime_plan.js";
export {
  createCudaWebGpuExecutionPlan,
  normalizeCudaWebGpuReadbackNames,
  normalizeCudaWebGpuReadback,
  summarizeCudaWebGpuExecutionPlan,
  type CudaWebGpuExecutionBlocker,
  type CudaWebGpuExecutionBlockerKind,
  type CudaWebGpuExecutionMode,
  type CudaWebGpuExecutionPlan,
  type CudaWebGpuExecutionPlanKind,
  type CudaWebGpuExecutionPlanOptions,
  type CudaWebGpuExecutionStatus,
} from "./webgpu_orchestration.js";
export {
  canEmitSemanticKernelIrWgsl,
  emitSemanticKernelIrWgsl,
  semanticKernelIrWgslPreflightBlocker,
  semanticKernelIrWgslPreflightFailure,
  type EmitSemanticKernelIrWgslOptions,
  type SemanticKernelIrWgslOutput,
  type SemanticKernelIrWgslPreflightFailure,
} from "./semantic_wgsl.js";
export {
  createCudaLiteCompileCacheKey,
  createCudaLiteLayoutBindingCompileCacheKey,
  createCudaLiteViewCopyBindingCompileCacheKey,
  createCudaLiteCompilerCache,
  type CudaLiteCompilerCache,
  type CudaLiteCompilerCacheOptions,
  type CudaLiteCompilerCacheStats,
} from "./cache.js";
export {
  CUDA_LITE_LAYOUT_BINDING_PROFILE,
  CudaLiteLayoutBindingError,
  prepareCudaLiteLayoutBindings,
  type CudaLiteLayoutBindingErrorCode,
  type CudaLiteLayoutBindingRequest,
  type PrepareCudaLiteLayoutBindingsOptions,
  type PreparedCudaLiteLayoutBinding,
  type PreparedCudaLiteLayoutBindings,
} from "./semantic_layout_bindings.js";
export {
  CUDA_LITE_VIEW_COPY_BINDING_PROFILE,
  CudaLiteViewCopyBindingError,
  prepareCudaLiteViewCopyBinding,
  type CudaLiteViewCopyBindingErrorCode,
  type PrepareCudaLiteViewCopyBindingOptions,
  type PrepareCudaLiteViewCopyBindingRequest,
  type PreparedCudaLiteViewCopyBinding,
} from "./semantic_view_copy_bindings.js";
export {
  mapCudaLiteDiagnosticToSourceProvenance,
  prepareCudaLiteCompilationUnit,
  type CudaLiteAppliedSourceTransform,
  type CudaLiteCompilationUnitPosition,
  type CudaLiteCompilationUnitSegment,
  type CudaLiteProvenanceDiagnosticSegment,
  type CudaLiteSourceFragment,
  type CudaLiteSourceProvenance,
  type CudaLiteSourceProvenancePosition,
  type PrepareCudaLiteCompilationUnitOptions,
  type PreparedCudaLiteCompilationUnit,
} from "./source_preparation.js";
export {
  compileCudaLiteKernelForWebGpu,
  compileCudaLiteKernel,
  compileCudaLiteKernelWithLayoutBindings,
  compileCudaLiteKernelWithViewCopyBinding,
  cudaLiteWebGpuCompileOptions,
  prepareCompiledKernelWebGpu,
  canRunCompiledKernelSemanticReference,
  runCompiledKernelReference,
  runCompiledKernelSemanticReference,
  runCompiledKernelWebGpu,
  type CompiledCudaLiteLayoutBoundKernel,
  type CompiledCudaLiteViewCopyBoundKernel,
  type CompiledKernelWebGpuExecutionOptions,
  type PreparedCompiledKernelWebGpu,
  type PreparedCompiledKernelWebGpuRunOptions,
  type PrepareCompiledKernelWebGpuOptions,
} from "./runner.js";
export {
  CppCuteBrowserLayoutAuthorizationError,
  authorizeCppCuteBrowserLayoutArtifact,
  unwrapAuthorizedCppCuteBrowserLayoutArtifact,
  type AuthorizeCppCuteBrowserLayoutArtifactOptions,
  type AuthorizedCppCuteBrowserLayoutArtifact,
  type AuthorizedCppCuteBrowserLayoutArtifactRecord,
  type CppCuteBrowserLayoutAuthorizationErrorCode,
} from "./cpp_cute_browser_layout_authorization.js";
export {
  CppCuteViewCopyLoweringError,
  lowerAuthorizedCppCuteViewCopyEntry,
  type CppCuteViewCopyLoweringErrorCode,
  type LowerAuthorizedCppCuteViewCopyEntryOptions,
  type LowerAuthorizedCppCuteViewCopyEntryRequest,
} from "./cpp_cute_view_copy_lowering.js";
export {
  CppCuteBrowserViewCopyCandidateError,
  prepareObservedCppCuteBrowserViewCopyCandidate,
  unwrapObservedCppCuteBrowserViewCopyCandidate,
  type CppCuteBrowserViewCopyCandidateErrorCode,
  type ObservedCppCuteBrowserViewCopyCandidate,
  type ObservedCppCuteBrowserViewCopyCandidateRecord,
  type PrepareObservedCppCuteBrowserViewCopyCandidateOptions,
  type PrepareObservedCppCuteBrowserViewCopyCandidateRequest,
} from "./cpp_cute_browser_view_copy_candidate.js";
export {
  CppCuteBrowserViewCopyAuthorizationError,
  authorizeCppCuteBrowserViewCopyArtifact,
  unwrapAuthorizedCppCuteBrowserViewCopyArtifact,
  type AuthorizeCppCuteBrowserViewCopyArtifactOptions,
  type AuthorizedCppCuteBrowserViewCopyArtifact,
  type AuthorizedCppCuteBrowserViewCopyArtifactRecord,
  type CppCuteBrowserViewCopyAuthorizationErrorCode,
} from "./cpp_cute_browser_view_copy_authorization.js";
