export function semanticMathCallArity(name: string): number {
  return name === "clock" ||
    name === "clock64" ||
    name === "__builtin_inff" ||
    name === "__builtin_huge_valf"
    ? 0
    : name === "fmin" ||
    name === "fminf" ||
    name === "min" ||
    name === "fmax" ||
    name === "fmaxf" ||
    name === "max" ||
    name === "pow" ||
    name === "powf" ||
    name === "__powf" ||
    name === "__fdividef" ||
    name === "fdividef" ||
    name === "__fadd_rn" ||
    name === "__fsub_rn" ||
    name === "__fmul_rn" ||
    name === "__fdiv_rn" ||
    name === "__hadd_rn" ||
    name === "__hadd_sat" ||
    name === "__hsub" ||
    name === "__hsub_rn" ||
    name === "__hsub_sat" ||
    name === "__hmul" ||
    name === "__hmul_rn" ||
    name === "__hmul_sat" ||
    name === "__hdiv" ||
    name === "__hdiv_rn" ||
    name === "__hmin" ||
    name === "__hmax" ||
    name === "__hmin_nan" ||
    name === "__hmax_nan" ||
    name === "__heq" ||
    name === "__hne" ||
    name === "__hgt" ||
    name === "__hge" ||
    name === "__hlt" ||
    name === "__hle" ||
    name === "__hequ" ||
    name === "__hneu" ||
    name === "__hgtu" ||
    name === "__hgeu" ||
    name === "__hltu" ||
    name === "__hleu" ||
    name === "__nv_cvt_fp8_to_halfraw" ||
    name === "copysign" ||
    name === "copysignf" ||
    name === "isgreater" ||
    name === "isgreaterequal" ||
    name === "isless" ||
    name === "islessequal" ||
    name === "islessgreater" ||
    name === "isunordered" ||
    name === "div_ceil" ||
    name === "ceil_div" ||
    name === "ldexp" ||
    name === "ldexpf" ||
    name === "scalbn" ||
    name === "scalbnf" ||
    name === "scalbln" ||
    name === "scalblnf" ||
    name === "fmod" ||
    name === "fmodf" ||
    name === "remainder" ||
    name === "remainderf" ||
    name === "fdim" ||
    name === "fdimf" ||
    name === "nextafter" ||
    name === "nextafterf" ||
    name === "nexttoward" ||
    name === "nexttowardf" ||
    name === "hypot" ||
    name === "hypotf" ||
    name === "rhypot" ||
    name === "rhypotf" ||
    name === "__bg_remquo_quotient" ||
    name === "__bg_remquo_remainder" ||
    name === "atan2" ||
    name === "atan2f" ||
    name === "__mul24" ||
    name === "__umul24" ||
    name === "__mulhi" ||
    name === "__umulhi" ||
    name === "__mul64hi" ||
    name === "__umul64hi" ||
    name === "__rhadd" ||
    name === "__uhadd" ||
    name === "__urhadd" ||
    name === "__hadd" ||
    name === "__vadd2" ||
    name === "__vsub2" ||
    name === "__vaddss2" ||
    name === "__vsubss2" ||
    name === "__vaddus2" ||
    name === "__vsubus2" ||
    name === "__vabsdiffu2" ||
    name === "__vabsdiffs2" ||
    name === "__vsads2" ||
    name === "__vsadu2" ||
    name === "__vhaddu2" ||
    name === "__vavgs2" ||
    name === "__vavgu2" ||
    name === "__vminu2" ||
    name === "__vmaxu2" ||
    name === "__vmins2" ||
    name === "__vmaxs2" ||
    name === "__vcmpeq2" ||
    name === "__vcmpne2" ||
    name === "__vcmpges2" ||
    name === "__vcmpgeu2" ||
    name === "__vcmpgts2" ||
    name === "__vcmpgtu2" ||
    name === "__vcmples2" ||
    name === "__vcmpleu2" ||
    name === "__vcmplts2" ||
    name === "__vcmpltu2" ||
    name === "__vseteq2" ||
    name === "__vsetne2" ||
    name === "__vsetges2" ||
    name === "__vsetgeu2" ||
    name === "__vsetgts2" ||
    name === "__vsetgtu2" ||
    name === "__vsetles2" ||
    name === "__vsetleu2" ||
    name === "__vsetlts2" ||
    name === "__vsetltu2" ||
    name === "__vadd4" ||
    name === "__vsub4" ||
    name === "__vaddss4" ||
    name === "__vsubss4" ||
    name === "__vaddus4" ||
    name === "__vsubus4" ||
    name === "__vabsdiffu4" ||
    name === "__vabsdiffs4" ||
    name === "__vsads4" ||
    name === "__vsadu4" ||
    name === "__vhaddu4" ||
    name === "__vavgs4" ||
    name === "__vavgu4" ||
    name === "__vminu4" ||
    name === "__vmaxu4" ||
    name === "__vmins4" ||
    name === "__vmaxs4" ||
    name === "__vcmpeq4" ||
    name === "__vcmpne4" ||
    name === "__vcmpges4" ||
    name === "__vcmpgeu4" ||
    name === "__vcmpgts4" ||
    name === "__vcmpgtu4" ||
    name === "__vcmples4" ||
    name === "__vcmpleu4" ||
    name === "__vcmplts4" ||
    name === "__vcmpltu4" ||
    name === "__vseteq4" ||
    name === "__vsetne4" ||
    name === "__vsetges4" ||
    name === "__vsetgeu4" ||
    name === "__vsetgts4" ||
    name === "__vsetgtu4" ||
    name === "__vsetles4" ||
    name === "__vsetleu4" ||
    name === "__vsetlts4" ||
    name === "__vsetltu4" ||
    name === "__vimax_s32_relu" ||
    name === "__vimin_s32_relu" ||
    name === "__vimax_s16x2_relu" ||
    name === "__vimin_s16x2_relu" ||
    name === "__vibmax_s32" ||
    name === "__vibmin_s32" ||
    name === "__vibmax_u32" ||
    name === "__vibmin_u32" ||
    name === "__vibmax_s16x2" ||
    name === "__vibmin_s16x2" ||
    name === "__vibmax_u16x2" ||
    name === "__vibmin_u16x2" ||
    name === "__bg_i16_lane" ||
    name === "__bg_u16_lane" ||
    name === "UMUL" ||
    name === "umin"
    ? 2
    : name === "__hisnan" ||
    name === "__hisinf"
    ? 1
    : name === "fma" ||
      name === "fmaf" ||
      name === "__fmaf_rn" ||
      name === "__hfma" ||
      name === "__hfma_rn" ||
      name === "__hfma_sat" ||
      name === "__hfma_relu" ||
      name === "lerp" ||
      name === "norm3df" ||
      name === "rnorm3df" ||
      name === "__byte_perm" ||
      name === "__funnelshift_l" ||
      name === "__funnelshift_lc" ||
      name === "__funnelshift_r" ||
      name === "__funnelshift_rc" ||
      name === "__sad" ||
      name === "__usad" ||
      name === "__usad4" ||
      name === "__viaddmax_s32" ||
      name === "__viaddmax_s32_relu" ||
      name === "__viaddmin_s32" ||
      name === "__viaddmin_s32_relu" ||
      name === "__viaddmax_u32" ||
      name === "__viaddmin_u32" ||
      name === "__viaddmax_s16x2" ||
      name === "__viaddmax_s16x2_relu" ||
      name === "__viaddmin_s16x2" ||
      name === "__viaddmin_s16x2_relu" ||
      name === "__viaddmax_u16x2" ||
      name === "__viaddmin_u16x2" ||
      name === "__vimax3_s32" ||
      name === "__vimax3_s32_relu" ||
      name === "__vimin3_s32" ||
      name === "__vimin3_s32_relu" ||
      name === "__vimax3_u32" ||
      name === "__vimin3_u32" ||
      name === "__vimax3_s16x2" ||
      name === "__vimax3_s16x2_relu" ||
      name === "__vimin3_s16x2" ||
      name === "__vimin3_s16x2_relu" ||
      name === "__vimax3_u16x2" ||
      name === "__vimin3_u16x2" ||
      name === "__dp4a" ||
      name === "__dp2a_lo" ||
      name === "__dp2a_hi" ||
      name === "__nv_cvt_float_to_fp8" ||
      name === "IMAD" ||
      name === "UMAD"
    ? 3
    : name === "norm4df" ||
      name === "rnorm4df"
    ? 4
    : 1;
}
