export function emitSemanticNumericHelpers(): readonly string[] {
  return [
    "fn bg_semantic_isnan_f32(value: f32) -> bool {",
    "  return (bitcast<u32>(value) & 0x7fffffffu) > 0x7f800000u;",
    "}",
    "fn bg_semantic_isnan_vec2_f32(value: vec2<f32>) -> vec2<bool> {",
    "  return (bitcast<vec2<u32>>(value) & vec2<u32>(0x7fffffffu)) > vec2<u32>(0x7f800000u);",
    "}",
    "fn bg_semantic_isinf_f32(value: f32) -> bool {",
    "  return (bitcast<u32>(value) & 0x7fffffffu) == 0x7f800000u;",
    "}",
    "fn bg_semantic_round_even_f32(value: f32) -> f32 {",
    "  if (value != value || abs(value) > 3.4028234663852886e38) { return value; }",
    "  let lower = floor(value);",
    "  let diff = value - lower;",
    "  if (diff < 0.5) { return lower; }",
    "  if (diff > 0.5) { return lower + 1.0; }",
    "  let half_lower = floor(lower * 0.5);",
    "  return select(lower + 1.0, lower, (half_lower * 2.0) == lower);",
    "}",
    "fn bg_semantic_remainder_f32(x: f32, y: f32) -> f32 {",
    "  return x - bg_semantic_round_even_f32(x / y) * y;",
    "}",
    "fn bg_semantic_logb_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  let runtime_zero = select(0.0, value, false);",
    "  if (value == 0.0) { return -1.0 / runtime_zero; }",
    "  if (abs(value) > 3.4028234663852886e38) { return 1.0 / runtime_zero; }",
    "  return floor(log2(abs(value)));",
    "}",
    "fn bg_semantic_ilogb_i32(value: f32) -> i32 {",
    "  if (value != value || abs(value) > 3.4028234663852886e38) { return 2147483647; }",
    "  if (value == 0.0) { return -2147483648; }",
    "  return i32(floor(log2(abs(value))));",
    "}",
    "fn bg_semantic_nextafter_f32(x: f32, y: f32) -> f32 {",
    "  if (x != x || y != y) { return x + y; }",
    "  if (x == y) { return y; }",
    "  if (x == 0.0) {",
    "    return bitcast<f32>(select(0x00000001u, 0x80000001u, (bitcast<u32>(y) & 0x80000000u) != 0u));",
    "  }",
    "  var bits = bitcast<u32>(x);",
    "  if (x > 0.0) {",
    "    bits = select(bits - 1u, bits + 1u, x < y);",
    "  } else {",
    "    bits = select(bits + 1u, bits - 1u, x < y);",
    "  }",
    "  return bitcast<f32>(bits);",
    "}",
    "fn bg_semantic_runtime_nan_f32(value: f32) -> f32 {",
    "  let runtime_zero = select(0.0, value, false);",
    "  return runtime_zero / runtime_zero;",
    "}",
    "fn bg_semantic_runtime_inf_f32(value: f32) -> f32 {",
    "  let runtime_zero = select(0.0, value, false);",
    "  return 1.0 / runtime_zero;",
    "}",
    "fn bg_semantic_erf_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  if (abs(value) > 3.4028234663852886e38) { return select(-1.0, 1.0, value > 0.0); }",
    "  let magnitude = abs(value);",
    "  let t = 1.0 / (1.0 + 0.3275911 * magnitude);",
    "  let polynomial = (((((1.061405429 * t) - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t;",
    "  return select(-1.0, 1.0, value >= 0.0) * (1.0 - (polynomial * exp(-(magnitude * magnitude))));",
    "}",
    "fn bg_semantic_erfinv_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  if (value <= -1.0) { return select(bg_semantic_runtime_nan_f32(value), -bg_semantic_runtime_inf_f32(value), value == -1.0); }",
    "  if (value >= 1.0) { return select(bg_semantic_runtime_nan_f32(value), bg_semantic_runtime_inf_f32(value), value == 1.0); }",
    "  if (value == 0.0) { return 0.0; }",
    "  let a = 0.147;",
    "  let l = log(1.0 - value * value);",
    "  let first = (2.0 / (3.141592653589793 * a)) + (l * 0.5);",
    "  var y = select(-1.0, 1.0, value >= 0.0) * sqrt(sqrt(first * first - l / a) - first);",
    "  y -= (bg_semantic_erf_f32(y) - value) / (1.1283791670955126 * exp(-(y * y)));",
    "  y -= (bg_semantic_erf_f32(y) - value) / (1.1283791670955126 * exp(-(y * y)));",
    "  return y;",
    "}",
    "fn bg_semantic_normcdfinv_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  if (value <= 0.0) { return select(bg_semantic_runtime_nan_f32(value), -bg_semantic_runtime_inf_f32(value), value == 0.0); }",
    "  if (value >= 1.0) { return select(bg_semantic_runtime_nan_f32(value), bg_semantic_runtime_inf_f32(value), value == 1.0); }",
    "  return 1.4142135623730951 * bg_semantic_erfinv_f32(2.0 * value - 1.0);",
    "}",
    "fn bg_semantic_tgamma_core_f32(value: f32) -> f32 {",
    "  let z = value - 1.0;",
    "  var x = 0.9999999999998099;",
    "  x += 676.5203681218851 / (z + 1.0);",
    "  x += -1259.1392167224028 / (z + 2.0);",
    "  x += 771.3234287776531 / (z + 3.0);",
    "  x += -176.6150291621406 / (z + 4.0);",
    "  x += 12.507343278686905 / (z + 5.0);",
    "  x += -0.13857109526572012 / (z + 6.0);",
    "  x += 0.000009984369578019572 / (z + 7.0);",
    "  x += 0.00000015056327351493116 / (z + 8.0);",
    "  let t = z + 7.5;",
    "  return 2.5066282746310002 * pow(t, z + 0.5) * exp(-t) * x;",
    "}",
    "fn bg_semantic_lgamma_core_f32(value: f32) -> f32 {",
    "  let z = value - 1.0;",
    "  var x = 0.9999999999998099;",
    "  x += 676.5203681218851 / (z + 1.0);",
    "  x += -1259.1392167224028 / (z + 2.0);",
    "  x += 771.3234287776531 / (z + 3.0);",
    "  x += -176.6150291621406 / (z + 4.0);",
    "  x += 12.507343278686905 / (z + 5.0);",
    "  x += -0.13857109526572012 / (z + 6.0);",
    "  x += 0.000009984369578019572 / (z + 7.0);",
    "  x += 0.00000015056327351493116 / (z + 8.0);",
    "  let t = z + 7.5;",
    "  return 0.9189385332046727 + (z + 0.5) * log(t) - t + log(abs(x));",
    "}",
    "fn bg_semantic_tgamma_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  if (abs(value) > 3.4028234663852886e38) { return select(value, bg_semantic_runtime_nan_f32(value), value < 0.0); }",
    "  if (value <= 0.0 && value == trunc(value)) { return bg_semantic_runtime_nan_f32(value); }",
    "  if (value < 0.5) {",
    "    return 3.141592653589793 / (sin(3.141592653589793 * value) * bg_semantic_tgamma_core_f32(1.0 - value));",
    "  }",
    "  return bg_semantic_tgamma_core_f32(value);",
    "}",
    "fn bg_semantic_lgamma_f32(value: f32) -> f32 {",
    "  if (value != value) { return value; }",
    "  if (abs(value) > 3.4028234663852886e38) { return bg_semantic_runtime_inf_f32(value); }",
    "  if (value <= 0.0 && value == trunc(value)) { return bg_semantic_runtime_inf_f32(value); }",
    "  if (value < 0.5) {",
    "    return log(3.141592653589793) - log(abs(sin(3.141592653589793 * value))) - bg_semantic_lgamma_core_f32(1.0 - value);",
    "  }",
    "  return bg_semantic_lgamma_core_f32(value);",
    "}",
    "fn bg_semantic_umulhi_u32(x: u32, y: u32) -> u32 {",
    "  let x_lo = x & 0xffffu;",
    "  let x_hi = x >> 16u;",
    "  let y_lo = y & 0xffffu;",
    "  let y_hi = y >> 16u;",
    "  let lo_carry = (((x_lo * y_lo) >> 16u) + ((x_lo * y_hi) & 0xffffu) + ((x_hi * y_lo) & 0xffffu)) >> 16u;",
    "  return (x_hi * y_hi) + ((x_lo * y_hi) >> 16u) + ((x_hi * y_lo) >> 16u) + lo_carry;",
    "}",
    "fn bg_semantic_mulhi_i32(x: i32, y: i32) -> i32 {",
    "  return i32(bg_semantic_umulhi_u32(u32(x), u32(y))) - select(0, y, x < 0) - select(0, x, y < 0);",
    "}",
    "fn bg_semantic_byte_perm_u32(x: u32, y: u32, selector: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var lane = 0u; lane < 4u; lane = lane + 1u) {",
    "    let source = (selector >> (lane * 4u)) & 0x7u;",
    "    let input = select(x, y, source >= 4u);",
    "    let byte = (input >> ((source & 0x3u) * 8u)) & 0xffu;",
    "    out = out | (byte << (lane * 8u));",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_funnelshift_l_u32(lo: u32, hi: u32, shift: u32) -> u32 {",
    "  let s = shift & 31u;",
    "  if (s == 0u) { return lo; }",
    "  return (lo << s) | (hi >> (32u - s));",
    "}",
    "fn bg_semantic_funnelshift_lc_u32(lo: u32, hi: u32, shift: u32) -> u32 {",
    "  let s = min(shift, 32u);",
    "  if (s == 0u) { return lo; }",
    "  if (s == 32u) { return hi; }",
    "  return (lo << s) | (hi >> (32u - s));",
    "}",
    "fn bg_semantic_funnelshift_r_u32(lo: u32, hi: u32, shift: u32) -> u32 {",
    "  let s = shift & 31u;",
    "  if (s == 0u) { return lo; }",
    "  return (lo >> s) | (hi << (32u - s));",
    "}",
    "fn bg_semantic_funnelshift_rc_u32(lo: u32, hi: u32, shift: u32) -> u32 {",
    "  let s = min(shift, 32u);",
    "  if (s == 0u) { return lo; }",
    "  if (s == 32u) { return hi; }",
    "  return (lo >> s) | (hi << (32u - s));",
    "}",
    "fn bg_semantic_usad4_u32(a: u32, b: u32, c: u32) -> u32 {",
    "  var out = c;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out + max(left, right) - min(left, right);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vadd2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (((left + right) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsub2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (((left - right) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vaddss2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left_bits = (a >> shift) & 0xffffu;",
    "    let right_bits = (b >> shift) & 0xffffu;",
    "    let left = i32(left_bits) - select(0, 65536, left_bits >= 0x8000u);",
    "    let right = i32(right_bits) - select(0, 65536, right_bits >= 0x8000u);",
    "    out = out | ((u32(clamp(left + right, -32768, 32767)) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsubss2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left_bits = (a >> shift) & 0xffffu;",
    "    let right_bits = (b >> shift) & 0xffffu;",
    "    let left = i32(left_bits) - select(0, 65536, left_bits >= 0x8000u);",
    "    let right = i32(right_bits) - select(0, 65536, right_bits >= 0x8000u);",
    "    out = out | ((u32(clamp(left - right, -32768, 32767)) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vaddus2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (min(0xffffu, left + right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsubus2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (select(0u, left - right, left >= right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vabsdiffu2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | ((max(left, right) - min(left, right)) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vavgu2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (((left + right + 1u) >> 1u) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vminu2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (min(left, right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmaxu2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left = (a >> shift) & 0xffffu;",
    "    let right = (b >> shift) & 0xffffu;",
    "    out = out | (max(left, right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmins2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left_bits = (a >> shift) & 0xffffu;",
    "    let right_bits = (b >> shift) & 0xffffu;",
    "    let left = i32(left_bits) - select(0, 65536, left_bits >= 0x8000u);",
    "    let right = i32(right_bits) - select(0, 65536, right_bits >= 0x8000u);",
    "    out = out | ((u32(min(left, right)) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmaxs2_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 16u) {",
    "    let left_bits = (a >> shift) & 0xffffu;",
    "    let right_bits = (b >> shift) & 0xffffu;",
    "    let left = i32(left_bits) - select(0, 65536, left_bits >= 0x8000u);",
    "    let right = i32(right_bits) - select(0, 65536, right_bits >= 0x8000u);",
    "    out = out | ((u32(max(left, right)) & 0xffffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vadd4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (((left + right) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsub4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (((left - right) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vaddss4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left_bits = (a >> shift) & 0xffu;",
    "    let right_bits = (b >> shift) & 0xffu;",
    "    let left = i32(left_bits) - select(0, 256, left_bits >= 0x80u);",
    "    let right = i32(right_bits) - select(0, 256, right_bits >= 0x80u);",
    "    out = out | ((u32(clamp(left + right, -128, 127)) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsubss4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left_bits = (a >> shift) & 0xffu;",
    "    let right_bits = (b >> shift) & 0xffu;",
    "    let left = i32(left_bits) - select(0, 256, left_bits >= 0x80u);",
    "    let right = i32(right_bits) - select(0, 256, right_bits >= 0x80u);",
    "    out = out | ((u32(clamp(left - right, -128, 127)) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vaddus4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (min(0xffu, left + right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vsubus4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (select(0u, left - right, left >= right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vabsdiffu4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | ((max(left, right) - min(left, right)) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vavgu4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (((left + right + 1u) >> 1u) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vminu4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (min(left, right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmaxu4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = (a >> shift) & 0xffu;",
    "    let right = (b >> shift) & 0xffu;",
    "    out = out | (max(left, right) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmins4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left_bits = (a >> shift) & 0xffu;",
    "    let right_bits = (b >> shift) & 0xffu;",
    "    let left = i32(left_bits) - select(0, 256, left_bits >= 0x80u);",
    "    let right = i32(right_bits) - select(0, 256, right_bits >= 0x80u);",
    "    out = out | ((u32(min(left, right)) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_vmaxs4_u32(a: u32, b: u32) -> u32 {",
    "  var out = 0u;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left_bits = (a >> shift) & 0xffu;",
    "    let right_bits = (b >> shift) & 0xffu;",
    "    let left = i32(left_bits) - select(0, 256, left_bits >= 0x80u);",
    "    let right = i32(right_bits) - select(0, 256, right_bits >= 0x80u);",
    "    out = out | ((u32(max(left, right)) & 0xffu) << shift);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_dp4a_i32(a: u32, b: u32, c: i32) -> i32 {",
    "  var out = c;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    let left = i32(((a >> shift) & 0xffu) << 24u) >> 24u;",
    "    let right = i32(((b >> shift) & 0xffu) << 24u) >> 24u;",
    "    out = out + (left * right);",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_dp4a_u32(a: u32, b: u32, c: u32) -> u32 {",
    "  var out = c;",
    "  for (var shift = 0u; shift < 32u; shift = shift + 8u) {",
    "    out = out + (((a >> shift) & 0xffu) * ((b >> shift) & 0xffu));",
    "  }",
    "  return out;",
    "}",
    "fn bg_semantic_dp2a_i32(a: u32, b: u32, c: i32, byte_shift: u32) -> i32 {",
    "  let left0_bits = a & 0xffffu;",
    "  let left1_bits = (a >> 16u) & 0xffffu;",
    "  let right0_bits = (b >> byte_shift) & 0xffu;",
    "  let right1_bits = (b >> (byte_shift + 8u)) & 0xffu;",
    "  let left0 = i32(left0_bits) - select(0, 65536, left0_bits >= 0x8000u);",
    "  let left1 = i32(left1_bits) - select(0, 65536, left1_bits >= 0x8000u);",
    "  let right0 = i32(right0_bits) - select(0, 256, right0_bits >= 0x80u);",
    "  let right1 = i32(right1_bits) - select(0, 256, right1_bits >= 0x80u);",
    "  return c + (left0 * right0) + (left1 * right1);",
    "}",
    "fn bg_semantic_dp2a_u32(a: u32, b: u32, c: u32, byte_shift: u32) -> u32 {",
    "  let left0 = a & 0xffffu;",
    "  let left1 = (a >> 16u) & 0xffffu;",
    "  let right0 = (b >> byte_shift) & 0xffu;",
    "  let right1 = (b >> (byte_shift + 8u)) & 0xffu;",
    "  return c + (left0 * right0) + (left1 * right1);",
    "}",
  ];
}
