export {
  evaluateGopherQuality,
  exactLineDeduplicate,
  extractVisibleTextFromHtml,
  gopherQualityFilter,
  maskPii,
  minhashDeduplicateDocuments,
  type DeduplicationOptions,
  type DeduplicationResult,
  type DocumentInput,
  type DuplicateLine,
  type GopherQualityOptions,
  type GopherQualityReport,
  type GopherQualityRule,
  type MinHashDeduplicationOptions,
  type MinHashDeduplicationResult,
  type NearDuplicateDocument,
  type PiiMaskResult,
  type PiiKind,
  type PiiSpan,
} from "@unlocalhosted/browsergrad-data";
