// Generated by scripts/generate-grad-framework-platform-support.mjs.
// Source: architecture/grad-compatibility-inventory.json
// Do not edit by hand.

export const GRAD_FRAMEWORK_PLATFORM_OPERATIONS = [
  {
    "operationId": "browsergrad.grad.conversion.to-cross-floating.v1",
    "publicSurface": "Tensor.to(different_float_dtype)",
    "implementationId": "grad.conversion.to-cross-floating.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "different-supported-floating-dtype",
    "dtypeContract": "resolved-target",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-different-supported-floating-dtype",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "always-owning"
    }
  },
  {
    "operationId": "browsergrad.grad.conversion.to-cross-nonfloating.v1",
    "publicSurface": "Tensor.to(different_dtype_with_nonfloating_endpoint)",
    "implementationId": "grad.conversion.to-cross-nonfloating.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "different-dtype-with-nonfloating-endpoint",
    "dtypeContract": "resolved-target",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-different-dtype-with-nonfloating-endpoint",
      "closureAutograd": "supported-explicit-detached-boundary",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "always-owning"
    }
  },
  {
    "operationId": "browsergrad.grad.conversion.to-invalid-request-rejected.v1",
    "publicSurface": "Tensor.to(invalid_or_ambiguous_request)",
    "implementationId": "grad.conversion.to-invalid-request-rejected.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "invalid-to-request",
    "dtypeContract": "none-rejected",
    "decisions": {
      "cpu": "refused-reject-invalid-to-request-before-execution",
      "closureAutograd": "not-applicable",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "not-applicable-refused-before-execution",
      "materialization": "not-applicable"
    }
  },
  {
    "operationId": "browsergrad.grad.conversion.to-same-dtype-identity.v0",
    "publicSurface": "Tensor.to(same_dtype)",
    "implementationId": "grad.conversion.to-same-dtype-identity.v0",
    "semanticState": "verified-eager-contract",
    "shapeContract": "requested-dtype-equals-storage-dtype",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-requested-dtype-equals-storage-dtype",
      "closureAutograd": "supported-preserved-eager-autograd",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "none-view-or-identity"
    }
  },
  {
    "operationId": "browsergrad.grad.device.module-to.v1",
    "publicSurface": "nn.Module.to(...)",
    "implementationId": "grad.device.module-to.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "module-device-or-dtype-request",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-module-device-or-dtype-request",
      "closureAutograd": "supported-preserved-eager-autograd",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "none-view-or-identity"
    }
  },
  {
    "operationId": "browsergrad.grad.device.tensor-cpu.v1",
    "publicSurface": "Tensor.to(device='cpu') and Tensor.cpu()",
    "implementationId": "grad.device.tensor-cpu.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "cpu-device-request",
    "dtypeContract": "requested-dtype-dependent",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-cpu-device-request",
      "closureAutograd": "conditional-identity-or-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.device.tensor-unsupported-rejected.v1",
    "publicSurface": "Tensor.to(non_cpu_device) and Tensor.cuda()",
    "implementationId": "grad.device.tensor-unsupported-rejected.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "unsupported-device-request",
    "dtypeContract": "none-rejected",
    "decisions": {
      "cpu": "refused-cpu-only-reject-unsupported-device-before-execution",
      "closureAutograd": "not-applicable",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "not-applicable-refused-before-execution",
      "materialization": "not-applicable"
    }
  },
  {
    "operationId": "browsergrad.grad.device.torch-tensor-constructor.v1",
    "publicSurface": "torch.tensor(device=...)",
    "implementationId": "grad.device.torch-tensor-constructor.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "constructor-device-request",
    "dtypeContract": "surface-dependent",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-constructor-device-request",
      "closureAutograd": "conditional-constructor-policy",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.dtype.alias-registry.v1",
    "publicSurface": "Tensor(dtype=string|numpy-dtype-spec) and torch unsigned dtype tokens",
    "implementationId": "grad.dtype.alias-registry.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "requested-dtype-dependent",
    "dtypeContract": "resolved-target",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-requested-dtype-dependent",
      "closureAutograd": "conditional-constructor-policy",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.dtype.bf16-rejected.v1",
    "publicSurface": "Tensor(dtype='bf16'|'bfloat16')",
    "implementationId": "grad.dtype.bf16-rejected.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "requested-bf16-token",
    "dtypeContract": "none-rejected",
    "decisions": {
      "cpu": "refused-reject-unsupported-bfloat16-before-allocation",
      "closureAutograd": "not-applicable",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "not-applicable-refused-before-execution",
      "materialization": "not-applicable"
    }
  },
  {
    "operationId": "browsergrad.grad.dtype.tensor-constructor-default.v1",
    "publicSurface": "Tensor(data, dtype=None)",
    "implementationId": "grad.dtype.tensor-constructor-default.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "no-requested-dtype",
    "dtypeContract": "default-float32",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-no-requested-dtype",
      "closureAutograd": "conditional-constructor-policy",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.dtype.torch-bfloat16-token-distinct-unsupported.v1",
    "publicSurface": "torch.bfloat16",
    "implementationId": "grad.dtype.torch-bfloat16-token-distinct-unsupported.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "torch-bfloat16-token",
    "dtypeContract": "distinct-unsupported-token",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-torch-bfloat16-token",
      "closureAutograd": "not-applicable",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "not-applicable"
    }
  },
  {
    "operationId": "browsergrad.grad.dtype.torch-constructor-inference.v1",
    "publicSurface": "torch.tensor(data, dtype=None|supported, requires_grad=bool)",
    "implementationId": "grad.dtype.torch-constructor-inference.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "torch-constructor-request",
    "dtypeContract": "input-or-requested-dtype",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-torch-constructor-request",
      "closureAutograd": "conditional-constructor-policy",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "always-owning"
    }
  },
  {
    "operationId": "browsergrad.grad.interop.from-numpy.v1",
    "publicSurface": "from_numpy(ndarray)",
    "implementationId": "grad.interop.from-numpy.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "supported-writable-numpy-array",
    "dtypeContract": "preserves-supported-storage",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-supported-writable-numpy-array",
      "closureAutograd": "conditional-constructor-policy",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "none-view-or-identity"
    }
  },
  {
    "operationId": "browsergrad.grad.interop.numpy-export-snapshot.v1",
    "publicSurface": "Tensor.numpy() and numpy.asarray(Tensor)",
    "implementationId": "grad.interop.numpy-export-snapshot.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "numpy-export-request",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-browsergrad-grad-explicit-numpy-export-request",
      "closureAutograd": "not-applicable",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "always-owning"
    }
  },
  {
    "operationId": "browsergrad.grad.materialization.contiguous.v1",
    "publicSurface": "Tensor.contiguous()",
    "implementationId": "grad.materialization.contiguous.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "input-layout-dependent",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-input-layout-dependent",
      "closureAutograd": "conditional-identity-or-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.view.detach.v1",
    "publicSurface": "Tensor.detach()",
    "implementationId": "grad.view.detach.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "all-inputs",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "supported-pytorch-shaped-compatibility",
      "closureAutograd": "supported-explicit-detached-boundary",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "none-view-or-identity"
    }
  },
  {
    "operationId": "browsergrad.grad.view.expand.v1",
    "publicSurface": "Tensor.expand()",
    "implementationId": "grad.view.expand.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "all-inputs",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "supported-pytorch-shaped-compatibility",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "none-view-or-identity"
    }
  },
  {
    "operationId": "browsergrad.grad.view.indexing.v1",
    "publicSurface": "Tensor.__getitem__()",
    "implementationId": "grad.view.indexing.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "index-kind-dependent",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-index-kind-dependent",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.view.permute.v1",
    "publicSurface": "Tensor.permute()",
    "implementationId": "grad.view.permute.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "all-inputs",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "supported-pytorch-shaped-compatibility",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.view.reshape.v1",
    "publicSurface": "Tensor.reshape()/view()",
    "implementationId": "grad.view.reshape.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "input-layout-dependent",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "conditional-pytorch-shaped-compatibility-input-layout-dependent",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  },
  {
    "operationId": "browsergrad.grad.view.transpose.v1",
    "publicSurface": "Tensor.transpose()",
    "implementationId": "grad.view.transpose.v1",
    "semanticState": "verified-eager-contract",
    "shapeContract": "all-inputs",
    "dtypeContract": "preserves",
    "decisions": {
      "cpu": "supported-pytorch-shaped-compatibility",
      "closureAutograd": "supported-eager-graph-edge",
      "symbolicVjp": "not-applicable-eager",
      "functionalGrad": "not-applicable-eager",
      "vmap": "not-applicable-eager",
      "onnxExport": "not-applicable-eager",
      "tensorPlan": "not-applicable-eager-framework",
      "webgpu": "refused-numpy-reference-only",
      "residency": "pyodide-wasm-linear-memory",
      "materialization": "conditional-input-contract"
    }
  }
] as const;
