// @generated — do not edit by hand. Source: src/python/framework-operation-contracts.v1.json
// Regenerate via `pnpm codegen`.

export const FRAMEWORK_OPERATION_CONTRACTS_JSON: string = ((): string => {
  const b64 = "ewogICJzY2hlbWEiOiAiYnJvd3NlcmdyYWQuaml0LmZyYW1ld29yay1vcGVyYXRpb24tY29udHJhY3RzIiwKICAidmVyc2lvbiI6IHsKICAgICJtYWpvciI6IDEsCiAgICAibWlub3IiOiAwCiAgfSwKICAib3BlcmF0aW9ucyI6IFsKICAgIHsKICAgICAgImNvbnRyYWN0SWQiOiAiYnJvd3NlcmdyYWQuaml0LmZyYW1ld29yay50ZW5zb3IuZXhwYW5kLnYxIiwKICAgICAgInB1YmxpY1N1cmZhY2UiOiAiVGVuc29yLmV4cGFuZCIsCiAgICAgICJvcGNvZGUiOiAiQlJPQURDQVNUX1RPIiwKICAgICAgInNlbWFudGljU3RhdGUiOiAidHlwZWQiLAogICAgICAic2hhcGVDb250cmFjdCI6ICJzdGF0aWMtYnJvYWRjYXN0LXdpdGgtZXhpc3RpbmctZGltLW1pbnVzLW9uZSIsCiAgICAgICJkdHlwZUNvbnRyYWN0IjogInByZXNlcnZlLWlucHV0IiwKICAgICAgImRlY2lzaW9ucyI6IHsKICAgICAgICAiY3B1IjogInN1cHBvcnRlZC1udW1weS1vd25pbmctY29weSIsCiAgICAgICAgImNsb3N1cmVBdXRvZ3JhZCI6ICJzdXBwb3J0ZWQtdW5icm9hZGNhc3Qtc3VtIiwKICAgICAgICAic3ltYm9saWNWanAiOiAic3VwcG9ydGVkLXVuYnJvYWRjYXN0LXN1bSIsCiAgICAgICAgImZ1bmN0aW9uYWxHcmFkIjogInN1cHBvcnRlZC12aWEtc3ltYm9saWMtdmpwIiwKICAgICAgICAidm1hcCI6ICJzdXBwb3J0ZWQtbGVhZGluZy1iYXRjaC1heGlzIiwKICAgICAgICAib25ueEV4cG9ydCI6ICJzdXBwb3J0ZWQtb3BzZXQxNy1leHBhbmQiLAogICAgICAgICJ0ZW5zb3JQbGFuIjogInN1cHBvcnRlZC1wcmltaXRpdmUiLAogICAgICAgICJ3ZWJncHUiOiAicHJvZmlsZS1ub25lbXB0eS1mMzItcmFuay1hdC1tb3N0LTQiLAogICAgICAgICJyZXNpZGVuY3kiOiAic3VwcG9ydGVkLW1hdGVyaWFsaXppbmctYW5kLXJlc2lkZW50IiwKICAgICAgICAibWF0ZXJpYWxpemF0aW9uIjogImNwdS1vd25pbmctY29weSIKICAgICAgfSwKICAgICAgInJldGlyZWRPcGFxdWVPcGVyYXRpb25JZCI6ICJqaXQuY3VzdG9tLmV4cGFuZC52MCIKICAgIH0KICBdCn0K";
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder("utf-8").decode(bytes);
})();
