import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const moduleDirectory = dirname(fileURLToPath(import.meta.url));
export const CPP_CUTE_COMMAND_LINE_POLICY_INCLUDE_PATH = resolve(
  moduleDirectory,
  "extractor",
  "BrowserGradCppCuteCommandLinePolicy.inc",
);

/** @param {unknown} value @param {string} path */
function record(value, path) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new TypeError(`${path} must be an object`);
  }
  return value;
}

/** @param {unknown} value @param {string} path */
function array(value, path) {
  if (!Array.isArray(value)) throw new TypeError(`${path} must be an array`);
  return value;
}

/** @param {unknown} value @param {string} path */
function ascii(value, path) {
  if (typeof value !== "string" || value.length === 0 || !/^[\x20-\x7e]+$/u.test(value)) {
    throw new TypeError(`${path} must be non-empty printable ASCII`);
  }
  return value;
}

/** @param {string} value */
function cppString(value) {
  return JSON.stringify(value);
}

/** @param {readonly string[]} values @param {string} indent */
function renderArrayElements(values, indent) {
  return values.map((value) => `${indent}${cppString(value)},`).join("\n");
}

/**
 * Deterministically renders native compiler-policy data from canonical package
 * manifest authority. Input order is semantic; this function never sorts it.
 *
 * @param {unknown} manifest
 */
export function renderCppCuteCommandLinePolicyInclude(manifest) {
  const root = record(manifest, "$manifest");
  const body = record(root.body, "$manifest.body");
  const temporal = record(body.temporalMacros, "$manifest.body.temporalMacros");
  const registry = record(
    body.warningPolicyRegistry,
    "$manifest.body.warningPolicyRegistry",
  );
  const temporalNames = array(
    temporal.macroNames,
    "$manifest.body.temporalMacros.macroNames",
  ).map((value, index) => ascii(value, `$manifest.body.temporalMacros.macroNames[${index}]`));
  const reservedGroups = array(
    registry.reservedClangDiagnosticGroups,
    "$manifest.body.warningPolicyRegistry.reservedClangDiagnosticGroups",
  ).map((value, index) => ascii(
    value,
    `$manifest.body.warningPolicyRegistry.reservedClangDiagnosticGroups[${index}]`,
  ));
  const defenseInDepthArgv = array(
    temporal.defenseInDepthArgv,
    "$manifest.body.temporalMacros.defenseInDepthArgv",
  ).map((value, index) => ascii(
    value,
    `$manifest.body.temporalMacros.defenseInDepthArgv[${index}]`,
  ));
  const entries = array(
    registry.entries,
    "$manifest.body.warningPolicyRegistry.entries",
  );
  if (entries.length !== 6) throw new TypeError("warning registry must contain exactly six entries");
  const seenPolicyIds = new Set();
  const seenGroups = new Set();
  const warnings = entries.map((value, index) => {
    const path = `$manifest.body.warningPolicyRegistry.entries[${index}]`;
    const entry = record(value, path);
    const policyId = ascii(entry.policyId, `${path}.policyId`);
    const clangGroup = ascii(entry.clangDiagnosticGroup, `${path}.clangDiagnosticGroup`);
    if (seenPolicyIds.has(policyId) || seenGroups.has(clangGroup)) {
      throw new TypeError(`${path} duplicates warning policy or Clang group`);
    }
    seenPolicyIds.add(policyId);
    seenGroups.add(clangGroup);
    const argv = record(entry.argv, `${path}.argv`);
    const dispositions = [
      ["ignore", 1],
      ["warn", 2],
      ["error", 2],
    ].map(([name, expectedLength]) => {
      const values = array(argv[name], `${path}.argv.${name}`).map(
        (argument, argumentIndex) => ascii(
          argument,
          `${path}.argv.${name}[${argumentIndex}]`,
        ),
      );
      if (values.length !== expectedLength) {
        throw new TypeError(`${path}.argv.${name} must contain ${expectedLength} arguments`);
      }
      return values;
    });
    return {
      policyId,
      clangGroup,
      ignore: dispositions[0],
      warn: dispositions[1],
      error: dispositions[2],
    };
  });

  const warningRecords = warnings.map((warning) => [
    "    {",
    `        ${cppString(warning.policyId)},`,
    `        ${cppString(warning.clangGroup)},`,
    `        {${warning.ignore.map(cppString).join(", ")}},`,
    `        {${warning.warn.map(cppString).join(", ")}},`,
    `        {${warning.error.map(cppString).join(", ")}},`,
    "    },",
  ].join("\n")).join("\n");

  return [
    "// Generated by cpp_cute_browser_command_line_policy_codegen.mjs.",
    "// Source: CPP_CUTE_SEMANTIC_ADAPTER_MANIFEST_V1_RESOURCE. DO NOT EDIT.",
    "",
    `constexpr std::string_view kTemporalMacroPolicyId = ${cppString(ascii(temporal.policyId, "$manifest.body.temporalMacros.policyId"))};`,
    `constexpr std::string_view kWarningPolicyRegistryId = ${cppString(ascii(registry.registryId, "$manifest.body.warningPolicyRegistry.registryId"))};`,
    `[[maybe_unused]] constexpr std::string_view kWarningCompilerBaseline = ${cppString(ascii(registry.compilerBaseline, "$manifest.body.warningPolicyRegistry.compilerBaseline"))};`,
    `[[maybe_unused]] constexpr std::string_view kUnknownWarningPolicy = ${cppString(ascii(registry.unknownPolicy, "$manifest.body.warningPolicyRegistry.unknownPolicy"))};`,
    "",
    `constexpr std::array<std::string_view, ${temporalNames.length}U> kTemporalMacroNames = {{`,
    renderArrayElements(temporalNames, "    "),
    "}};",
    "",
    `[[maybe_unused]] constexpr std::array<std::string_view, ${reservedGroups.length}U> kReservedClangDiagnosticGroups = {{`,
    renderArrayElements(reservedGroups, "    "),
    "}};",
    "",
    `[[maybe_unused]] constexpr std::array<std::string_view, ${defenseInDepthArgv.length}U> kTemporalDefenseInDepthArgv = {{`,
    renderArrayElements(defenseInDepthArgv, "    "),
    "}};",
    "",
    `constexpr std::array<WarningMapping, ${warnings.length}U> kWarningMappings = {{`,
    warningRecords,
    "}};",
    "",
  ].join("\n");
}

/** @param {unknown} manifest @param {Uint8Array} actualBytes */
export function cppCuteCommandLinePolicyIncludeMatches(manifest, actualBytes) {
  const expected = Buffer.from(renderCppCuteCommandLinePolicyInclude(manifest), "utf8");
  return expected.length === actualBytes.length && expected.equals(actualBytes);
}

async function main() {
  const mode = process.argv[2] ?? "--check";
  if (mode !== "--check" && mode !== "--write") {
    throw new TypeError("usage: node cpp_cute_browser_command_line_policy_codegen.mjs [--check|--write]");
  }
  let resourceModule;
  try {
    resourceModule = await import("../../dist/resources/cpp_cute_semantic_adapter_manifest_v1.js");
  } catch (error) {
    throw new Error("build compiler package before running command-line policy codegen", { cause: error });
  }
  const expected = renderCppCuteCommandLinePolicyInclude(
    resourceModule.CPP_CUTE_SEMANTIC_ADAPTER_MANIFEST_V1_RESOURCE,
  );
  if (mode === "--write") {
    writeFileSync(CPP_CUTE_COMMAND_LINE_POLICY_INCLUDE_PATH, expected, "utf8");
    return;
  }
  const actual = readFileSync(CPP_CUTE_COMMAND_LINE_POLICY_INCLUDE_PATH);
  if (!cppCuteCommandLinePolicyIncludeMatches(
    resourceModule.CPP_CUTE_SEMANTIC_ADAPTER_MANIFEST_V1_RESOURCE,
    actual,
  )) {
    throw new Error("generated native command-line policy differs from semantic adapter manifest");
  }
}

const invokedPath = process.argv[1] === undefined ? null : pathToFileURL(resolve(process.argv[1])).href;
if (invokedPath === import.meta.url) await main();
