import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  reviewCppCuteBrowserConfiguredTarget,
} from "./cpp_cute_browser_configured_target_review.mjs";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, {
    recursive: true,
    force: true,
  })));
});

async function fixture(
  compileFlags = "-O3 -fexceptions -DNDEBUG",
  includeSelection: "both" | "source-only" | "binary-only" = "both",
  llvmRtti = "ON",
) {
  const root = await mkdtemp(join(tmpdir(), "browsergrad-configured-target-"));
  roots.push(root);
  const wasmBuildRoot = join(root, "wasm-build");
  const llvmProjectSourceRoot = join(root, "llvm-project");
  const targetDirectory = join(
    wasmBuildRoot,
    "tools",
    "browsergrad_extractor",
    "CMakeFiles",
    "browsergrad-cpp-cute-extractor.dir",
  );
  const factoryModulePath = join(root, "evidence", "generated", "clang-extractor.mjs");
  const sourceInclude = `-I${join(llvmProjectSourceRoot, "clang", "include")}`;
  const binaryInclude = `-I${join(wasmBuildRoot, "tools", "clang", "include")}`;
  const includeFlags = includeSelection === "both"
    ? `${binaryInclude} ${sourceInclude}`
    : includeSelection === "source-only" ? sourceInclude : binaryInclude;
  await mkdir(targetDirectory, { recursive: true });
  await writeFile(join(targetDirectory, "flags.make"), [
    "# generated by CMake",
    `CXX_INCLUDES = ${includeFlags}`,
    `CXX_FLAGS = ${compileFlags}`,
    "",
  ].join("\n"));
  await writeFile(
    join(targetDirectory, "link.txt"),
    `/emsdk/upstream/emscripten/em++ -O3 -fexceptions objects.o -o ${factoryModulePath}\n`,
  );
  await writeFile(
    join(wasmBuildRoot, "CMakeCache.txt"),
    `# generated by CMake\nLLVM_ENABLE_RTTI:BOOL=${llvmRtti}\n`,
  );
  return {
    root,
    wasmBuildRoot,
    llvmProjectSourceRoot,
    targetDirectory,
    factoryModulePath,
  };
}

describe("configured BrowserGrad Clang-Wasm target review", () => {
  it("observes the exact target compile and link exception mode", async () => {
    const input = await fixture();
    await expect(reviewCppCuteBrowserConfiguredTarget(input)).resolves.toMatchObject({
      authority: "configured-target-flags-review-only",
      exceptionMode: "emscripten-javascript",
      rttiRequired: true,
      llvmLibrariesRttiEnabled: true,
      clangIncludeDirectoriesVerified: true,
      compileFlagsSha256: expect.stringMatching(/^[0-9a-f]{64}$/u),
      linkCommandSha256: expect.stringMatching(/^[0-9a-f]{64}$/u),
      buildExecuted: false,
      abiConformanceVerified: false,
      releaseReady: false,
    });
  });

  it.each(["-fno-exceptions", "-fwasm-exceptions", "-fno-rtti"])(
    "rejects forbidden target mode %s before compilation",
    async (flag) => {
      const input = await fixture(`-O3 -fexceptions ${flag}`);
      await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
        code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
        path: "$.compileFlags.CXX_FLAGS",
      });
    },
  );

  it("rejects RTTI-disabled LLVM and Clang libraries before compilation", async () => {
    const input = await fixture(
      "-O3 -fexceptions -DNDEBUG",
      "both",
      "OFF",
    );
    await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
      code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
      path: "$.cmakeCache.LLVM_ENABLE_RTTI",
    });
  });

  it.each(["source-only", "binary-only"] as const)(
    "rejects a configured target missing one Clang include root (%s)",
    async (includeSelection) => {
      const input = await fixture("-O3 -fexceptions -DNDEBUG", includeSelection);
      await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
        code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
        path: "$.compileFlags.CXX_INCLUDES",
      });
    },
  );

  it("rejects symlinked target evidence", async () => {
    const input = await fixture();
    await rm(join(input.targetDirectory, "flags.make"));
    await writeFile(join(input.root, "substitute-flags.make"), "CXX_FLAGS = -fexceptions\n");
    await symlink(
      join(input.root, "substitute-flags.make"),
      join(input.targetDirectory, "flags.make"),
    );

    await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
      code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
      path: "$.compileFlags",
    });
  });

  it("rejects a symlinked CMake cache", async () => {
    const input = await fixture();
    await rm(join(input.wasmBuildRoot, "CMakeCache.txt"));
    await writeFile(
      join(input.root, "substitute-cache.txt"),
      "LLVM_ENABLE_RTTI:BOOL=ON\n",
    );
    await symlink(
      join(input.root, "substitute-cache.txt"),
      join(input.wasmBuildRoot, "CMakeCache.txt"),
    );

    await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
      code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
      path: "$.cmakeCache",
    });
  });
});
