import type {
  PreparedCppCuteBrowserBuildInputLock,
} from "../../dist/cpp_cute_browser_build_lock.js";
import type {
  CppCuteClangWasmBuildRoots,
  CppCuteClangWasmMaterializedTools,
} from "./cpp_cute_browser_build_plan.mjs";
import type {
  CppCuteBrowserConfiguredTargetReview,
} from "./cpp_cute_browser_configured_target_review.mjs";

export interface PrepareCppCuteClangWasmBuildSourceInput {
  readonly lock: PreparedCppCuteBrowserBuildInputLock;
  readonly tools: CppCuteClangWasmMaterializedTools;
  readonly roots: CppCuteClangWasmBuildRoots;
  readonly extractorSourceInputRoot: string;
}

export interface CppCuteBrowserBuildExecutorOptions {
  readonly signal?: AbortSignal;
}

export interface CppCuteBrowserBuildExecutionOptions extends CppCuteBrowserBuildExecutorOptions {
  /** Mirrors the already-bounded build logs while retaining immutable evidence. */
  readonly mirrorOutput?: boolean;
}

declare const preparedCppCuteClangWasmBuildSourceBrand: unique symbol;

/**
 * Opaque authority over one exact staged extractor source snapshot.
 * Its parent is current-user-owned and not group/other-writable; same-uid
 * actors must honor the executor's single-writer boundary.
 * It proves no build execution, output identity, reproducibility, or release.
 */
export interface PreparedCppCuteClangWasmBuildSource {
  readonly [preparedCppCuteClangWasmBuildSourceBrand]: true;
  readonly authority: "build-source-snapshot-only";
  readonly lockId: string;
  readonly sourceSetSha256: string;
  readonly fileCount: number;
  readonly totalByteLength: number;
  readonly stagedSourceRoot: string;
  readonly sourceVerified: true;
  readonly buildExecuted: false;
  readonly outputIdentityAuthorized: false;
  readonly reproducibilityVerified: false;
  readonly releaseReady: false;
}

export interface ExecutedCppCuteClangWasmBuildStep {
  readonly id: string;
  readonly stageId: "native-tablegen" | "clang-extractor-wasm";
  readonly kind: "configure" | "build";
  readonly executable: string;
  readonly arguments: readonly string[];
  readonly cwd: string;
  readonly environment: Readonly<Record<string, string>>;
  readonly exitCode: number | null;
  readonly terminationSignal: NodeJS.Signals | null;
  readonly stdoutPath: string;
  readonly stdoutSha256: string;
  readonly stdoutByteLength: number;
  readonly stderrPath: string;
  readonly stderrSha256: string;
  readonly stderrByteLength: number;
}

export interface ExecutedCppCuteClangWasmNativeTool {
  readonly path: string;
  readonly sha256: string;
  readonly byteLength: number;
}

declare const executedCppCuteClangWasmBuildBrand: unique symbol;

/**
 * Opaque observation of one successful exact four-step Clang-Wasm build.
 * Generated bytes are sealed and structurally validated, but this is not ABI,
 * reproducibility, provenance, distribution, or release authority.
 */
export interface ExecutedCppCuteClangWasmBuild {
  readonly [executedCppCuteClangWasmBuildBrand]: true;
  readonly authority: "clang-wasm-build-execution-observation-only";
  readonly lockId: string;
  readonly sourceSetSha256: string;
  readonly paths: Readonly<{
    readonly llvmProjectSourceRoot: string;
    readonly extractorSourceRoot: string;
    readonly nativeBuildRoot: string;
    readonly wasmBuildRoot: string;
    readonly outputRoot: string;
    readonly stateRoot: string;
  }>;
  readonly nativeTools: Readonly<{
    readonly clangTablegen: ExecutedCppCuteClangWasmNativeTool;
    readonly llvmTablegen: ExecutedCppCuteClangWasmNativeTool;
  }>;
  readonly configuredTarget: CppCuteBrowserConfiguredTargetReview;
  readonly stepCount: number;
  readonly steps: readonly ExecutedCppCuteClangWasmBuildStep[];
  readonly factoryModulePath: string;
  readonly factoryModuleSha256: string;
  readonly factoryModuleByteLength: number;
  readonly wasmSidecarPath: string;
  readonly wasmSha256: string;
  readonly wasmByteLength: number;
  readonly linkMapPath: string;
  readonly linkMapSha256: string;
  readonly linkMapByteLength: number;
  readonly sourceVerified: true;
  readonly buildExecuted: true;
  readonly factoryModuleUtf8Validated: true;
  readonly webAssemblyValidated: true;
  readonly abiConformanceVerified: false;
  readonly outputIdentityAuthorized: false;
  readonly reproducibilityVerified: false;
  readonly releaseReady: false;
  readonly factoryModuleDistributed: false;
}

declare const materializedCppCuteClangWasmSidecarBrand: unique symbol;

/**
 * Exact-copy observation. It is not build, provenance, or release authority.
 * The hard-link is the cancellation commit point. Output parents are
 * current-user-owned and not group/other-writable; same-uid actors must honor
 * the executor's single-writer boundary.
 */
export interface MaterializedCppCuteClangWasmSidecar {
  readonly [materializedCppCuteClangWasmSidecarBrand]: true;
  readonly authority: "wasm-sidecar-byte-materialization-observation-only";
  readonly lockId: string;
  readonly sourceSetSha256: string;
  readonly generatedWasmSha256: string;
  readonly distributedWasmSha256: string;
  readonly wasmByteLength: number;
  readonly distributedWasmPath: string;
  readonly sidecarBytesMaterialized: true;
  readonly webAssemblyValidated: false;
  readonly abiConformanceVerified: false;
  readonly sourceVerified: true;
  readonly buildExecuted: false;
  readonly outputIdentityAuthorized: false;
  readonly reproducibilityVerified: false;
  readonly releaseReady: false;
  readonly factoryModuleDistributed: false;
}

export type CppCuteBrowserBuildExecutorErrorCode =
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-CANCELLED"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-INVALID"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-RESOURCE-LIMIT"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-HASH-MISMATCH"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-CONFLICT"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-IO"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-CLEANUP"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-UNVERIFIED"
  | "BG-COMPILER-CPP-CUTE-BROWSER-BUILD-EXECUTOR-BUILD-FAILED";

export class CppCuteBrowserBuildExecutorError extends Error {
  readonly code: CppCuteBrowserBuildExecutorErrorCode;
  readonly path: string;
}

export function prepareCppCuteClangWasmBuildSource(
  input: PrepareCppCuteClangWasmBuildSourceInput,
  options?: CppCuteBrowserBuildExecutorOptions,
): Promise<PreparedCppCuteClangWasmBuildSource>;

export function executeCppCuteClangWasmBuild(
  prepared: PreparedCppCuteClangWasmBuildSource,
  options?: CppCuteBrowserBuildExecutionOptions,
): Promise<ExecutedCppCuteClangWasmBuild>;

export function materializeCppCuteClangWasmSidecar(
  prepared: PreparedCppCuteClangWasmBuildSource,
  options?: CppCuteBrowserBuildExecutorOptions,
): Promise<MaterializedCppCuteClangWasmSidecar>;
