import { describe, expect, it } from "vitest";

import {
  CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_RESOURCE,
} from "../../dist/resources/cpp_cute_browser_build_lock_v1.js";
import {
  CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_RESOURCE,
} from "../../dist/resources/cpp_cute_browser_reproducibility_v3.js";
import {
  parseCppCuteBrowserReproducibilityAuthoringArguments,
  projectCppCuteBrowserReproducibility,
  renderCppCuteBrowserReproducibilityIdentity,
  renderCppCuteBrowserReproducibilityResource,
} from "./cpp_cute_browser_reproducibility_authoring.mjs";

interface MutableEvidence {
  authority: string;
  lockId: string;
  sourceSetSha256: string;
  builds: [
    { wasmSha256: string; readonly wasmByteLength: number },
    { wasmSha256: string; readonly wasmByteLength: number },
  ];
}

describe("Clang-Wasm reproducibility resource authoring", () => {
  it("accepts only exact check or canonical evidence metadata", () => {
    expect(
      parseCppCuteBrowserReproducibilityAuthoringArguments(["--check"]),
    ).toEqual({
      check: true,
      inputPath: undefined,
      runId: undefined,
      sourceRevision: undefined,
    });
    expect(
      parseCppCuteBrowserReproducibilityAuthoringArguments([
        "--",
        "--source-revision=" + "a".repeat(40),
        "--input=/private/tmp/reproducibility.json",
        "--run-id=30475350224",
      ]),
    ).toEqual({
      check: false,
      inputPath: "/private/tmp/reproducibility.json",
      runId: "30475350224",
      sourceRevision: "a".repeat(40),
    });
    for (const arguments_ of [
      [],
      ["--input=relative.json", "--run-id=1", "--source-revision=" + "a".repeat(40)],
      ["--input=/tmp/a", "--run-id=0", "--source-revision=" + "a".repeat(40)],
      ["--input=/tmp/a", "--run-id=1", "--source-revision=ABC"],
      ["--check", "--run-id=1", "--source-revision=" + "a".repeat(40)],
    ]) {
      expect(() =>
        parseCppCuteBrowserReproducibilityAuthoringArguments(arguments_),
      ).toThrow();
    }
  });

  it("projects and renders evidence bound to the current build lock", async () => {
    const currentEvidence = currentEvidenceFixture();
    const projection = await projectCppCuteBrowserReproducibility(
      currentEvidence,
      {
        runId: "30475350224",
        sourceRevision: "a".repeat(40),
      },
    );
    expect(projection).toMatchObject({
      runId: "30475350224",
      sourceRevision: "a".repeat(40),
      wasmSha256: currentEvidence.builds[0].wasmSha256,
      wasmByteLength: currentEvidence.builds[0].wasmByteLength,
    });
    expect(projection.resourceSha256).toMatch(/^[0-9a-f]{64}$/u);
    expect(projection.resourceByteLength).toBeGreaterThan(0);
    expect(
      renderCppCuteBrowserReproducibilityResource(projection),
    ).toContain(
      "Generated by cpp_cute_browser_reproducibility_authoring.mjs",
    );
    expect(
      renderCppCuteBrowserReproducibilityIdentity(projection),
    ).toContain("30475350224");
  });

  it("rejects drifted parity, authority, and package lock bindings", async () => {
    const driftedWasm = currentEvidenceFixture();
    driftedWasm.builds[1].wasmSha256 = "f".repeat(64);
    await expect(
      projectCppCuteBrowserReproducibility(driftedWasm, {
        runId: "1",
        sourceRevision: "a".repeat(40),
      }),
    ).rejects.toThrow();

    const driftedAuthority = currentEvidenceFixture();
    driftedAuthority.authority = "caller-asserted";
    await expect(
      projectCppCuteBrowserReproducibility(driftedAuthority, {
        runId: "1",
        sourceRevision: "a".repeat(40),
      }),
    ).rejects.toThrow();

    const driftedLock = currentEvidenceFixture();
    driftedLock.lockId =
      "bg.cpp.browser-build-input-lock.sha256." + "f".repeat(64);
    await expect(
      projectCppCuteBrowserReproducibility(driftedLock, {
        runId: "1",
        sourceRevision: "a".repeat(40),
      }),
    ).rejects.toThrow();
  });
});

function currentEvidenceFixture(): MutableEvidence {
  const evidence = structuredClone(
    CPP_CUTE_BROWSER_REPRODUCIBILITY_V3_RESOURCE,
  ) as unknown as MutableEvidence;
  evidence.lockId = CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_RESOURCE.lockId;
  evidence.sourceSetSha256 =
    CPP_CUTE_BROWSER_BUILD_INPUT_LOCK_V1_RESOURCE.body.recipe
      .extractorSource.sourceSetSha256;
  return evidence;
}
