import { describe, expect, it } from "vitest";

import {
  parseCppCuteBrowserFullDistributionReproducibilityAuthoringArguments,
  renderCppCuteBrowserFullDistributionReproducibilityIdentity,
  renderCppCuteBrowserFullDistributionReproducibilityResource,
  type CppCuteBrowserFullDistributionReproducibilityAuthoringProjection,
} from "./cpp_cute_browser_full_distribution_reproducibility_authoring.mjs";

const PROJECTION = {
  schema:
    "browsergrad.compiler.cpp-cute.browser-full-distribution-reproducibility-authoring-projection",
  version: 1,
  authority: "package-authoring-projection-only",
  resource: {
    reproducibilityId:
      `bg.cpp.browser-full-distribution-reproducibility.sha256.${"d".repeat(64)}`,
    schema:
      "browsergrad.compiler.cpp-cute.browser-full-distribution-reproducibility-observation",
    version: 1,
  },
  resourceSha256: "a".repeat(64),
  resourceByteLength: 123,
  sourceRevision: "b".repeat(40),
} as const satisfies CppCuteBrowserFullDistributionReproducibilityAuthoringProjection;

describe("full-distribution reproducibility authoring", () => {
  it("accepts only check or the closed live authoring input set", () => {
    expect(
      parseCppCuteBrowserFullDistributionReproducibilityAuthoringArguments([
        "--check",
      ]),
    ).toEqual({
      check: true,
      deterministicRoot: undefined,
      evidencePath: undefined,
      producerPolicyPath: undefined,
      profilePath: undefined,
      sourceRevision: undefined,
    });
    expect(
      parseCppCuteBrowserFullDistributionReproducibilityAuthoringArguments([
        "--profile=/private/tmp/profile.json",
        "--evidence=/private/tmp/evidence.json",
        `--source-revision=${"c".repeat(40)}`,
        "--producer-policy=/private/tmp/policy.json",
        "--deterministic-root=/private/tmp/root",
      ]),
    ).toEqual({
      check: false,
      deterministicRoot: "/private/tmp/root",
      evidencePath: "/private/tmp/evidence.json",
      producerPolicyPath: "/private/tmp/policy.json",
      profilePath: "/private/tmp/profile.json",
      sourceRevision: "c".repeat(40),
    });
    for (const arguments_ of [
      [],
      ["--check", "--evidence=/tmp/a"],
      [
        "--profile=/tmp/p",
        "--evidence=relative",
        `--source-revision=${"c".repeat(40)}`,
        "--producer-policy=/tmp/policy",
        "--deterministic-root=/tmp/root",
      ],
    ]) {
      expect(() =>
        parseCppCuteBrowserFullDistributionReproducibilityAuthoringArguments(
          arguments_,
        ),
      ).toThrow();
    }
  });

  it("renders deterministic typed resource and identity modules", () => {
    const resource =
      renderCppCuteBrowserFullDistributionReproducibilityResource(PROJECTION);
    expect(resource).toContain(
      "Generated by cpp_cute_browser_full_distribution_reproducibility_authoring.mjs",
    );
    expect(resource).toContain(
      "CppCuteBrowserFullDistributionReproducibilityOutputV1",
    );
    expect(resource).toContain("as const satisfies JsonObject");

    const identity =
      renderCppCuteBrowserFullDistributionReproducibilityIdentity(PROJECTION);
    expect(identity).toContain(`"${"a".repeat(64)}"`);
    expect(identity).toContain(`"${"b".repeat(40)}"`);
  });

  it("rejects malformed authoring projections", () => {
    expect(() =>
      renderCppCuteBrowserFullDistributionReproducibilityResource({
        ...PROJECTION,
        resourceSha256: "not-a-digest",
      }),
    ).toThrow();
  });
});
