import { describe, expect, it } from "vitest";

import {
  parseCppCuteBrowserStrictCompileObservationAuthoringArguments,
  renderCppCuteBrowserStrictCompileObservationIdentity,
  renderCppCuteBrowserStrictCompileObservationResource,
  type CppCuteBrowserStrictCompileObservationAuthoringProjection,
} from "./cpp_cute_browser_strict_compile_observation_authoring.mjs";

const PROJECTION = {
  schema:
    "browsergrad.compiler.cpp-cute.strict-compile-observation-authoring-projection",
  version: 1,
  authority: "package-authoring-projection-only",
  matrix: {
    authority: "local-real-browser-worker-matrix-observation-only",
    caseCount: 9,
    cases: [],
    claims: {},
    packageBinding: {},
    schema:
      "browsergrad.compiler.cpp-cute.browser-real-compile-matrix-observation",
    version: 2,
  },
  resourceSha256: "a".repeat(64),
  resourceByteLength: 123,
  sourceRevision: "b".repeat(40),
  workerBundleSha256: "c".repeat(64),
  verifierWorkerBundleSha256: "d".repeat(64),
  wasmSha256: "e".repeat(64),
  wasmByteLength: 456,
} as const satisfies CppCuteBrowserStrictCompileObservationAuthoringProjection;

describe("strict browser compile observation authoring", () => {
  it("accepts only one exact check or canonical absolute input mode", () => {
    expect(
      parseCppCuteBrowserStrictCompileObservationAuthoringArguments([
        "--check",
      ]),
    ).toEqual({ check: true, inputPath: undefined });
    expect(
      parseCppCuteBrowserStrictCompileObservationAuthoringArguments([
        "--",
        "--input=/private/tmp/matrix.json",
      ]),
    ).toEqual({
      check: false,
      inputPath: "/private/tmp/matrix.json",
    });
    for (const arguments_ of [
      [],
      ["--input=relative.json"],
      ["--", "--check", "--input=/tmp/a"],
      ["--input=/tmp/a", "--check"],
      ["--unknown"],
    ]) {
      expect(() =>
        parseCppCuteBrowserStrictCompileObservationAuthoringArguments(
          arguments_,
        ),
      ).toThrow();
    }
  });

  it("renders deterministic typed resource and identity modules", () => {
    const resource =
      renderCppCuteBrowserStrictCompileObservationResource(PROJECTION);
    expect(resource).toContain(
      "Generated by cpp_cute_browser_strict_compile_observation_authoring.mjs",
    );
    expect(resource).toContain('"caseCount": 9');
    expect(resource).toContain("as const satisfies JsonObject");

    const identity =
      renderCppCuteBrowserStrictCompileObservationIdentity(PROJECTION);
    expect(identity).toContain(`"${"a".repeat(64)}"`);
    expect(identity).toContain(`"${"b".repeat(40)}"`);
    expect(identity).toContain(`"${"c".repeat(64)}"`);
    expect(identity).toContain(`"${"d".repeat(64)}"`);
  });

  it("rejects structurally similar non-authoring projections", () => {
    expect(() =>
      renderCppCuteBrowserStrictCompileObservationResource({
        ...PROJECTION,
        resourceSha256: "not-a-digest",
      }),
    ).toThrow();
  });
});
