import { describe, expect, it } from "vitest";

import {
  parseCppCuteBrowserHeaderDistributionReproducibilityAuthoringArguments,
  renderCppCuteBrowserHeaderDistributionReproducibilityIdentity,
  renderCppCuteBrowserHeaderDistributionReproducibilityResource,
  type CppCuteBrowserHeaderDistributionReproducibilityAuthoringProjection,
} from "./cpp_cute_browser_header_distribution_reproducibility_authoring.mjs";

const PROJECTION = {
  schema:
    "browsergrad.compiler.cpp-cute.browser-header-distribution-reproducibility-authoring-projection",
  version: 1,
  authority: "package-authoring-projection-only",
  resource: {
    schema:
      "browsergrad.compiler.cpp-cute.browser-header-distribution-reproducibility",
    version: 2,
    outputs: [],
  },
  resourceSha256: "a".repeat(64),
  resourceByteLength: 123,
  sourceRevision: "b".repeat(40),
  headerInputProjectionId:
    `bg.cpp.browser-header-input-projection.sha256.${"c".repeat(64)}`,
} as const satisfies CppCuteBrowserHeaderDistributionReproducibilityAuthoringProjection;

describe("header-distribution reproducibility authoring", () => {
  it("accepts only check or one exact input and source revision", () => {
    expect(
      parseCppCuteBrowserHeaderDistributionReproducibilityAuthoringArguments([
        "--check",
      ]),
    ).toEqual({
      check: true,
      inputPath: undefined,
      sourceRevision: undefined,
    });
    expect(
      parseCppCuteBrowserHeaderDistributionReproducibilityAuthoringArguments([
        "--",
        "--source-revision=0123456789abcdef0123456789abcdef01234567",
        "--input=/private/tmp/header-repro.json",
      ]),
    ).toEqual({
      check: false,
      inputPath: "/private/tmp/header-repro.json",
      sourceRevision: "0123456789abcdef0123456789abcdef01234567",
    });
    for (const arguments_ of [
      [],
      ["--input=relative.json", `--source-revision=${"a".repeat(40)}`],
      ["--input=/tmp/a"],
      ["--check", "--input=/tmp/a"],
      ["--input=/tmp/a", "--unknown=x"],
    ]) {
      expect(() =>
        parseCppCuteBrowserHeaderDistributionReproducibilityAuthoringArguments(
          arguments_,
        ),
      ).toThrow();
    }
  });

  it("renders deterministic typed resource and identity modules", () => {
    const resource =
      renderCppCuteBrowserHeaderDistributionReproducibilityResource(PROJECTION);
    expect(resource).toContain(
      "Generated by cpp_cute_browser_header_distribution_reproducibility_authoring.mjs",
    );
    expect(resource).toContain(
      "CppCuteBrowserHeaderDistributionReproducibilityOutputV2",
    );
    expect(resource).toContain("as const satisfies JsonObject");

    const identity =
      renderCppCuteBrowserHeaderDistributionReproducibilityIdentity(PROJECTION);
    expect(identity).toContain(`"${"a".repeat(64)}"`);
    expect(identity).toContain(`"${"b".repeat(40)}"`);
    expect(identity).toContain(PROJECTION.headerInputProjectionId);
  });

  it("rejects structurally similar malformed projections", () => {
    expect(() =>
      renderCppCuteBrowserHeaderDistributionReproducibilityResource({
        ...PROJECTION,
        resourceSha256: "not-a-digest",
      }),
    ).toThrow();
  });
});
