import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  reviewCppCuteBrowserConfiguredTarget,
} from "./cpp_cute_browser_configured_target_review.mjs";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, {
    recursive: true,
    force: true,
  })));
});

async function fixture(compileFlags = "-O3 -fexceptions -DNDEBUG") {
  const root = await mkdtemp(join(tmpdir(), "browsergrad-configured-target-"));
  roots.push(root);
  const wasmBuildRoot = join(root, "wasm-build");
  const targetDirectory = join(
    wasmBuildRoot,
    "tools",
    "browsergrad_extractor",
    "CMakeFiles",
    "browsergrad-cpp-cute-extractor.dir",
  );
  const factoryModulePath = join(root, "evidence", "generated", "clang-extractor.mjs");
  await mkdir(targetDirectory, { recursive: true });
  await writeFile(join(targetDirectory, "flags.make"), [
    "# generated by CMake",
    `CXX_FLAGS = ${compileFlags}`,
    "",
  ].join("\n"));
  await writeFile(
    join(targetDirectory, "link.txt"),
    `/emsdk/upstream/emscripten/em++ -O3 -fexceptions objects.o -o ${factoryModulePath}\n`,
  );
  return { root, wasmBuildRoot, targetDirectory, factoryModulePath };
}

describe("configured BrowserGrad Clang-Wasm target review", () => {
  it("observes the exact target compile and link exception mode", async () => {
    const input = await fixture();
    await expect(reviewCppCuteBrowserConfiguredTarget(input)).resolves.toMatchObject({
      authority: "configured-target-flags-review-only",
      exceptionMode: "emscripten-javascript",
      rttiRequired: true,
      compileFlagsSha256: expect.stringMatching(/^[0-9a-f]{64}$/u),
      linkCommandSha256: expect.stringMatching(/^[0-9a-f]{64}$/u),
      buildExecuted: false,
      abiConformanceVerified: false,
      releaseReady: false,
    });
  });

  it.each(["-fno-exceptions", "-fwasm-exceptions", "-fno-rtti"])(
    "rejects forbidden target mode %s before compilation",
    async (flag) => {
      const input = await fixture(`-O3 -fexceptions ${flag}`);
      await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
        code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
        path: "$.compileFlags.CXX_FLAGS",
      });
    },
  );

  it("rejects symlinked target evidence", async () => {
    const input = await fixture();
    await rm(join(input.targetDirectory, "flags.make"));
    await writeFile(join(input.root, "substitute-flags.make"), "CXX_FLAGS = -fexceptions\n");
    await symlink(
      join(input.root, "substitute-flags.make"),
      join(input.targetDirectory, "flags.make"),
    );

    await expect(reviewCppCuteBrowserConfiguredTarget(input)).rejects.toMatchObject({
      code: "BG-COMPILER-CPP-CUTE-BROWSER-CONFIGURED-TARGET-REVIEW-INVALID",
      path: "$.compileFlags",
    });
  });
});
