import { createHash } from "node:crypto";

import {
  canonicalJsonBytes,
} from "@unlocalhosted/browsergrad-semantic-core/schema";
import { describe, expect, it } from "vitest";

import {
  parseCppCuteBrowserExactDistributionConvergenceAuthoringArguments,
  renderCppCuteBrowserExactDistributionConvergenceIdentity,
  renderCppCuteBrowserExactDistributionConvergenceResource,
} from
  "./cpp_cute_browser_exact_distribution_convergence_authoring.mjs";

const RESOURCE = {
  schema:
    "browsergrad.compiler.cpp-cute.browser-exact-distribution-convergence-observation",
  version: 1,
  authority:
    "package-pinned-local-engineering-exact-payload-convergence-observation-only",
  matrixId:
    `bg.cpp.browser-exact-distribution-convergence.sha256.${"a".repeat(64)}`,
  sourceRevision: "b".repeat(40),
  caseCount: 9,
  distribution: {},
  producer: {},
  webgpu: {},
  cases: [],
  claims: {},
} as const;
const RESOURCE_BYTES = canonicalJsonBytes(RESOURCE);
const PROJECTION = {
  schema:
    "browsergrad.compiler.cpp-cute.exact-distribution-convergence-authoring-projection",
  version: 1,
  authority: "package-authoring-projection-only",
  resource: RESOURCE,
  resourceSha256:
    createHash("sha256").update(RESOURCE_BYTES).digest("hex"),
  resourceByteLength: RESOURCE_BYTES.byteLength,
  sourceRevision: RESOURCE.sourceRevision,
  matrixId: RESOURCE.matrixId,
  caseCount: 9,
} as const;

describe("exact distribution convergence authoring", () => {
  it("accepts only one exact check or canonical absolute input mode", () => {
    expect(
      parseCppCuteBrowserExactDistributionConvergenceAuthoringArguments([
        "--check",
      ]),
    ).toEqual({ check: true, inputPath: undefined });
    expect(
      parseCppCuteBrowserExactDistributionConvergenceAuthoringArguments([
        "--",
        "--input=/private/tmp/matrix.json",
      ]),
    ).toEqual({
      check: false,
      inputPath: "/private/tmp/matrix.json",
    });
    for (const arguments_ of [
      [],
      ["--input=relative.json"],
      ["--", "--check", "--input=/tmp/a"],
      ["--input=/tmp/a", "--check"],
      ["--unknown"],
    ]) {
      expect(() =>
        parseCppCuteBrowserExactDistributionConvergenceAuthoringArguments(
          arguments_,
        ),
      ).toThrow();
    }
  });

  it("renders deterministic typed resource and identity modules", () => {
    const resource =
      renderCppCuteBrowserExactDistributionConvergenceResource(PROJECTION);
    expect(resource).toContain(
      "Generated by cpp_cute_browser_exact_distribution_convergence_authoring.mjs",
    );
    expect(resource).toContain('"caseCount": 9');
    expect(resource).toContain("as const satisfies JsonObject");

    const identity =
      renderCppCuteBrowserExactDistributionConvergenceIdentity(PROJECTION);
    expect(identity).toContain(`"${PROJECTION.resourceSha256}"`);
    expect(identity).toContain(`"${RESOURCE.sourceRevision}"`);
  });

  it("rejects projections whose resource identity is not authentic", () => {
    expect(() =>
      renderCppCuteBrowserExactDistributionConvergenceResource({
        ...PROJECTION,
        resourceSha256: "c".repeat(64),
      })
    ).toThrow();
  });
});
