import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    globals: false,
    include: [
      "scripts/cpp_cute_browser_build/*.test.ts",
      "tests/compiler/cpp_cute_browser_build_provenance_syntax.test.ts",
      "tests/compiler/cpp_cute_browser_build_lock.test.ts",
      "tests/compiler/cpp_cute_browser_runtime_abi.test.ts",
      "tests/compiler/cpp_cute_browser_runtime_profile.test.ts",
      "tests/compiler/cpp_cute_browser_assets.test.ts",
      "tests/compiler/cpp_cute_browser_emscripten_factory.test.ts",
      "tests/compiler/cpp_cute_browser_frontend_work_metrics.test.ts",
      "tests/compiler/cpp_cute_browser_generated_factory.test.ts",
      "tests/compiler/cpp_cute_browser_header_distribution_reproducibility.test.ts",
      "tests/compiler/cpp_cute_browser_wasm_compiler.test.ts",
      "tests/compiler/cpp_cute_browser_worker_bundle.test.ts",
      "tests/compiler/cpp_cute_browser_worker_controller.test.ts",
      "tests/compiler/cpp_cute_browser_worker_controller_production.test.ts",
      "tests/compiler/cpp_cute_browser_worker_entry.test.ts",
      "tests/compiler/cpp_cute_browser_worker_package_invocation.test.ts",
      "tests/compiler/cpp_cute_browser_worker_positive.test.ts",
      "tests/compiler/cpp_cute_browser_worker_protocol.test.ts",
      "tests/compiler/cpp_cute_browser_worker_runtime.test.ts",
      "tests/compiler/cpp_cute_browser_worker_transfer.test.ts",
      "tests/compiler/cpp_cute_frontend_artifact.test.ts",
      "tests/compiler/cpp_cute_frontend_profile.test.ts",
      "tests/compiler/verify_compiler_runner.test.ts",
    ],
    exclude: ["scripts/cpp_cute_browser_build/*_native.test.ts"],
    fileParallelism: true,
    maxWorkers: 4,
  },
});
