// Generated by scripts/generate-program-capability-registry.mjs.
// Source: architecture/platform-vocabulary.json#semanticCapabilities + #backends
// Do not edit by hand.

import {
  createSemanticBackendDefinition,
  createSemanticCapabilityDefinition,
  type SemanticBackendDefinition,
  type SemanticBackendDefinitionInput,
  type SemanticCapabilityDefinition,
  type SemanticCapabilityDefinitionInput,
} from "@unlocalhosted/browsergrad-semantic-core/capability";

const SEMANTIC_CAPABILITY_DEFINITION_INPUTS = [
  {
    "capabilityId": "browsergrad.layout.index-map",
    "semanticVersion": "1.0.0",
    "operationVersion": "browsergrad.layout@1",
    "preservationLevels": [
      "observable-equivalent"
    ],
    "owner": "@unlocalhosted/browsergrad-semantic-core",
    "evidenceIds": [
      "packages/browsergrad-semantic-core/tests/layout/artifact.test.ts",
      "packages/browsergrad-semantic-core/tests/layout/normalize-layout.test.ts",
      "packages/browsergrad-semantic-core/tests/layout/python-parity.test.ts"
    ]
  }
] as const satisfies readonly SemanticCapabilityDefinitionInput[];

const SEMANTIC_BACKEND_DEFINITION_INPUTS = [
  {
    "backendId": "browsergrad.compiler.semantic-reference",
    "semanticVersion": "0.1.0",
    "owner": "@unlocalhosted/browsergrad-compiler",
    "executionTiers": [
      "semantic-reference"
    ],
    "evidenceIds": [
      "packages/browsergrad-compiler/tests/compiler/core.test.ts",
      "packages/browsergrad-compiler/tests/compiler/pointer_scalar_memory_freeze.test.ts"
    ]
  },
  {
    "backendId": "browsergrad.jit.numpy-reference",
    "semanticVersion": "0.1.0",
    "owner": "@unlocalhosted/browsergrad-jit",
    "executionTiers": [
      "semantic-reference"
    ],
    "evidenceIds": [
      "packages/browsergrad-jit/tests-integration/arithmetic.test.ts"
    ]
  },
  {
    "backendId": "browsergrad.kernels.webgpu",
    "semanticVersion": "0.1.0",
    "owner": "@unlocalhosted/browsergrad-kernels",
    "executionTiers": [
      "webgpu-core",
      "webgpu-enhanced"
    ],
    "evidenceIds": [
      "packages/browsergrad-kernels/tests-browser/webgpu_real.test.ts",
      "packages/browsergrad-kernels/tests-browser/wgsl_program_webgpu.test.ts"
    ]
  }
] as const satisfies readonly SemanticBackendDefinitionInput[];

export const SEMANTIC_CAPABILITY_DEFINITIONS: readonly SemanticCapabilityDefinition[] =
  Object.freeze(
    SEMANTIC_CAPABILITY_DEFINITION_INPUTS.map((input) =>
      createSemanticCapabilityDefinition(input)
    ),
  );

export const SEMANTIC_BACKEND_DEFINITIONS: readonly SemanticBackendDefinition[] =
  Object.freeze(
    SEMANTIC_BACKEND_DEFINITION_INPUTS.map((input) =>
      createSemanticBackendDefinition(input)
    ),
  );
